### ISSUE TITLE
[Bug?]: yarn rw upgrade 6.6.4 -> 7.1.2 Error

### ISSUE THREAD

**Issue by furkanhalkan** [redwoodjs/redwood#10195]
### What's not working?

Hello everyone,

I'm trying to upgrade from version 6.6.4 to 7.1.2, but I'm encountering an error.

The error message is as follows:

yarn rw upgrade
✔ Checking latest version
✔ Updating your Redwood version
  ✔ Updating path\package.json
  ✔ Updating path\api\package.json
  ✔ Updating path\web\package.json
✖ Could not finish installation. Please run `yarn install` and then `yarn dedupe`, before continuing
◼ Refreshing the Prisma client
◼ De-duplicating dependencies
◼ One more thing..

------------------------------------------------------------------------------------------------------------------------
Error: Could not finish installation. Please run `yarn install` and then `yarn dedupe`, before continuing
    at yarnInstall (path\node_modules\@redwoodjs\cli\dist\commands\upgrade.js:174:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Task.run (path\node_modules\listr2\dist\index.cjs:2049:11)

------------------------------------------------------------------------------------------------------------------------
Need help?
 - Not sure about something or need advice? Reach out on our Forum (​https://community.redwoodjs.com/​)
 - Think you've found a bug? Open an issue on our GitHub (​https://github.com/redwoodjs/redwood​)
 - Here's your unique error reference to quote: '5d824878-87d6-4590-979e-9c774b51cfa4'
 
 $ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @redwoodjs/studio@npm:7.1.2: No candidates found
    at ge (path\.yarn\releases\yarn-3.6.3.cjs:439:8124)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 13)
    at async io (path\.yarn\releases\yarn-3.6.3.cjs:390:10398)
➤ YN0000: └ Completed in 5s 241ms
➤ YN0000: Failed with errors in 5s 246ms
➤ YN0061: @babel/plugin-proposal-nullish-coalescing-operator@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
➤ YN0061: @babel/plugin-proposal-optional-chaining@npm:7.21.0 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.

$ yarn dedupe
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ No packages can be deduped using the highest strategy
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @redwoodjs/studio@npm:7.1.2: No candidates found
    at ge (C:\wamp64\www\CubeDentalV2\CubeDental\.yarn\releases\yarn-3.6.3.cjs:439:8124)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 13)
    at async io (C:\wamp64\www\CubeDentalV2\CubeDental\.yarn\releases\yarn-3.6.3.cjs:390:10398)
➤ YN0000: └ Completed in 4s 973ms
➤ YN0000: Failed with errors in 4s 974ms
➤ YN0061: @babel/plugin-proposal-nullish-coalescing-operator@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
➤ YN0061: @babel/plugin-proposal-optional-chaining@npm:7.21.0 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.

My personal opinion is that I'm receiving this error because Redwood Studio is installed, but I don't want to remove Redwood Studio either.

Any help or suggestions would be greatly appreciated. Thank you!

### How do we reproduce the bug?

yarn rw exp studio

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.10.0 - ~\AppData\Local\Temp\xfs-06c2643c\node.CMD
    Yarn: 3.6.3 - ~\AppData\Local\Temp\xfs-06c2643c\yarn.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
  npmPackages:
    @redwoodjs/api: 7.1.2 => 6.6.4
    @redwoodjs/auth-dbauth-setup: 7.1.2 => 6.6.4
    @redwoodjs/cli-storybook: 7.1.2 => 6.6.4
    @redwoodjs/core: 7.1.2 => 6.6.4
    @redwoodjs/studio: 7.1.2 => 6.6.4
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hi @furkanhalkan 👋 Could you try removing the `@redwoodjs/studio` dependency from your project? I think then your upgrade will work and then you should be able to run `yarn rw studio` to get studio again

**Comment by furkanhalkan** [comment]
Thank you, @Josh-Walker-GM . I resolved the issue following your suggestion, but now I'm encountering a different problem with WebAuthn. Although the request to http://localhost:8910/.redwood/functions/auth?method=webAuthnAuthOptions is correct, I'm unable to log in. It continuously prompts for WebAuthn verification.

**Comment by Josh-Walker-GM** [comment]
Glad it helped @furkanhalkan! Would you be able to open a new issue with some more details on the webauthn issue you're experiencing?
