### ISSUE TITLE
[Bug?]: `yarn rw dev` doesn't work because of fsevents dep

### ISSUE THREAD

**Issue by danhab99** [redwoodjs/redwood#10824]
### What's not working?

Running `yarn rw dev` throws an error, the error doesn't go away after running `yarn install`

### How do we reproduce the bug?

```
workstation project(main) ✗: yarn rw dev
api | Internal Error: fsevents@patch:fsevents@npm%3A~2.3.2#~builtin<compat/fsevents>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
api |     at V0.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:435:5145)
api |     at kf.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:391:1264)
api |     at /home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8033
api |     at df (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:390:11070)
api |     at ge (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8013)
web | Internal Error: fsevents@patch:fsevents@npm%3A~2.3.2#~builtin<compat/fsevents>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
web |     at V0.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:435:5145)
web |     at kf.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:391:1264)
web |     at /home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8033
web |     at df (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:390:11070)
web |     at ge (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8013)
gen | Internal Error: fsevents@patch:fsevents@npm%3A~2.3.2#~builtin<compat/fsevents>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
gen |     at V0.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:435:5145)
gen |     at kf.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:391:1264)
gen |     at /home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8033
gen |     at df (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:390:11070)
gen |     at ge (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8013)
api | yarn cross-env NODE_ENV=development NODE_OPTIONS="--enable-source-maps"   yarn nodemon     --quiet     --watch "/home/dan/Documents/node/project/redwood.toml"     --exec "yarn rw-api-server-watch       --port 8911       --debug-port 18911       | rw-log-formatter" exited with code 1
web | yarn cross-env NODE_ENV=development rw-vite-dev  exited with code 1
gen | yarn rw-gen-watch exited with code 1
workstation project(main) ✗: yarn install
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 228ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide prettier (pfdc36), requested by prettier-plugin-tailwindcss.
➤ YN0002: │ web@workspace:web doesn't provide webpack (p0988a), requested by postcss-loader.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 725ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 508ms
➤ YN0000: · Done with warnings in 1s 712ms
workstation project(main) ✗: yarn rw dev
api | Internal Error: fsevents@patch:fsevents@npm%3A~2.3.2#~builtin<compat/fsevents>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
api |     at V0.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:435:5145)
api |     at kf.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:391:1264)
api |     at /home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8033
api |     at df (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:390:11070)
api |     at ge (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8013)
gen | Internal Error: fsevents@patch:fsevents@npm%3A~2.3.2#~builtin<compat/fsevents>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
gen |     at V0.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:435:5145)
gen |     at kf.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:391:1264)
gen |     at /home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8033
gen |     at df (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:390:11070)
gen |     at ge (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8013)
web | Internal Error: fsevents@patch:fsevents@npm%3A~2.3.2#~builtin<compat/fsevents>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
web |     at V0.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:435:5145)
web |     at kf.getCandidates (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:391:1264)
web |     at /home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8033
web |     at df (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:390:11070)
web |     at ge (/home/dan/Documents/node/project/.yarn/releases/yarn-3.6.3.cjs:439:8013)
api | yarn cross-env NODE_ENV=development NODE_OPTIONS="--enable-source-maps"   yarn nodemon     --quiet     --watch "/home/dan/Documents/node/project/redwood.toml"     --exec "yarn rw-api-server-watch       --port 8911       --debug-port 18911       | rw-log-formatter" exited with code 1
gen | yarn rw-gen-watch exited with code 1
web | yarn cross-env NODE_ENV=development rw-vite-dev  exited with code 1
```

### What's your environment? (If it applies)

```shell
System:
  OS: Linux 5.15 Manjaro Linux
  Shell: 5.2.26 - /bin/bash
Binaries:
  Node: 20.12.2 - /tmp/xfs-05d0e340/node
  Yarn: 3.6.3 - /tmp/xfs-05d0e340/yarn
Databases:
  SQLite: 3.46.0 - /usr/bin/sqlite3
npmPackages:
  @redwoodjs/cli-storybook: 7.4.3 => 7.4.3 
  @redwoodjs/core: 7.4.3 => 7.4.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @danhab99 thanks for reporting. I'll have a look at this issue but may need some help from the community as I don't run Linux. But we do CI on some Linux flavors and will see if that has reported any issues recently.

**Comment by dthyresson** [comment]
@Josh-Walker-GM as I don't have Linux, might you be able to verify this issue? I don't believe I see it happening our our Linux CI runs.

**Comment by Josh-Walker-GM** [comment]
Yeah leave this one with me and I'll try to get back in the day or two

**Comment by Josh-Walker-GM** [comment]
Hey @danhab99 sorry I forgot to reply at the time! I spent a little time trying to reproduce this locally but couldn't. I'll set myself a reminder to try again with fresh eyes and a fresh setup later this week.

Was there any change in status on your end in the meantime?

**Comment by danhab99** [comment]
No change, still can't work on that project

**Comment by danhab99** [comment]
Figured out the problem, didn't setup corepack properly. Closing

**Comment by Tobbe** [comment]
@danhab99 Thanks for getting back to us with your solution!
