### ISSUE TITLE
[Bug?]: Pre-render does not work

### ISSUE THREAD

**Issue by MartinDawson** [redwoodjs/redwood#10850]
### What's not working?

Pre-render does not work on latest redwoodjs versions.

### How do we reproduce the bug?

- Use latest redwoodjs 7.7.1 packages
- Add prerender to a route.

Output:

```ts
function getRouteHooksFilePath(routeFilePath) {
  const routeHooksFilePathTs = routeFilePath.replace(
    /\.[jt]sx?$/,
    ".routeHooks.ts"
  );

async function expandRouteParameters(route) {
  const routeHooksFilePath = getRouteHooksFilePath(route.filePath);

```

filePath is undefined so it throws the below error:

```ts
yarn run rw build(base) martin@martin-HP-EliteBook-840-G5:~/Documents/findmyfetish$ yarn run rw build
Debugger attached.
yarn run v1.22.19
$ /home/martin/Documents/findmyfetish/node_modules/.bin/rw build
Debugger attached.
✔ Generating Prisma Client...
✔ Verifying graphql schema...
✔ Building API...
✔ Building Web...

Creating 200.html...
Starting prerendering...
Debugger attached.
$ /home/martin/Documents/findmyfetish/node_modules/.bin/rw prerender
Debugger attached.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TypeError: Cannot read properties of undefined (reading 'replace')
    at getRouteHooksFilePath (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/prerenderHandler.js:55:46)
    at expandRouteParameters (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/prerenderHandler.js:72:30)
    at /home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/prerenderHandler.js:125:36
    at Array.map (<anonymous>)
    at getTasks (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/prerenderHandler.js:125:21)
    at handler (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/prerenderHandler.js:226:28)
    at Object.handler (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/prerender.js:63:10)
    at async runYargs (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/index.js:151:3)
    at async /home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/index.js:105:7
    at async main (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/index.js:94:3)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Need help?
 - Not sure about something or need advice? Reach out on our Forum
 - Think you've found a bug? Open an issue on our GitHub
 - Here's your unique error reference to quote: '9fb1138a-749b-4375-acb3-070962d1fabe'
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: Command failed with exit code 1: yarn rw prerender
    at makeError (/home/martin/Documents/findmyfetish/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/martin/Documents/findmyfetish/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async triggerPrerender (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/buildHandler.js:183:5)
    at async /home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/buildHandler.js:195:7
    at async timedTelemetry (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/telemetry/dist/telemetry.js:70:18)
    at async handler (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/commands/buildHandler.js:192:3)
    at async runYargs (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/index.js:151:3)
    at async /home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/index.js:105:7
    at async main (/home/martin/Documents/findmyfetish/node_modules/@redwoodjs/cli/dist/index.js:94:3)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Need help?
 - Not sure about something or need advice? Reach out on our Forum
 - Think you've found a bug? Open an issue on our GitHub
 - Here's your unique error reference to quote: '7aff2b4f-b3b9-4bb8-b52d-46a2dad82a25'
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...
```

### What's your environment? (If it applies)

```shell
Chrome: 125.0.6422.141
  npmPackages:
    @redwoodjs/cli-data-migrate: 7.7.1 => 7.7.1 
    @redwoodjs/core: 7.7.1 => 7.7.1 
    @redwoodjs/project-config: 7.7.1 => 7.7.1 
  redwood.toml:
    [web]
      title = "FindMyFetish"
      port = 8910
      apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
      includeEnvironmentVariables = [
        # Add any ENV vars that should be available to the web side to this array
        # See https://redwoodjs.com/docs/environment-variables#web
      ]
    [api]
      port = 8911
    [browser]
      open = true
    [notifications]
      versionUpdates = ["latest"]
Done in 3.12s.
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @MartinDawson and thanks for reporting.

I attempted to reproduce with a very basic pretender case and did not encounter the error you had -- but your setup is likely a different.

Steps:

1. `yarn create redwood-app ~/tmp/prernder-test` (TS on)
2. `yarn rw g page BlogPost` 
3. Gave it a param and prerender`<Route path="/blog-post/{id:Int}" page={BlogPostPage} name="blogPost" prerender />`
4. Added param to page

```ts
import { Link, routes } from '@redwoodjs/router'
import { Metadata } from '@redwoodjs/web'

const BlogPostPage = ({ id }: { id: number }) => {
  return (
    <>
      <Metadata title="BlogPost" description="BlogPost page" />

      <h1>BlogPostPage - {id}</h1>
      <p>
        Find me in <code>./web/src/pages/BlogPostPage/BlogPostPage.tsx</code>
      </p>
      <p>
        My default route is named <code>blogPost</code>, link to me with `
        <Link to={routes.blogPost({ id })}>BlogPost</Link>`
      </p>
    </>
  )
}

export default BlogPostPage
```
 
6.  added `web/src/pages/BlogPostPage/BlogPostPage.routeHooks.js`

```ts
export function routeParameters() {
  return [{ id: 1 }, { id: 2 }, { id: 3 }]
}\
```

8. `yarn rw build`
 
```bash
✔ Building Web...

Creating 200.html...
Starting prerendering...
✔ Prerendering /blog-post/1 -> web/dist/blog-post/1.html
✔ Prerendering /blog-post/2 -> web/dist/blog-post/2.html
✔ Prerendering /blog-post/3 -> web/dist/blog-post/3.html
```

8. `yarn rw serve`

and when I visit a preredendered page see the `2` id in pre-rendered markup

![image](https://github.com/redwoodjs/redwood/assets/1051633/0e3bd130-e4b0-49fb-a376-c16d6255c577)


but if I go to a hook not pre-rendered then renders on navigation

![image](https://github.com/redwoodjs/redwood/assets/1051633/1604e95e-7880-46d1-8f88-f7a49d3b6efb)

---

Not sure I understand how you used:

```
function getRouteHooksFilePath(routeFilePath) {
  const routeHooksFilePathTs = routeFilePath.replace(
    /\.[jt]sx?$/,
    ".routeHooks.ts"
  );

async function expandRouteParameters(route) {
  const routeHooksFilePath = getRouteHooksFilePath(route.filePath);
```

Could you provide some examples maybe with what the Page is doing that might cause that error?

I'll also try with a GraphQL query/cell and if that is different will report back,

**Comment by dthyresson** [comment]
FYI, tired with a cell and GraphQL query as well and my post and title was pre-rendered: 
![image](https://github.com/redwoodjs/redwood/assets/1051633/98753953-f2dc-451e-bffb-e05fd56ceef5)

**Comment by dthyresson** [comment]
@MartinDawson Thanks much for the repo.

I cloned and just did a `yarn rw build` and seemed to work (am on OSX).

```
prerender-broken main % yarn rw build
✔ Generating Prisma Client...
✔ Verifying graphql schema...
✔ Building API...
✔ Building Web...

Creating 200.html...
Starting prerendering...
✔ Prerendering /blog-post/1 -> web/dist/blog-post/1.html
✔ Prerendering /blog-post/2 -> web/dist/blog-post/2.html
✔ Prerendering /blog-post/3 -> web/dist/blog-post/3.html
```

Am on OSX and

```
prerender-broken main % node -v
v20.10.0
prerender-broken main % yarn -v
4.3.0
prerender-broken main % npm -v
10.2.3
```

I'll try node 20.14.0.

**Comment by dthyresson** [comment]
> using v1.22.19 of `yarn` somehow in my installs and builds. Maybe cause it is bundled with nvm? not sure.

It might be. I was going down that path testing yesterday and used nvm to update node and all off the sudden my yarn reverted from v4 to v1 and I struggled to get to back to using 4. Must be with nvm.

Glad it's working again.
