### ISSUE TITLE
[Bug?]: Failing yarn rw upgrade to v8 (possibly storybook related)

### ISSUE THREAD

**Issue by lintfail** [redwoodjs/redwood#11465]
### What's not working?

Seeing the following even after `yarn install ` and `yarn dedup`

```
✔ Checking latest version
✔ Updating your Redwood version
  ✔ Updating /Users/ybv/code/webapps/surverysort/package.json
  ✔ Updating /Users/ybv/code/webapps/surverysort/api/package.json
  ✔ Updating /Users/ybv/code/webapps/surverysort/web/package.json
✔ Removing CLI cache
✖ Could not finish installation. Please run `yarn install` and then `yarn dedupe`,
  before continuing
◼ Refreshing the Prisma client
◼ De-duplicating dependencies
◼ One more thing..
-----------------------------------------------------------------------------------------
Error: Could not finish installation. Please run `yarn install` and then `yarn dedupe`, before continuing
    at yarnInstall (/Users/ybv/code/webapps/surverysort/node_modules/@redwoodjs/cli/dist/commands/upgrade.js:222:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Task.run (/Users/ybv/code/webapps/surverysort/node_modules/listr2/dist/index.cjs:2049:11)

-----------------------------------------------------------------------------------------
Need help?
 - Not sure about something or need advice? Reach out on our Forum (​https://community.redwoodjs.com/​)
 - Think you've found a bug? Open an issue on our GitHub (​https://github.com/redwoodjs/redwood​)
 - Here's your unique error reference to quote: 'bf54d34b-6026-4953-be8c-9e81865d72fd'
---------------------------------------------------------------------------------------
```

### How do we reproduce the bug?

running `yarn rw upgrade`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.6.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - /private/var/folders/z6/v_slqjb52537sk4256_bq7sm0000gn/T/xfs-aaec4b8d/node
    Yarn: 4.3.0 - /private/var/folders/z6/v_slqjb52537sk4256_bq7sm0000gn/T/xfs-aaec4b8d/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.6
  npmPackages:
    @redwoodjs/auth-clerk-setup: 8.0.0 => 7.7.4 
    @redwoodjs/auth-dbauth-setup: 8.0.0 => 7.7.4 
    @redwoodjs/cli-data-migrate: 8.0.0 => 7.7.4 
    @redwoodjs/cli-storybook: 8.0.0 => 7.7.4 
    @redwoodjs/core: 8.0.0 => 7.7.4 
    @redwoodjs/project-config: 8.0.0 => 7.7.4 
    @redwoodjs/realtime: 8.0.0 => 7.7.4 
    @redwoodjs/studio: 11 => 11.4.0 
  redwood.toml:
    [web]
      title = "Redwood App"
      port = 8910
      apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
      includeEnvironmentVariables = [
        "CLERK_PUBLISHABLE_KEY"
        # Add any ENV vars that should be available to the web side to this array
        # See https://redwoodjs.com/docs/environment-variables#web
      ]
    [api]
      port = 8911
    [browser]
      open = true
    [notifications]
      versionUpdates = ["latest"]
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Can you please try removing the `@redwoodjs/cli-storybook` package from your root `package.json` file? In v8 we removed this package and now only support and publish the `@redwoodjs/cli-storybook-vite` package.

**Comment by lintfail** [comment]
Thanks, @Josh-Walker-GM that worked
