### ISSUE TITLE
`yarn rw db migrate save` throws error, but ok with `prisma2 migrate save…`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#123]
Going through tutorial (line#386) and ran into error when running `yarn rw db migrate save` from directory root (see below).

I was able to run the prisma2 command successfully from directory `api/prisma`:  
`yarn prisma2 migrate save —experimental` == good to go

**ERROR**
```
$ yarn rw db migrate save
yarn run v1.22.0
$ /Users/price/Repos/redwoodblog/node_modules/.bin/rw db migrate save
$ /Users/price/Repos/redwoodblog/node_modules/.bin/prisma2 migrate save --experimental
Error in Create Database Dialog
Error: Raw mode is not supported on the current process.stdin, which Ink uses as
 input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#isr
awmodesupported
    at /Users/price/Repos/redwoodblog/node_modules/prisma2/build/index.js:2:2794
332
    at /Users/price/Repos/redwoodblog/node_modules/prisma2/build/index.js:2:2452
031
    at commitHookEffectList (/Users/price/Repos/redwoodblog/node_modules/prisma2
/build/index.js:2:1195732)
    at commitPassiveHookEffects (/Users/price/Repos/redwoodblog/node_modules/pri
sma2/build/index.js:2:1196784)
    at Object.as (/Users/price/Repos/redwoodblog/node_modules/prisma2/build/inde
x.js:2:1188992)
    at invokeGuardedCallback (/Users/price/Repos/redwoodblog/node_modules/prisma
2/build/index.js:2:1191527)
    at flushPassiveEffectsImpl (/Users/price/Repos/redwoodblog/node_modules/pris
ma2/build/index.js:2:1227209)
    at unstable_runWithPriority (/Users/price/Repos/redwoodblog/node_modules/pri
sma2/build/index.js:2:43340)
    at runWithPriority (/Users/price/Repos/redwoodblog/node_modules/prisma2/buil
d/index.js:2:1077079)
    at flushPassiveEffects (/Users/price/Repos/redwoodblog/node_modules/prisma2/
build/index.js:2:1226809)
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in App
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
✨  Done in 1.84s.
```

**Comment by peterp** [comment]
Hmmm... I don't think this is using the latest "redwood cli," since the error output contains something about raw mode in react-ink, and we've moved away from that.

**Comment by thedavidprice** [comment]
My `package.json` in the App:
```
// node_modules/@redwoodjs/cli/package.json

{
  "name": "@redwoodjs/cli",
  "description": "The Redwood Command Line",
  "version": "0.0.1-alpha.28",
  ...
...
}
```
And version from cli:
```
$ yarn rw --version
yarn run v1.22.0
$ /Users/price/Repos/redwoodblog/node_modules/.bin/rw --version
0.0.1-alpha.28
```

¯\_(ツ)_/¯

**Comment by thedavidprice** [comment]
@peterp Assuming this one was covered in the recent PRs. Will loop back if I have further questions next pass through the tutorial. 

Closing for now.
