### ISSUE TITLE
Error: Command failed with ENOENT: yarn install\nspawn yarn install ENOENT

### ISSUE THREAD

**Issue by hgareeballa** [redwoodjs/redwood#1239]
Getting below error while trying to create redwood app under windows !
node -v
v13.13.0
yarn -v
1.22.5
--
C:\myredwood>yarn create redwood-app ./redwoodblog
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-redwood-app@0.19.1" with binaries:
      - create-redwood-app
  √ Creating Redwood app
    √ Creating directory 'C:\myredwood\redwoodblog'
    √ Downloading latest release
    √ Extracting latest release
    √ Clean up
  > Installing packages
    √ Checking node and yarn compatibility
    × Running `yarn install`... (This could take a while)
      → info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error: Command failed with ENOENT: yarn install
spawn yarn install ENOENT
error Couldn't find the binary git
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at notFoundError (C:\Users\elmuzamh\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\elmuzamh\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\elmuzamh\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn yarn install',
  path: 'yarn install',
  spawnargs: [],
  originalMessage: 'spawn yarn install ENOENT',
  shortMessage: 'Command failed with ENOENT: yarn install\nspawn yarn install ENOENT',
  command: 'yarn install',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.5\n' +
    '[1/5] Validating package.json...\n' +
    '[2/5] Resolving packages...\n' +
    '[3/5] Fetching packages...\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: "error Couldn't find the binary git",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}
error Command failed.
Exit code: 1
Command: C:\Users\elmuzamh\AppData\Local\Yarn\bin\create-redwood-app
Arguments: ./redwoodblog
Directory: C:\myredwood
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

C:\myredwood>node -v
v13.13.0

C:\myredwood>yarn -v
1.22.5

C:\myredwood>

**Comment by peterp** [comment]
It looks like you may need to install git

> error Couldn't find the binary git

I don't know why git is a requirement, @RobertBroersma do you think this has something to do with those checks you added to the test suite? If so, I would _really_ like to remove that since it makes containerisation a bit more complicated.

**Comment by RobertBroersma** [comment]
@peterp Not sure which tests you mean... Error seems like it's coming from `yarn install`, is that right?

**Comment by peterp** [comment]
@RobertBroersma Ah, I'm a dumbass, I thought you had a package that checked if it the repo was in `git` or `mercurial` but I see you're just using trying to run them in a shell.

**Comment by hgareeballa** [comment]
Its working now after installing git O_o

**Comment by RobertBroersma** [comment]
@peterp I can't really tell from my Google searches if Yarn requires git or if it's because of this package: https://github.com/redwoodjs/redwood/blob/main/packages/auth/package.json#L17

Does `create-redwood-app` come with Auth out of the box nowadays?
