### ISSUE TITLE
Add top-level `context` to services

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#127]
From my quick pseudo code from our call:

```
import { PrismaClient } from '@prisma/client'
import { RedwoodContext} from '@redwoodjs/api'

const db = new PrismaClient()
const context = new RedwoodContext()

export const posts = () => {
  return db.post.findMany()
}
```

**Comment by chris-hailstorm** [comment]
@cannikin I realize that's just pseudocode -- when I tried that snip in one of my service files:

```
21:03:51 api | /Users/chris/temp/aw-hammer-060-temp/api/src/services/projects/projects.js:22
21:03:51 api | const context = new _api.RedwoodContext();
21:03:51 api |                 ^
21:03:51 api |
21:03:51 api | TypeError: _api.RedwoodContext is not a constructor
21:03:51 api |     at Object.<anonymous> (/Users/chris/temp/aw-hammer-060-temp/api/src/services/projects/projects.js:8:17)
21:03:51 api |     at Module._compile (internal/modules/cjs/loader.js:955:30)
21:03:51 api |     at Module._compile (/Users/chris/temp/aw-hammer-060-temp/node_modules/pirates/lib/index.js:99:24)
21:03:51 api |     at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
21:03:51 api |     at Object.newLoader [as .js] (/Users/chris/temp/aw-hammer-060-temp/node_modules/pirates/lib/index.js:104:7)
21:03:51 api |     at Module.load (internal/modules/cjs/loader.js:811:32)
21:03:51 api |     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
21:03:51 api |     at Module.require (internal/modules/cjs/loader.js:848:19)
21:03:51 api |     at require (internal/modules/cjs/helpers.js:74:18)
21:03:51 api |     at Object.<anonymous> (/Users/chris/temp/aw-hammer-060-temp/api/src/functions/graphql.js:21:59)
error Command failed with exit code 1.
```

Can you give a quick example of how to use the context?

**Comment by cannikin** [comment]
@chris-hailstorm See the PR from Peter, I’m actually not sure how he ended up solving this... https://github.com/redwoodjs/redwood/pull/139

**Comment by chris-hailstorm** [comment]
Here's a simple example that seems to work:

```
/* api/src/functions/graphql.js */

import {
  createGraphQLHandler,
  makeMergedSchema,
  makeServices,
} from '@redwoodjs/api'

import importAll from '@redwoodjs/api/importAll.macro'

import { db } from 'src/lib/db'

const schemas = importAll('api', 'graphql')
const services = importAll('api', 'services')

const context = ({context, event}) => {
  console.log('GraphQL custom context handler')
  console.log(context)
  console.log(event)
  return context
}

export const handler = createGraphQLHandler({
  schema: makeMergedSchema({
    schemas,
    services: makeServices({ services }),
  }),
  context,
  db,
})
```

Now I'm trying to figure out how to get more info into the context from the client side.

**Comment by cannikin** [comment]
Calling @peterp, help!

**Comment by peterp** [comment]
@chris-hailstorm The `event` contains a bunch of useful things, but I think mostly the way of getting stuff from web -> api (especially authentication tokens) would be to add them to the headers of apollo graphql client.

I need to look into how we do that via the Redwood Providers. It may not be technically possible right now, but I need to double check that.
