### ISSUE TITLE
Test command fails on BlogPostCell.js Success component: possible Mock issue (v0.20.0)

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1396]
@peterp @RobertBroersma 

After running the Cypress E2E on a new v0.20.0 project, I ran the Test command, which is successful for all tests except `BlogPostCell.js`.

Given the output `Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`, it seems to be an issue with the Mocking.

See below for full error output:
<details>
```bash
FAIL   web  web/src/components/BlogPostsCell/BlogPostsCell.test.js
  BlogPostsCell
    ✕ Success renders successfully (82 ms)
    ○ skipped Loading renders successfully
    ○ skipped Empty renders successfully
    ○ skipped Failure renders successfully

  ● BlogPostsCell › Success renders successfully

    Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

      21 |
      22 |   test('Success renders successfully', async () => {
    > 23 |     render(<Success blogPosts={standard().blogPosts} />)
         |     ^
      24 |     expect(screen.getByText(/42/i)).toBeInTheDocument()
      25 |   })
      26 | })

      at reconcileChildFibers (../node_modules/react-dom/cjs/react-dom.development.js:14348:23)
      at reconcileChildren (../node_modules/react-dom/cjs/react-dom.development.js:16762:28)
      at mountIndeterminateComponent (../node_modules/react-dom/cjs/react-dom.development.js:17542:5)
      at beginWork (../node_modules/react-dom/cjs/react-dom.development.js:18596:16)
      at HTMLUnknownElement.callCallback (../node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (../node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (../node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at beginWork$1 (../node_modules/react-dom/cjs/react-dom.development.js:23203:7)
      at performUnitOfWork (../node_modules/react-dom/cjs/react-dom.development.js:22157:12)
      at workLoopSync (../node_modules/react-dom/cjs/react-dom.development.js:22130:22)
      at performSyncWorkOnRoot (../node_modules/react-dom/cjs/react-dom.development.js:21756:9)
      at scheduleUpdateOnFiber (../node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (../node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at ../node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (../node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (../node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (../node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at ../node_modules/@testing-library/react/dist/pure.js:98:25
      at batchedUpdates$1 (../node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (../node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (../node_modules/@testing-library/react/dist/pure.js:94:26)
      at customRender (../node_modules/@redwoodjs/testing/dist/customRender.js:20:29)
      at _callee3$ (src/components/BlogPostsCell/BlogPostsCell.test.js:23:5)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (../node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
      at _next (../node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
      at ../node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:34:7
      at new Wrapper (../node_modules/core-js-pure/internals/export.js:15:24)
      at Object.<anonymous> (../node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:23:12)

  console.error
    Error: Uncaught [Error: Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.]
        at reportException (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
        at invokeEventListeners (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:22157:12) Error: Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
        at reconcileChildFibers (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:14348:23)
        at reconcileChildren (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:16762:28)
        at mountIndeterminateComponent (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:17542:5)
        at beginWork (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:18596:16)
        at HTMLUnknownElement.callCallback (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:188:14)
        at HTMLUnknownElement.callTheUserObjectsOperation (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
        at innerInvokeEventListeners (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
        at invokeEventListeners (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/price/Repos/xx-delete/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
        at workLoopSync (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
        at performSyncWorkOnRoot (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
        at scheduleUpdateOnFiber (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:21188:7)
        at updateContainer (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:24373:3)
        at /Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:24758:7
        at unbatchedUpdates (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:21903:12)
        at legacyRenderSubtreeIntoContainer (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:24757:5)
        at Object.render (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:24840:10)
        at /Users/price/Repos/xx-delete/node_modules/@testing-library/react/dist/pure.js:98:25
        at batchedUpdates$1 (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
        at act (/Users/price/Repos/xx-delete/node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
        at render (/Users/price/Repos/xx-delete/node_modules/@testing-library/react/dist/pure.js:94:26)
        at customRender (/Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/customRender.js:20:29)
        at _callee3$ (/Users/price/Repos/xx-delete/web/src/components/BlogPostsCell/BlogPostsCell.test.js:23:5)
        at tryCatch (/Users/price/Repos/xx-delete/node_modules/regenerator-runtime/runtime.js:63:40)
        at Generator.invoke [as _invoke] (/Users/price/Repos/xx-delete/node_modules/regenerator-runtime/runtime.js:293:22)
        at Generator.next (/Users/price/Repos/xx-delete/node_modules/regenerator-runtime/runtime.js:118:21)
        at asyncGeneratorStep (/Users/price/Repos/xx-delete/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
        at _next (/Users/price/Repos/xx-delete/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
        at /Users/price/Repos/xx-delete/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:34:7
        at new Promise (<anonymous>)
        at new Wrapper (/Users/price/Repos/xx-delete/node_modules/core-js-pure/internals/export.js:15:24)
        at Object.<anonymous> (/Users/price/Repos/xx-delete/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:23:12)
        at Object.asyncJestTest (/Users/price/Repos/xx-delete/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
        at /Users/price/Repos/xx-delete/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/Users/price/Repos/xx-delete/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /Users/price/Repos/xx-delete/node_modules/jest-jasmine2/build/queueRunner.js:75:41
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

      at VirtualConsole.<anonymous> (../node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at innerInvokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
      at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)

  console.error
    The above error occurred in the <Success> component:
        in Success
        in FlashProvider (created by RedwoodProvider)
        in ApolloProvider (created by GraphQLProvider)
        in GraphQLProvider (created by GraphQLProviderWithAuth)
        in GraphQLProviderWithAuth (created by RedwoodProvider)
        in RedwoodProvider (created by MockProviders)
        in MockProviders (created by wrapper)
        in wrapper

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      at logCapturedError (../node_modules/react-dom/cjs/react-dom.development.js:19527:21)
      at logError (../node_modules/react-dom/cjs/react-dom.development.js:19564:5)
      at update.callback (../node_modules/react-dom/cjs/react-dom.development.js:20708:5)
      at callCallback (../node_modules/react-dom/cjs/react-dom.development.js:12490:12)
      at commitUpdateQueue (../node_modules/react-dom/cjs/react-dom.development.js:12511:9)
      at commitLifeCycles (../node_modules/react-dom/cjs/react-dom.development.js:19883:11)
      at commitLayoutEffects (../node_modules/react-dom/cjs/react-dom.development.js:22803:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 skipped, 4 total
Snapshots:   0 total
Time:        4.143 s, estimated 5 s
Ran all test suites related to changed files.
```
</details>

**Comment by thedavidprice** [comment]
And I'm seeing a similar case when running Storybook. On the same project as above, I ran `rw Storybook`. All components and states seem to render correctly _except_ for `BlogPostsCell.js` Success component.

Same output here as above: `Error: Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

See below for full error output:
<details>
```bash
Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: Success(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:121065:23)
    at reconcileChildren (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:123479:28)
    at mountIndeterminateComponent (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:124259:5)
    at beginWork (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:125313:16)
    at HTMLUnknownElement.callCallback (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:106905:14)
    at Object.invokeGuardedCallbackDev (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:106954:16)
    at invokeGuardedCallback (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:107009:31)
    at beginWork$1 (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:129920:7)
    at performUnitOfWork (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:128871:12)
    at workLoopSync (http://localhost:7910/main.c40b24817b9e729e3438.bundle.js:128847:22)
```
</details>

**Comment by thedavidprice** [comment]
Nothing to see here 👀
