### ISSUE TITLE
Running tests on NavLink component throws "TypeError: Cannot read property 'pathname' of undefined"

### ISSUE THREAD

**Issue by brgmnn** [redwoodjs/redwood#1676]
When running the default generated test on a component that uses a `NavLink` you get a `TypeError: Cannot read property 'pathname' of undefined`. I managed to reproduce this with the following component:
```javascript
import React from "react";
import { routes, NavLink } from "@redwoodjs/router";

const HerculesLayout = (props) => {
  return <NavLink to={routes.home()}>Home</NavLink>;
};

export default HerculesLayout;
```
And the following test which hasn't been modified and was generated by the layout scaffolding:
```javascript
import { render } from "@redwoodjs/testing";

import HerculesLayout from "./HerculesLayout";

describe("HerculesLayout", () => {
  it("renders successfully", () => {
    expect(() => {
      render(<HerculesLayout />);
    }).not.toThrow();
  });
});
```
This gives me the following error in the console when running `yarn rw test`:
```shell
 HerculesLayout
    ✕ renders successfully (96 ms)

  ● HerculesLayout › renders successfully

    expect(received).not.toThrow()

    Error name:    "TypeError"
    Error message: "Cannot read property 'pathname' of undefined"

           6 |   it("renders successfully", () => {
           7 |     expect(() => {
        >  8 |       render(<HerculesLayout />);
             |       ^
           9 |     }).not.toThrow();
          10 |   });
          11 | });

          at useMatch (node_modules/@redwoodjs/router/dist/links.js:32:62)
          at node_modules/@redwoodjs/router/dist/links.js:62:21
          at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
          at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:16816:20)
          at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18645:16)
          at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
          at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
          at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
          at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
          at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
          at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
          at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
          at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
          at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
          at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
          at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
          at node_modules/react-dom/cjs/react-dom.development.js:24758:7
          at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
          at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
          at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
          at node_modules/@testing-library/react/dist/pure.js:99:25
          at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
          at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
          at render (node_modules/@testing-library/react/dist/pure.js:95:26)
          at customRender (node_modules/@redwoodjs/testing/dist/customRender.js:20:29)
          at web/src/layouts/HerculesLayout/HerculesLayout.test.js:8:7
          at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:83:11)
          at Object.toThrow (node_modules/expect/build/index.js:338:21)
          at Object.<anonymous> (web/src/layouts/HerculesLayout/HerculesLayout.test.js:9:12)

       7 |     expect(() => {
       8 |       render(<HerculesLayout />);
    >  9 |     }).not.toThrow();
         |            ^
      10 |   });
      11 | });
      12 |

      at Object.<anonymous> (src/layouts/HerculesLayout/HerculesLayout.test.js:9:12)
```
The diagnostic info from `yarn rw info` on my machine is:
```shell
yarn run v1.22.10
$ /Users/daniel/Code/node_modules/.bin/rw info

  System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1611790331077-0.2843548795228614/node
    Yarn: 1.22.10 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1611790331077-0.2843548795228614/yarn
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @redwoodjs/core: 0.23.0 => 0.23.0

✨  Done in 1.50s.
```

**Comment by Tobbe** [comment]
Hi @brgmnn, thanks for the bug report

So this is what's happening

`<NavLink>` uses the `useMatch()` hook to see if what you're passing as the `to` prop matches the current url. `useMatch()` in turns uses `useLocation()`. `useLocation()` internally uses `LocationContext`, which doesn't have a context Provider when you run the test, so it returns `undefined`.

**Comment by brgmnn** [comment]
Thanks for looking in to this and opening a PR to address it @Tobbe! I look forward to using this in our tests when we upgrade to the next release 👍
