### ISSUE TITLE
[v0.24.0] `yarn rw test web` is Failing

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1688]
## How to Reproduce
- Run through the E2E process to create a new project and add code per E2E.
- Enter the new project and run `yarn rw test web --no-watch`

Results in the following errors:
```console
 FAIL   web  web/src/pages/HomePage/HomePage.test.js
  ● Test suite failed to run

    Cannot find module '@redwoodjs/router/dist/index' from '../node_modules/@redwoodjs/testing/dist/MockRouter.js'

    Require stack:
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/MockRouter.js
      src/Routes.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/MockProviders.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/customRender.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/index.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockRouter.js:31:14)
```

**Comment by thedavidprice** [comment]
NOTE: @cannikin and I also identified an issue with the API generated tests. He's separately working on fixing the templates.

**Comment by peterp** [comment]
Hmmm... When I copied the code using `yarn rwt cpw` this error goes away.

**Comment by thedavidprice** [comment]
Bummer, the PR didn't do the trick.

Ran through E2E but also did the simplest possible path to reproduce:
```
yarn babel-node src/create-redwood-app.js ~/Repos/test-project
cd ~/Repos/test-project
yarn rw upgrade -t canary
yarn rw g page home /
yarn rw test --no-watch
```

Web test fails to run with error:
```console
$ /Users/price/Repos/xx-delete/node_modules/.bin/jest --passWithNoTests --runInBand --config /Users/price/Repos/xx-delete/node_modules/@redwoodjs/core/config/jest.config.js --projects web api
 FAIL   web  web/src/pages/HomePage/HomePage.test.js
  ● Test suite failed to run

    Cannot find module '@redwoodjs/router/dist/index' from '../node_modules/@redwoodjs/testing/dist/MockRouter.js'

    Require stack:
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/MockRouter.js
      src/Routes.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/MockProviders.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/customRender.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/testing/dist/index.js
      /Users/price/Repos/xx-delete/node_modules/@redwoodjs/core/dist/configs/browser/jest.setup.js

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockRouter.js:31:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.779 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✨  Done in 15.93s.
```
