### ISSUE TITLE
useSelector breaking v0.24.0

### ISSUE THREAD

**Issue by rechandler** [redwoodjs/redwood#1726]
could not find react-redux context value; please ensure the component is wrapped in a <Provider>
Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:136408:11)
    at useSelector (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:136530:28)
    at VehicleInfo (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:151707:86)
    at renderWithHooks (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:124957:18)
    at mountIndeterminateComponent (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:127636:13)
    at beginWork (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:128750:16)
    at HTMLUnknownElement.callCallback (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:110342:14)
    at Object.invokeGuardedCallbackDev (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:110391:16)
    at invokeGuardedCallback (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:110446:31)
    at beginWork$1 (http://localhost:7910/main.8dc4a9e79da6f0a4eb85.bundle.js:133357:7)

This is the error being thrown from components that use the useSelector hook. Downgrading to v 0.23.0 fixes the issue. 
Before this happened I ran `yarn rw upgrade` so all the rw components were updated to 0.24.0.

Any component that uses useSelector won't work

**Comment by rechandler** [comment]
The issue for anyone else who might come across this was because RedwoodProvider was replaced by Redwood Apollo Provider.
https://github.com/redwoodjs/redwood/pull/1639
Swap those out and you'll be good to go.

**Comment by thedavidprice** [comment]
Full details and "How to upgrade" found in respective sections of the v0.24 Release Notes:
https://github.com/redwoodjs/redwood/releases/tag/v0.24.0
