### ISSUE TITLE
Error when running app after upgrading

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#1883]
After I upgrade my app to .26.2 I get the following error when running `rw dev`:

```
api | Running at 'http://localhost:8911'
api | Watching files in '/Users/jeroen/Development/ydp/api/src/functions'
web | internal/validators.js:124
web |     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
web |     ^
web |
web | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
web |     at validateString (internal/validators.js:124:11)
web |     at Object.resolve (path.js:980:7)
web |     at module.exports (/Users/jeroen/Development/ydp/node_modules/@redwoodjs/core/config/webpack.common.js:190:35)
web |     at Object.<anonymous> (/Users/jeroen/Development/ydp/node_modules/@redwoodjs/core/config/webpack.development.js:12:26)
web |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
web |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
web |     at Module.load (internal/modules/cjs/loader.js:928:32)
web |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
web |     at Module.require (internal/modules/cjs/loader.js:952:19)
web |     at require (internal/modules/cjs/helpers.js:88:18)
web |     at WEBPACK_OPTIONS (/Users/jeroen/Development/ydp/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
web |     at requireConfig (/Users/jeroen/Development/ydp/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
web |     at /Users/jeroen/Development/ydp/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
web |     at Array.forEach (<anonymous>)
web |     at module.exports (/Users/jeroen/Development/ydp/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
web |     at Object.<anonymous> (/Users/jeroen/Development/ydp/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40) {
web |   code: 'ERR_INVALID_ARG_TYPE'
web | }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm wondering if this is an error in my specific app, or that more people are seeing this after upgrading.

For good measure I also tested against a newly generated app, that one is working just fine.

rw info output:

```
System:
    OS: macOS 11.2.1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /var/folders/08/y52xs2c516xbcj0hkhpygzb00000gn/T/yarn--1614429115434-0.061391786596062925/node
    Yarn: 1.22.10 - /var/folders/08/y52xs2c516xbcj0hkhpygzb00000gn/T/yarn--1614429115434-0.061391786596062925/yarn
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    @redwoodjs/core: ^0.26.2 => 0.26.2

```

**Comment by jvanbaarsen** [comment]
Woops, got it solved. This was an issue because in the canary situation the upgrade guide didn't say anything about the `App.js` file. I wrongly assumed nothing had changed between the canary I tried and this release. (The rename `web/src/index.js` -> `web/src/App.js` step was not there)

After renaming `web/src/index.js` to `web/src/App.js` everything works as expected.
