### ISSUE TITLE
Invariant Violation: expected workspace package to exist for "@redwoodjs/core"

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/redwood#2009]
I'm getting `Invariant Violation: expected workspace package to exist for "@redwoodjs/core"` when trying to upgrade to `0.27.1` from a existing `0.27.0` project. Not sure if that is the correlation.

```
~/work/git/<obfuscated> dev !2 ❯ yarn redwood upgrade                                                                                                     1m 18s
yarn run v1.22.10
$ /home/johan/work/git/<obfuscated>/node_modules/.bin/redwood upgrade
  ✔ Checking installed packages
    ✔ Found @redwoodjs/auth
  ✔ Running upgrade command
    ✔ Running @redwoodjs package interactive upgrade CLI
  ✔ Refreshing the Prisma client
    ✔ ...
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
? Choose which packages to update. 
? Choose which packages to update. @redwoodjs/api@0.27.1, @redwoodjs/auth@0.27.1, @redwoodjs/cli@0.27.1, @redwoodjs/core@0.27.1, @redwoodjs/forms@0.27.1, @redwoodjs/router@0.27.1, @redwo
odjs/structure@0.27.1, @redwoodjs/testing@0.27.1, @redwoodjs/web@0.27.1
info Installing "dependencies"...
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "react@^16.8.3". Ignoring it.
warning Lockfile has incorrect entry for "react-dom@^16.8.3". Ignoring it.
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > web > less-loader@7.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > web > styled-components@5.2.1" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/cli > @redwoodjs/prerender@0.27.0" has unmet peer dependency "react@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/cli > @redwoodjs/prerender@0.27.0" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/testing > @testing-library/react@11.2.2" has unmet peer dependency "react@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/testing > @testing-library/react@11.2.2" has unmet peer dependency "react-dom@*".
warning "@redwoodjs/core > @storybook/react@5.3.21" has unmet peer dependency "react@*".
warning "@redwoodjs/core > @storybook/react@5.3.21" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > web > react-json-view > react-textarea-autosize@6.1.0" has incorrect peer dependency "react@>=0.14.0 <17.0.0".
warning "@redwoodjs/api > @redwoodjs/internal > @babel/plugin-transform-typescript@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @redwoodjs/cli > @redwoodjs/prerender@0.27.2-canary.4" has unmet peer dependency "react@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @redwoodjs/cli > @redwoodjs/prerender@0.27.2-canary.4" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @redwoodjs/testing > @redwoodjs/web@0.27.2-canary.4" has unmet peer dependency "react@^17.0.1".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core@5.3.21" has unmet peer dependency "react@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core@5.3.21" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > web > @redwoodjs/web > react-hot-toast > goober@2.0.33" has unmet peer dependency "csstype@^2.6.2".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/cli > @redwoodjs/internal > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.13.10" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/cli > @redwoodjs/internal > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/router@5.3.21" has unmet peer dependency "react@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/router@5.3.21" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/theming@5.3.21" has unmet peer dependency "react@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/theming@5.3.21" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/addons > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/theming > @emotion/core@10.1.1" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-6e312153-432f-437f-b159-8f02c5d5b13d > @redwoodjs/core > @storybook/react > @storybook/core > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
warning "@redwoodjs/api > apollo-server-lambda > apollo-server-core > graphql-upload@8.1.0" has incorrect peer dependency "graphql@0.13.1 - 14".
warning "@redwoodjs/api > graphql-tools > @graphql-tools/graphql-tag-pluck > @vue/compiler-sfc@3.0.5" has unmet peer dependency "vue@3.0.5".
warning "@redwoodjs/api > graphql-tools > @graphql-tools/links > apollo-upload-client@14.1.2" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
warning "@redwoodjs/core > @redwoodjs/testing > @redwoodjs/web@0.27.1" has unmet peer dependency "react@^17.0.1".
warning "@redwoodjs/core > @redwoodjs/cli > @redwoodjs/prerender@0.27.1" has unmet peer dependency "react@*".
warning "@redwoodjs/core > @redwoodjs/cli > @redwoodjs/prerender@0.27.1" has unmet peer dependency "react-dom@*".
Invariant Violation: expected workspace package to exist for "@redwoodjs/core"
    at invariant (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:2314:15)
    at _loop2 (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:94537:9)
    at PackageHoister.init (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:94596:19)
    at PackageLinker.getFlatHoistedTree (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:48744:20)
    at PackageLinker.<anonymous> (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:48755:27)
    at Generator.next (<anonymous>)
    at step (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/home/johan/.nvm/versions/node/v14.15.5/lib/node_modules/yarn/lib/cli.js:5301:28)
Done in 40.42s.
```

`package.json`
```json
{
  "private": true,
  "workspaces": {
    "packages": [
      "api",
      "web"
    ]
  },
  "devDependencies": {
    "@redwoodjs/core": "^0.27.2-canary.4",
    "pm2": "^4.5.0"
  },
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config"
  },
  "engines": {
    "node": ">=14",
    "yarn": ">=1.15"
  },
  "dependencies": {
    "@redwoodjs/cli": "^0.27.0",
    "@redwoodjs/structure": "^0.27.0",
    "@redwoodjs/testing": "^0.27.0"
  },
  "resolutions": {
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
}
```

`api/package.json`
```json
{
  "name": "api",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@azure/msal-node": "^1.0.0-beta.2",
    "@redwoodjs/api": "^0.27.0",
    "@redwoodjs/api-server": "https://rw-pr-redwoodjs-com.s3.amazonaws.com/1691/redwoodjs-api-server-0.27.0-7b6532d.tgz",
    "@redwoodjs/core": "^0.27.0",
    "node-fetch": "^2.6.1",
    "uuid": "^8.3.2",
    "yup": "^0.32.8"
  }
}
```

`web/package.json`
```json
{
  "name": "web",
  "version": "0.0.0",
  "private": true,
  "browserslist": {
    "development": [
      "last 1 version"
    ],
    "production": [
      "defaults",
      "not IE 11",
      "not IE_Mob 11"
    ]
  },
  "dependencies": {
    "@redwoodjs/auth": "^0.27.0",
    "@redwoodjs/forms": "^0.27.0",
    "@redwoodjs/router": "^0.27.0",
    "@redwoodjs/web": "^0.27.0",
    "antd": "^4.8.2",
    "change-case": "^4.1.1",
    "copy-to-clipboard": "^3.3.1",
    "less": "^3.12.2",
    "less-loader": "^7.1.0",
    "moment": "^2.29.1",
    "msal": "^1.4.4",
    "prop-types": "^15.7.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-json-view": "^1.19.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-leaves": "^2.0.0",
    "styled-components": "^5.2.1"
  }
}
```

**Comment by jeliasson** [comment]
@Tobbe Have you encountered above? I'm thinking if this related to #1994 or not. Thanks!
