### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by carlskii** [redwoodjs/redwood#2453]
Hi,

I'm exploring the use of RW for a project that will include a remote GraphQL service. However, I can't seem to get RW to perform a successful query. If a build a test using Apollo Client like this: 

```
import { ApolloClient, InMemoryCache, HttpLink } from '@apollo/client';
import { gql } from '@apollo/client';
import fetch from 'cross-fetch';

const client = new ApolloClient({
  link: new HttpLink({ uri: 'http://localhost:8055/graphql', fetch }),
  cache: new InMemoryCache()
});

client
  .query({
    query: gql`
    query MyQuery {
      partners{
    name
       about
       logo
       
     }
     }
    `
  })
  .then(result => console.log(result));
```

My query works perfectly: 

```
{
  data: { partners: [ [Object], [Object], [Object], [Object] ] },
  loading: false,
  networkStatus: 7
}
```

However if I configure my RW (App.js) app like this: 

```
import { FatalErrorBoundary } from '@redwoodjs/web'
import { RedwoodApolloProvider } from '@redwoodjs/web/apollo'
import { InMemoryCache } from '@apollo/client'


const cache = new InMemoryCache()

import FatalErrorPage from 'src/pages/FatalErrorPage'
import Routes from 'src/Routes'

import './scaffold.css'
import './index.css'

const App = () => (
  <FatalErrorBoundary page={FatalErrorPage}>
    <RedwoodApolloProvider graphQLClientConfig ={{ cache,
      // URL of your Hasura backend
      uri: 'http://localhost:8055/graphql', 
      cache: new InMemoryCache()
       }
    }}>
      <Routes />
    </RedwoodApolloProvider>
  </FatalErrorBoundary>
)

export default App
```

Then create a cell that makes a query: 

```
export const QUERY = gql`
query {
  partners{
name
   about
   logo
   
 }
 }
`

export const Loading = () => <div>Loading...</div>

export const Empty = () => <div>Empty</div>

export const Failure = ({ error }) => (
  <div style={{ color: 'red' }}>Error: {error.message}</div>
)

export const Success = ({ partners }) => {
  console.log(partners)
  return (
    <div>
      {partners.data.map((items) => (
        <li>{items.name} - {items.about}</li>
      ))}
    </div>
  )
}
```

I'm getting `Error: Response not successful: Received status code 400` 

My response looks like this: 

```
{
    "errors": [
        {
            "message": "Cannot query field \"partners\" on type \"Query\".",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Cannot query field \"partners\" on type \"Query\".",
                        "    at Object.Field (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
                        "    at Object.enter (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                        "    at visit (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/graphql/language/visitor.js:243:26)",
                        "    at Object.validate (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/apollo-server-core/src/requestPipeline.ts:514:14)",
                        "    at Object.<anonymous> (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/apollo-server-core/src/requestPipeline.ts:300:32)",
                        "    at Generator.next (<anonymous>)",
                        "    at fulfilled (/Users/cbourne/development/redwoodjs/my-redwood-app/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
                    ]
                }
            }
        }
    ]
}
```

If I follow the link in the console `http://localhost:8910/.redwood/functions/graphql` it loads the playground where the query works. Is there anything I'm missing here?

**Comment by peterp** [comment]
@carlskii Hey there, sorry for the delay in response here.

Is this GraphQL server a Redwood GraphQL server?

This can be configured in `redwood.toml` via the `apiProxyPath` configuration.

```toml
[web]
  port = 8910
  apiProxyPath = "http://localhost:8055"
```

Will result in `http://localhost:8055/graphql` being used for the GraphQL queries.

Please feel free to re-open this if it doesn't deal with your question properly.
