### ISSUE TITLE
Vercel deployments fail when using @redwoodjs/logger

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2736]
Now confirming this is a bug, because someone else has reported the same issue I saw.

Example error output at **runtime**:

```
2021-06-04T13:48:33.771Z	5f08b8f2-09ea-46c4-ad18-6abf9da208ab	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Cannot find module '/var/task/node_modules/@babel/runtime-corejs3/core-js/json/stringify.js'","code":"MODULE_NOT_FOUND","path":"/var/task/node_modules/@babel/runtime-corejs3/package.json","stack":["Error: Cannot find module '/var/task/node_modules/@babel/runtime-corejs3/core-js/json/stringify.js'","    at createEsmNotFoundErr (internal/modules/cjs/loader.js:912:15)","    at finalizeEsmResolution (internal/modules/cjs/loader.js:905:15)","    at resolveExports (internal/modules/cjs/loader.js:437:14)","    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)","    at Function.Module._load (internal/modules/cjs/loader.js:730:27)","    at Module.require (internal/modules/cjs/loader.js:957:19)","    at require (internal/modules/cjs/helpers.js:88:18)","    at Object.<anonymous> (/var/task/node_modules/@redwoodjs/api/dist/logger/index.js:15:41)","    at Module._compile (internal/modules/cjs/loader.js:1068:30)"]}
```

My suspicion is that Vercel's `nft` is removing `pino` from the deployed archive. The way I solved it on Tape is to not use logger for now, instead using console.logs (not recommended!).

cc @thedavidprice, @dthyresson 

--- 
Internal discussion started at: https://redwoodjs.slack.com/archives/C015DABLCK0/p1622803718001700

**Comment by dac09** [comment]
Vercel NFT issue confirmed. Issue here: https://github.com/vercel/nft/issues/220

**Comment by dac09** [comment]
Confirming fix in above issue has now solved the problem.
