### ISSUE TITLE
RW 0.33.0 rw-gen-watch crashes on Windows

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#2745]
Just installed RW 0.33.0 on Windows, and something seems to crash when I delete a file in my project (the teamToRatings service in this case)

```
gen | Error: EPERM: operation not permitted, unlink 'C:\Users\tobbe\dev\redwood\performance-management\.redwood\types\mirror\api\src\services\teamToRatings'
gen |     at Object.unlinkSync (node:fs:1252:3)
gen |     at FSWatcher.<anonymous> (C:\Users\tobbe\dev\redwood\performance-management\node_modules\@redwoodjs\internal\dist\generate\watch.js:74:19)
gen |     at FSWatcher.emit (node:events:376:20)
gen |     at C:\Users\tobbe\dev\redwood\performance-management\node_modules\chokidar\index.js:576:16
gen |     at Map.forEach (<anonymous>)
gen |     at Timeout._onTimeout (C:\Users\tobbe\dev\redwood\performance-management\node_modules\chokidar\index.js:574:30)
gen |     at listOnTimeout (node:internal/timers:556:17)
gen |     at processTimers (node:internal/timers:499:7) {
gen |   errno: -4048,
gen |   syscall: 'unlink',
gen |   code: 'EPERM',
gen |   path: 'C:\\Users\\tobbe\\dev\\redwood\\performance-management\\.redwood\\types\\mirror\\api\\src\\services\\teamToRatings'
gen | }
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
gen | yarn rw-gen-watch exited with code 1
```

**Comment by peterp** [comment]
I guess this has something to do with deleting a folder that isn't empty?

**Comment by Tobbe** [comment]
> I guess this has something to do with deleting a folder that isn't empty?

I did delete a whole folder (with files in it).

**Comment by thedavidprice** [comment]
@Tobbe do you know if this is still an issue? Assuming so.

**Comment by Tobbe** [comment]
Not sure. And I don't have my Windows machine to try it on anymore :/

**Comment by thedavidprice** [comment]
Closing this for now.
