### ISSUE TITLE
extendDefaultPlugins is not a function (While processing: "/node_modules/@redwoodjs/core/config/babel-preset.js

### ISSUE THREAD

**Issue by jmcmullen** [redwoodjs/redwood#2900]
I've updated to the latest version of Redwood and I am now seeing this error.

I've inspected the missing function from the `babel-preset.js` file and it appears to be related to `svgo`.
```
const { extendDefaultPlugins } = require('svgo')
```

I tried removing any SVG files from my code but I still see the following error in console:
```
 ✘ j@macbook  ~/Dev/fished   master ±  yarn rw dev
yarn run v1.22.10
$ /Users/j/Dev/fished/node_modules/.bin/rw dev
$ /Users/j/Dev/fished/node_modules/.bin/cross-env NODE_ENV=development webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
$ /Users/j/Dev/fished/node_modules/.bin/cross-env NODE_ENV=development yarn dev-server
$ /Users/j/Dev/fished/node_modules/.bin/rw-gen-watch
$ /Users/j/Dev/fished/node_modules/.bin/dev-server
gen | Generating TypeScript definitions and GraphQL schemas...
api | Running at 'http://localhost:8911'
api | Watching files in '/Users/j/Dev/fished/api/src/functions'
gen | 100 files generated
api | 
api | TypeError: [BABEL] /Users/j/Dev/fished/api/src/functions/graphql.js: extendDefaultPlugins is not a function (While processing: "/Users/j/Dev/fished/node_modules/@redwoodjs/core/config/babel-preset.js")
api | 
api | 
api | 1 module.exports
api |   /Users/j/Dev/fished/node_modules/@redwoodjs/core/config/babel-preset.js:171
api | 
api | 2 sync
api |   /Users/j/Dev/fished/node_modules/@babel/core/lib/gensync-utils/async.js:37
api | 
api | 3 sync
api |   /Users/j/Dev/fished/node_modules/gensync/index.js:182
api | 
api | 4 anonymous
api |   /Users/j/Dev/fished/node_modules/gensync/index.js:210
api | 
api | 5 anonymous
api |   /Users/j/Dev/fished/node_modules/@babel/core/lib/config/full.js:217
api | 
api | 6 anonymous
api |   /Users/j/Dev/fished/node_modules/@babel/core/lib/gensync-utils/async.js:24
api | 
api | 7 evaluateSync
api |   /Users/j/Dev/fished/node_modules/gensync/index.js:251
api | 
web | ℹ ｢wds｣: Project is running at http://localhost:8910/
web | ℹ ｢wds｣: webpack output is served from /
web | ℹ ｢wds｣: Content not from webpack is served from /Users/j/Dev/fished/web
web | ℹ ｢wds｣: 404s will fallback to /index.html
```

When I access the live server on 8910 I see the same error but from `App.js`
```
./src/App.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/j/Dev/fished/web/src/App.js: extendDefaultPlugins is not a function (While processing: "/Users/j/Dev/fished/node_modules/@redwoodjs/core/config/babel-preset.js")
    at module.exports (/Users/j/Dev/fished/node_modules/@redwoodjs/core/config/babel-preset.js:171:26)
    at async (/Users/j/Dev/fished/node_modules/@babel/core/lib/gensync-utils/async.js:43:33)
    at async (/Users/j/Dev/fished/node_modules/gensync/index.js:186:15)
    at /Users/j/Dev/fished/node_modules/gensync/index.js:216:13
    at Generator.next (<anonymous>)
    at /Users/j/Dev/fished/node_modules/@babel/core/lib/config/full.js:217:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/j/Dev/fished/node_modules/@babel/core/lib/gensync-utils/async.js:24:3)
    at Generator.next (<anonymous>)
    at step (/Users/j/Dev/fished/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/Users/j/Dev/fished/node_modules/gensync/index.js:291:5)
    at Function.errback (/Users/j/Dev/fished/node_modules/gensync/index.js:113:7)
    at errback (/Users/j/Dev/fished/node_modules/@babel/core/lib/gensync-utils/async.js:71:18)
    at async (/Users/j/Dev/fished/node_modules/gensync/index.js:188:31)
    at onFirstPause (/Users/j/Dev/fished/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
```

**Comment by peterp** [comment]
@jmcmullen Could you try deleting your `node_modules`, removing `yarn.lock` and re-installing everything?

**Comment by jmcmullen** [comment]
@peterp that's the first thing I tried, same problem. I've even created a new redwood project and copied my web and api src over and I still get the issue.

**Comment by peterp** [comment]
@dac09 can you help out with this?

**Comment by dac09** [comment]
Hey @jmcmullen - can you do me a favour and run `yarn why babel-plugin-inline-react-svg` and `yarn why svgo` and paste the output here please? 

My feeling is that the wrong version of the plugin/svgo is being installed.

**Comment by jmcmullen** [comment]
Thanks for taking a look @dac09 - here's the output.

```
 j@macbook  ~/Dev/fished   feature/rw-34-update  yarn why babel-plugin-inline-react-svg
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "babel-plugin-inline-react-svg"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "babel-plugin-inline-react-svg@2.0.1"
info Reasons this module exists
   - "_project_#@redwoodjs#core" depends on it
   - Hoisted from "_project_#@redwoodjs#core#babel-plugin-inline-react-svg"
info Disk size without dependencies: "1.64MB"
info Disk size with unique dependencies: "6.87MB"
info Disk size with transitive dependencies: "19.16MB"
info Number of shared dependencies: 52
✨  Done in 2.33s.
```

```
 j@macbook  ~/Dev/fished   feature/rw-34-update  yarn why svgo
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "svgo"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "svgo@1.3.2"
info Has been hoisted to "svgo"
info Reasons this module exists
   - "workspace-aggregator-db2d1a9f-aafb-4153-b7cd-4a67f9ba40fd" depends on it
   - Hoisted from "_project_#email#gulp-imagemin#imagemin-svgo#svgo"
   - Hoisted from "_project_#@redwoodjs#core#css-minimizer-webpack-plugin#cssnano#cssnano-preset-default#postcss-svgo#svgo"
info Disk size without dependencies: "3.07MB"
info Disk size with unique dependencies: "6.33MB"
info Disk size with transitive dependencies: "15.3MB"
info Number of shared dependencies: 47
=> Found "babel-plugin-inline-react-svg#svgo@2.3.0"
info This module exists because "_project_#@redwoodjs#core#babel-plugin-inline-react-svg" depends on it.
info Disk size without dependencies: "1.05MB"
info Disk size with unique dependencies: "3.53MB"
info Disk size with transitive dependencies: "5.66MB"
info Number of shared dependencies: 22
✨  Done in 1.33s.
```

**Comment by jmcmullen** [comment]
Ahh, I think you've spelt it out for me. I have another monorepo called emails that seems to be using an older version.

**Comment by dac09** [comment]
Yeah looks like its the older version of svgo thats the problem :) svgo needs to be 2.x+, annoying that its overriding the version redwood should be using.

Please let me know if upgrading solves it for you.

**Comment by jmcmullen** [comment]
Yep, that fixed it after another `node_modules` purge. Thanks so much for you help, I really appreciate it. Never knew about `yarn why`, definitely adding that one to my arsenal.

**Comment by dac09** [comment]
Wooooo! Nice one, glad I could help. `yarn why` is super useful yes
