### ISSUE TITLE
[Windows] Storybook doesn't work in RW 0.35

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3046]
Created a fresh project, and the first command I run is `yarn rw sb`. It gives me this error

![image](https://user-images.githubusercontent.com/30793/125861057-4ab8d108-5970-422c-8818-f7fae4558f79.png)

```
tobbe@XPS9550 MINGW64 ~/dev/redwood/sbtest
$ yarn rw info
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\sbtest\node_modules\.bin\rw info

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 16.3.0 - ~\AppData\Local\Temp\yarn--1626385041833-0.014567907293163707\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1626385041833-0.014567907293163707\yarn.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
  npmPackages:
    @redwoodjs/core: 0.35.0 => 0.35.0

Done in 6.52s.
```

Here's the full sb output:

```
tobbe@XPS9550 MINGW64 ~/dev/redwood/sbtest
$ yarn rw sb
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\sbtest\node_modules\.bin\rw sb
$ C:\Users\tobbe\dev\redwood\sbtest\node_modules\.bin\msw init C:\Users\tobbe\dev\redwood\sbtest\web\public --no-save
$ C:\Users\tobbe\dev\redwood\sbtest\node_modules\.bin\start-storybook --config-dir C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook --port 7910 --no-version-updates --static-dir C:\Users\tobbe\dev\redwood\sbtest\web\public
Initializing the Mock Service Worker at "C:\Users\tobbe\dev\redwood\sbtest\web\public"...

Service Worker successfully created!
C:\Users\tobbe\dev\redwood\sbtest\web\public\mockServiceWorker.js

Continue by creating a mocking definition module in your application:

https://mswjs.io/docs/getting-started/mocks

info @storybook/react v6.3.2
info
info => Loading presets
info => Serving static files from C:\Users\tobbe\dev\redwood\sbtest\web\public at /
info => Loading custom babel config as JS
info => Loading 1 config file in "C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook"
info => Loading 2 other files in "C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook"
info => Loading custom babel config as JS
WARN We found no files matching any of the following globs:
WARN
WARN C:\Users\tobbe\dev\redwood\sbtest\web\src/**/*.stories.{tsx,jsx,js}
WARN
WARN Maybe your glob was invalid?
WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
info => Using implicit CSS loaders
info => Using default Webpack4 setup
(node:25976) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 1/1 modules 0 active
info => Using cached manager
webpack built preview 4fa051ca6774dd1f051c in 16776ms
× ｢wdm｣: Hash: 4fa051ca6774dd1f051c
Version: webpack 4.46.0
Time: 16776ms
Built at: 2021-07-15 23:06:20
                    Asset      Size  Chunks                          Chunk Names
       0.iframe.bundle.js   5.5 KiB       0  [emitted]
   0.iframe.bundle.js.map  2.03 KiB       0  [emitted] [dev]
       1.iframe.bundle.js  5.04 KiB       1  [emitted]
   1.iframe.bundle.js.map  1.53 KiB       1  [emitted] [dev]
              iframe.html  4.35 KiB          [emitted]
    main.iframe.bundle.js  7.63 MiB    main  [emitted]        [big]  main
main.iframe.bundle.js.map  8.01 MiB    main  [emitted] [dev]         main
Entrypoint main [big] = main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js ../node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ../node_modules/@storybook/core-client/dist/esm/globals/globals.js ../node_modules/@redwoodjs/testing/config/storybook/storybook-init-framework-entry.js ../node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ../node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ../node_modules/@redwoodjs/testing/config/storybook/preview.js-generated-config-entry.js ../node_modules/@redwoodjs/testing/config/storybook/generated-stories-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 136 bytes {main} [built]
[../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js] 2.38 KiB {main} [built]
[../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js] 500 bytes {main} [built]
[../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/utils/errorEventHandlers.js] 2.91 KiB {main} [built]
[../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/utils/formatWebpackErrors.js] 3.34 KiB {main} [built]
[../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/utils/safeThis.js] 523 bytes {main} [built]
[../node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/index.js] 8.82 KiB {main} [built]
[../node_modules/@redwoodjs/testing/config/storybook/generated-stories-entry.js] 334 bytes {main} [built]
[../node_modules/@redwoodjs/testing/config/storybook/preview.js-generated-config-entry.js] 2.78 KiB {main} [built]
[../node_modules/@redwoodjs/testing/config/storybook/storybook-init-framework-entry.js] 26 bytes {main} [built]
[../node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js] 2.78 KiB {main} [built]
[../node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js] 2.78 KiB {main} [built]
[../node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {main} [built]
[../node_modules/@storybook/core-client/dist/esm/globals/polyfills.js] 97 bytes {main} [built]
[../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] 7.68 KiB {main} [built]
    + 1798 hidden modules

ERROR in ../node_modules/@redwoodjs/testing/config/storybook/generated-stories-entry.js
edwoodsbtestwebsrc' in 'C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook'
 @ ../node_modules/@redwoodjs/testing/config/storybook/generated-stories-entry.js 6:37-202
 @ multi ../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js ../node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ../node_modules/@storybook/core-client/dist/esm/globals/globals.js ../node_modules/@redwoodjs/testing/config/storybook/storybook-init-framework-entry.js ../node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ../node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ../node_modules/@redwoodjs/testing/config/storybook/preview.js-generated-config-entry.js ../node_modules/@redwoodjs/testing/config/storybook/generated-stories-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  5.81 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [../node_modules/html-webpack-plugin/lib/loader.js!../node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.98 KiB {HtmlWebpackPlugin_0} [built]
edwoodsbtestwebsrc' in 'C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook'
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\webpack\lib\ContextModuleFactory.js:143:23
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\neo-async\async.js:2830:7
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\neo-async\async.js:6877:13
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\webpack\lib\ContextModuleFactory.js:118:26
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\tobbe\dev\redwood\sbtest\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\tobbe\dev\redwood\sbtest\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\tobbe\dev\redwood\sbtest\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at C:\Users\tobbe\dev\redwood\sbtest\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\tobbe\dev\redwood\sbtest\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:43:1)
edwoodsbtestwebsrc' in 'C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook'
  Parsed request is a module
  using description file: C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\package.json (relative path: ./config/storybook)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\storybook\node_modules doesn't exist or is not a directory
      C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\config\node_modules doesn't exist or is not a directory
      C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\node_modules doesn't exist or is not a directory
      C:\Users\tobbe\dev\redwood\sbtest\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\tobbe\dev\node_modules doesn't exist or is not a directory
      C:\Users\tobbe\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\node_modules
        using description file: C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\tobbe\dev\redwood\sbtest\node_modules
        using description file: C:\Users\tobbe\dev\redwood\sbtest\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
edwoodsbtestwebsrc)cription file: C:\Users\tobbe\dev\redwood\sbtest\node_modules\@redwoodjs\testing\package.json (relative path: ./node_modules/C:Users obbedev
            as directory
edwoodsbtestwebsrc doesn't exist\redwood\sbtest\node_modules\@redwoodjs\testing\node_modules\C:Users    obbedev
edwoodsbtestwebsrc)cription file: C:\Users\tobbe\dev\redwood\sbtest\package.json (relative path: ./node_modules/C:Users obbedev
            as directory
edwoodsbtestwebsrc doesn't exist\redwood\sbtest\node_modules\C:Users    obbedev
      looking for modules in C:\Users\tobbe\dev\redwood\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        as directory
edwoodsbtestwebsrc doesn't existwood\node_modules\C:Users       obbedev

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Done in 33.94s.
```

A user on Discord first reported this, and they also provided this info

> Currently running node 14.17.0. I did some more troubleshooting, and if I replace the main.js in node_modules/@redwoodjs/testing/config with the main.js from 0.34.1, it seems to work. I noticed that the 0.35.0 main.js has some new functions for determining paths. I wonder if this is an issue with pathing and Windows?

https://discord.com/channels/679514959968993311/716252919875240007/864889866508435487

**Comment by Tobbe** [comment]
On Windows `getPaths().web.src` returns this for my example project: `'C:\\Users\\tobbe\\dev\\redwood\\sbtest\\web\\src'`

Making this change storybook works again (which is basically reverting one change made for the 0.35 release)

```diff
diff --git a/packages/testing/config/storybook/main.js b/packages/testing/config/storybook/main.js
index 8d6ac923..0b1ede55 100644
--- a/packages/testing/config/storybook/main.js
+++ b/packages/testing/config/storybook/main.js
@@ -11,7 +11,7 @@ const config = getConfig()
 const rwjsPaths = getPaths()

 const baseConfig = {
-  stories: [`${rwjsPaths.web.src}/**/*.stories.{tsx,jsx,js}`],
+  stories: ['../../../../web/src/**/*.stories.{tsx,jsx,js}'],

   addons: [config.web.a11y && '@storybook/addon-a11y'].filter(Boolean),
   webpackFinal: (sbConfig, { configType }) => {
```
