### ISSUE TITLE
How to avoid `useParams` must be used within a ParamsProvider in jest and storybook

### ISSUE THREAD

**Issue by toxsick** [redwoodjs/redwood#3109]
Hey guys,

quick question regarding `useParams`. Let's say I have a simple component like this:

```tsx
// ParamComponent.tsx

import { useParams } from '@redwoodjs/router';

const ParamComponent = () => {
  const params = useParams();
  return (
    <div>
      <h2>ParamComponent</h2>
      <p>{JSON.stringify(params)}</p>
    </div>
  );
};

export default ParamComponent;

```
Out of the box the jest test will fail with:

![ParamComponent tsx — ahab-rw 2021-07-23 16-16-31](https://user-images.githubusercontent.com/951466/126795213-90155c36-aa94-4a62-941e-3ae4f19008ee.png)

And also storybook will not be happy:

![ ParamComponent - Generated ⋅ Storybook 2021-07-23 16-18-58](https://user-images.githubusercontent.com/951466/126795607-7ee28eb1-b5b5-4d51-ae22-cea0a68f0b55.png)

Since there a data mocking concept  for other parts of redwood (e.g. Cells) I was wondering if there is a best practice to mock routing stuff or if I am missing something?!

I know I could mock this out with jest and do some webpack alias stuff in storybook to get around this, but since this is a pretty common thing that comes up in a lot of apps, I wanted to ask if you guys have an advice for this one.

Thanks and regards!

Here again the error for people who search:

```
    expect(received).not.toThrow()

    Error name:    "Error"
    Error message: "useParams must be used within a ParamsProvider"

          2 |
          3 | const ParamComponent = () => {
        > 4 |   const params = useParams();
            |                  ^
          5 |   return (
          6 |     <div>
          7 |       <h2>ParamComponent</h2>

          at useParams (../node_modules/@redwoodjs/router/dist/params.js:61:11)
          at ParamComponent (src/components/ParamComponent/ParamComponent.tsx:4:18)
          at renderWithHooks (../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
          at mountIndeterminateComponent (../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
          at beginWork (../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
          at HTMLUnknownElement.callCallback (../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
          at HTMLUnknownElement.callTheUserObjectsOperation (../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
          at innerInvokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
          at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
          at invokeGuardedCallback (../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
          at beginWork$1 (../node_modules/react-dom/cjs/react-dom.development.js:23964:7)
          at performUnitOfWork (../node_modules/react-dom/cjs/react-dom.development.js:22779:12)
          at workLoopSync (../node_modules/react-dom/cjs/react-dom.development.js:22707:5)
          at renderRootSync (../node_modules/react-dom/cjs/react-dom.development.js:22670:7)
          at performSyncWorkOnRoot (../node_modules/react-dom/cjs/react-dom.development.js:22293:18)
          at scheduleUpdateOnFiber (../node_modules/react-dom/cjs/react-dom.development.js:21881:7)
          at updateContainer (../node_modules/react-dom/cjs/react-dom.development.js:25482:3)
          at ../node_modules/react-dom/cjs/react-dom.development.js:26021:7
          at unbatchedUpdates (../node_modules/react-dom/cjs/react-dom.development.js:22431:12)
          at legacyRenderSubtreeIntoContainer (../node_modules/react-dom/cjs/react-dom.development.js:26020:5)
          at Object.render (../node_modules/react-dom/cjs/react-dom.development.js:26103:10)
          at ../node_modules/@testing-library/react/dist/pure.js:101:25
          at batchedUpdates$1 (../node_modules/react-dom/cjs/react-dom.development.js:22380:12)
          at act (../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
          at render (../node_modules/@testing-library/react/dist/pure.js:97:26)
          at customRender (../node_modules/@redwoodjs/testing/dist/customRender.js:20:29)
          at src/components/ParamComponent/ParamComponent.test.tsx:8:7
          at Object.<anonymous> (../node_modules/expect/build/toThrowMatchers.js:83:11)
          at Object.toThrow (../node_modules/expect/build/index.js:338:21)
          at Object.<anonymous> (src/components/ParamComponent/ParamComponent.test.tsx:9:12)

       7 |     expect(() => {
       8 |       render(<ParamComponent />)
    >  9 |     }).not.toThrow()
         |            ^
      10 |   })
      11 | })
```

**Comment by thedavidprice** [comment]
>  I was wondering if there is a best practice to mock routing stuff or if I am missing something

^^ @peterp do you have any thoughts/advice on this? My hunch is that we aren't supporting this via current Jest config/setup.

**Comment by Tobbe** [comment]
I wonder if it isn't just a matter of adding `<ParamsProvider>` to MockProviders.tsx

**Comment by thedavidprice** [comment]
Ah, very interesting @Tobbe 

Here's the file, which is used by both Storybook and Jest:
https://github.com/redwoodjs/redwood/blob/main/packages/testing/src/MockProviders.tsx
