### ISSUE TITLE
Please don't swallow graphql code gen errors

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#3351]
These lines swallow really helpful error messages
https://github.com/redwoodjs/redwood/blob/306c26ee558d4a03bb7e234828817763dbf5b4f6/packages/internal/src/generate/graphqlSchema.ts#L54-L62

Reading the comment in the snippet above it sounds like the ambition was to do more. I'd like to follow through on that.

For example, if I have this as part of one of my .sdl files

```sdl
type ProductCategory {
  code: String!
  name: String!
  isEmpty: Bool!
}
```

Currently all I get is this

```
Generating...

Failed to load schema
Failed to load schema

Error: Could not generate GraphQL schema
```

The full error (`e` in the code above) is this

```
ListrError: Something went wrong
    at C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\listr\index.js:102:18
    at async executeCodegen (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@graphql-codegen\cli\index.cjs.js:934:5)
    at async generate (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@graphql-codegen\cli\index.cjs.js:1231:25)
    at async generateGraphQLSchema (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@redwoodjs\internal\dist\generate\graphqlSchema.js:35:15)
    at async generate (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@redwoodjs\internal\dist\generate\generate.js:16:22)
    at async run (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@redwoodjs\internal\dist\generate\generate.js:28:17) {
  errors: [
    DetailedError: Failed to load schema
        at loadSchema (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@graphql-codegen\cli\index.cjs.js:413:15)
        at async C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@graphql-codegen\cli\index.cjs.js:842:55
        at async Task.task (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@graphql-codegen\cli\index.cjs.js:696:17) {
      details: '\n' +
        '        Failed to load schema from \n' +
        'scalar Date\n' +
        'scalar Time\n' +
        'scalar DateTime\n' +
        'scalar JSON\n' +
        'scalar JSONObject\n' +
        '\n' +
        'type Redwood {\n' +
        '  version: String\n' +
        '  currentUser: JSON\n' +
        '  prismaVersion: String\n' +
        '}\n' +
        '\n' +
        'type Query {\n' +
        '  redwood: Redwood\n' +
        '},**/*.sdl.{js,ts}:\n' +
        '\n' +
        '        Unknown type: "Bool".\n' +
        '        Error: Unknown type: "Bool".\n' +
        '    at getNamedType (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\utilities\\extendSchema.js:360:13)\n' +
        '    at getWrappedType (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\utilities\\extendSchema.js:375:12)\n' +
        '    at getWrappedType (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\utilities\\extendSchema.js:372:45)\n' +
        '    at buildFieldMap (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\utilities\\extendSchema.js:409:17)\n' +
        '    at fields (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\utilities\\extendSchema.js:561:22)\n' +
        '    at resolveThunk (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\type\\definition.js:480:40)\n' +
        '    at defineFieldMap (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\type\\definition.js:692:18)\n' +
        '    at GraphQLObjectType.getFields (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\type\\definition.js:633:27)\n' +
        '    at collectReferencedTypes (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\type\\schema.js:366:81)\n' +
        '    at new GraphQLSchema (C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\node_modules\\graphql\\type\\schema.js:148:9)\n' +
        '    \n' +
        '        GraphQL Code Generator supports:\n' +
        '          - ES Modules and CommonJS exports (export as default or named export "schema")\n' +
        '          - Introspection JSON File\n' +
        '          - URL of GraphQL endpoint\n' +
        '          - Multiple files with type definitions (glob expression)\n' +
        '          - String in config file\n' +
        '    \n' +
        '        Try to use one of above options and run codegen again.\n' +
        '    \n' +
        '      ',
      source: 'C:\\Users\\tobbe\\dev\\redwood\\acm-store-rw\\.redwood\\schema.graphql',
      context: [Object: null prototype] {}
    }
  ],
  context: [Object: null prototype] {}
}
```

In the middle of all that I can see that `Bool` isn't a valid type. I'd like to try to filter out some of the noise.  One way to do that is to only print the error details

```
for (const error of e.errors) {
  console.error('Error details:');
  console.error(error.details)
}
```

Leaving us with this output

```
Error details:

        Failed to load schema from
scalar Date
scalar Time
scalar DateTime
scalar JSON
scalar JSONObject

type Redwood {
  version: String
  currentUser: JSON
  prismaVersion: String
}

type Query {
  redwood: Redwood
},**/*.sdl.{js,ts}:

        Unknown type: "Bool".
        Error: Unknown type: "Bool".
    at getNamedType (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\utilities\extendSchema.js:360:13)
    at getWrappedType (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\utilities\extendSchema.js:375:12)
    at getWrappedType (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\utilities\extendSchema.js:372:45)
    at buildFieldMap (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\utilities\extendSchema.js:409:17)
    at fields (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\utilities\extendSchema.js:561:22)
    at resolveThunk (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\type\definition.js:480:40)
    at defineFieldMap (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\type\definition.js:692:18)
    at GraphQLObjectType.getFields (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\type\definition.js:633:27)
    at collectReferencedTypes (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\type\schema.js:366:81)
    at new GraphQLSchema (C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\graphql\type\schema.js:148:9)

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
```

Depending on how much we can/want to trust that the output stays the same we can filter further, by for example removing the useless stack trace, etc.

**Comment by thedavidprice** [comment]
Looping in @peterp and @dac09

**Comment by dac09** [comment]
Nice, and thanks for the rrepro and analysis @Tobbe. I'll take care of this, because I meant to do some refactoring around better errors for the generator anyway for #2964
