### ISSUE TITLE
When spinning up a new project on windows 10 - things are not working

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/redwood#3521]
I was looking into another issue I was having.  As part of that I thought I'd spin up a fresh project to reproduce the error.

So I went to the learn.redwoodjs.com and copied the lines to spin up a project.

```sh
 yarn create redwood-app ./redwoodblog-test-sb
```

<details>
<summary>It ran with no issues (click to see output).</summary>

```sh
$ yarn create redwood-app ./redwoodblog-test-sb
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "cameronjs > cameronjs-html-webpack-plugin@0.5.1" has unmet peer dependency "webpack@^4.42.0".
warning "create-redwood-app > @redwoodjs/internal > @babel/plugin-transform-typescript@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > @babel/register@7.15.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.1.4" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-polyfill-corejs3@0.2.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.15.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "create-redwood-app > @redwoodjs/internal > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-polyfill-corejs3 > @babel/helper-define-polyfill-provider@0.2.3" has unmet peer dependency "@babel/core@^7.4.0-0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-polyfill-corejs3 > @babel/helper-define-polyfill-provider > @babel/helper-compilation-targets@7.15.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...

success Installed "create-redwood-app@0.37.2" with binaries:
      - create-redwood-app
  √ Creating Redwood app
    √ Checking node and yarn compatibility
    √ Creating directory 'C:\Users\jaceb\git\redwoodblog-test-sb'
  √ Installing packages
    √ Running 'yarn install'... (This could take a while)
  √ Convert TypeScript files to JavaScript
  √ Generating types

Thanks for trying out Redwood!

 ⚡️ Get up and running fast with this Quick Start guide: https://redwoodjs.com/docs/quick-start

Join the Community

 ❖ Join our Forums: https://community.redwoodjs.com
 ❖ Join our Chat: https://discord.gg/redwoodjs

Get some help

 ❖ Get started with the Tutorial: https://redwoodjs.com/tutorial
 ❖ Read the Documentation: https://redwoodjs.com/docs

Stay updated

 ❖ Sign up for our Newsletter: https://www.redwoodjs.com/newsletter
 ❖ Follow us on Twitter: https://twitter.com/redwoodjs

Become a Contributor ❤

 ❖ Learn how to get started: https://redwoodjs.com/docs/contributing
 ❖ Find a Good First Issue: https://redwoodjs.com/good-first-issue

Fire it up! �

 > cd ./redwoodblog-test-sb
 > yarn rw dev

Done in 100.50s.
```

</details>

Then I thought okay I'll just run it.

```sh
yarn rw dev
```

<details>
<summary>
Which gave me an error of "Unable to load '@webpack-cli/serve' command" (click for full output)
</summary>

```sh
$ yarn rw dev
yarn run v1.22.5
$ C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\.bin\rw dev
  √ Generating the Prisma client...
$ C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\.bin\cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --config C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\@redwoodjs\core\config\webpack.development.js
$ C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\.bin\cross-env NODE_ENV=development NODE_OPTIONS=--enable-source-maps yarn nodemon --watch C:\Users\jaceb\git\redwoodblog-test-sb\redwood.toml --exec "yarn rw-api-server-watch"
$ C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\.bin\rw-gen-watch
web | [webpack-cli] Unable to load '@webpack-cli/serve' command
web | [webpack-cli] TypeError: options.forEach is not a function
web |     at WebpackCLI.makeCommand (C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\webpack-cli\lib\webpack-cli.js:173:21)
web |     at ServeCommand.apply (C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\@webpack-cli\serve\lib\index.js:41:19wwweb |     at loadCommandByName (C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\webpack-cli\lib\webpack-cli.js:907:35)  web weweb weweweweb |     at async Promise.all (index 0)
web |     at async WebpackCLI.run (C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\webpack-cli\lib\webpack-cli.js:1521:9)
web |     at async runCLI (C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\webpack-cli\lib\bootstrap.js:11:9)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web | cd "C:\Users\jaceb\git\redwoodblog-test-sb\web" && yarn cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --conf
ig "C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\@redwoodjs\core\config\webpack.development.js"  exited with code 2
$ C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\.bin\nodemon --watch C:\Users\jaceb\git\redwoodblog-test-sb\redwood.toml --exec "yar
n rw-api-server-watch"
api | [nodemon] 2.0.12
api | [nodemon] to restart at any time, enter `rs`
api | [nodemon] watching path(s): redwood.toml
api | [nodemon] watching extensions: js,mjs,json
api | [nodemon] starting `yarn rw-api-server-watch`
$ C:\Users\jaceb\git\redwoodblog-test-sb\node_modules\.bin\rw-api-server-watch
gen | Generating TypeScript definitions and GraphQL schemas...
gen | 14 files generated
api | Building... Took 324 ms
api | Starting API Server... Took 4 ms
api | Listening on http://localhost:8911/
api | Importing Server Functions...
api | /graphql 6344 ms
api | ... Imported in 6344 ms
```

</details>

**Comment by thedavidprice** [comment]
Gah, Webpack! This feels like a bug in Webpack (I hope).

Could you try `yarn add -W -D webpack webpack-dev-server`? This will upgrade both Webpack and Webpack-dev-server packages to the latest in your root directory. If that resolves things, let me know and I'll get out a patch ASAP.

**Comment by thedavidprice** [comment]
Weird. What's with those `\\` in your paths? That can't be good. What Windows terminal + shell combo are you using?

Maybe just try to add the dependencies manually:
```
// ./package.json
...
  "devDependencies": {
    "@redwoodjs/core": "^0.37.2",
    "webpack": "^5.57.1",
    "webpack-dev-server": "^4.3.1"
  },
...
```

And then `yarn install`

**Comment by thedavidprice** [comment]
Confirming this is a bug on both Windows and Mac. Coming from Webpack specifically. DANG IT

moving this conversation over here --> https://github.com/redwoodjs/redwood/issues/3522
