### ISSUE TITLE
fresh install bug - Unable to load '@webpack-cli/serve' command

### ISSUE THREAD

**Issue by shansmith01** [redwoodjs/redwood#3522]
Hi There, 

I have just done a fresh install of 0.37.2 and when I try running yarn rw dev I get errors in my terminal and can not get a page to open.

```
% yarn rw dev 
yarn run v1.22.15
$ /Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/.bin/rw dev
$ /Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/.bin/cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --config /Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/@redwoodjs/core/config/webpack.development.js
$ /Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/.bin/cross-env NODE_ENV=development NODE_OPTIONS=--enable-source-maps yarn nodemon --watch /Users/shannonsmith/Documents/GitHub/bedhopper/redwood.toml --exec 'yarn rw-api-server-watch'
$ /Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/.bin/rw-gen-watch
web | [webpack-cli] Unable to load '@webpack-cli/serve' command
web | [webpack-cli] TypeError: options.forEach is not a function
web |     at WebpackCLI.makeCommand (/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/webpack-cli/lib/webpack-cli.js:173:21)
web |     at ServeCommand.apply (/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/@webpack-cli/serve/lib/index.js:41:19)
web |     at loadCommandByName (/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/webpack-cli/lib/webpack-cli.js:907:35)
web |     at async Command.<anonymous> (/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/webpack-cli/lib/webpack-cli.js:1483:17)
web |     at async Promise.all (index 0)
web |     at async WebpackCLI.run (/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/webpack-cli/lib/webpack-cli.js:1521:9)
web |     at async runCLI (/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/webpack-cli/lib/bootstrap.js:11:9)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web | cd "/Users/shannonsmith/Documents/GitHub/bedhopper/web" && yarn cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --config "/Users/shannonsmith/Documents/GitHub/bedhopper/node_modules/@redwoodjs/core/config/webpack.development.js"  exited with code 2

...... API seems to generate okay.

```

System details below.

```
  System:
    OS: macOS 11.5.2
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /var/folders/t3/gmgw2_c966sdwbh8whw_0cx00000gn/T/yarn--1633569109564-0.34389710180327326/node
    Yarn: 1.22.15 - /var/folders/t3/gmgw2_c966sdwbh8whw_0cx00000gn/T/yarn--1633569109564-0.34389710180327326/yarn
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 94.0.4606.71
    Safari: 14.1.2
  npmPackages:
    @redwoodjs/core: 0.37.2 => 0.37.2 
```

Can I get a hand please?

**Comment by thedavidprice** [comment]
Related —> we started seeing something related to dev server throw in the CI today without any correlation with code modifications. @jtoar and I resolved it by upgrading Webpack, although that doesn't seem to fix this problem.

**Current theory:**
Webpack [released a new version yesterday](https://github.com/webpack/webpack/releases). Although we pin the version in our Redwood package, it's also included via Storybook. It seems like fresh installs are using the latest which is throwing.

The root issue seems to be a dependency of Webpack, which is `tapable`. Looking there, too.

**Comment by thedavidprice** [comment]
## Found It
It's a dependency of a dependency, which released a new version today. Fresh projects would have grabbed the latest version, which has a bug. Project upgrading would have a yarn.lock with the previous version, which works.

The guilty package is here --> https://www.npmjs.com/package/@webpack-cli/serve

## Workaround
For now, the workaround is to _force_ your project to use v1.5.2. It's a two-step process:
1. install in root package.json
2. set a resolution

Your `./package.json` will need to look something like this:
```diff
{
  "private": true,
  "workspaces": {
    "packages": [
      "api",
      "web"
    ]
  },
  "devDependencies": {
    "@redwoodjs/core": "0.37.2",
+    "@webpack-cli/serve": "1.5.2"
  },
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config",
    "root": true
  },
  "engines": {
    "node": "14.x",
    "yarn": "1.x"
  },
  "resolutions": {
+    "@webpack-cli/serve": "1.5.2"
  }
}
```

## Next Steps
We'll get a patch v0.37.2 out asap. And we'll report the bug to Webpack folks on their repo.

**Comment by shansmith01** [comment]
Works thanks @thedavidprice

**Comment by thedavidprice** [comment]
v0.37.3 will be out within the hour

Thank you to you and @jacebenson for reporting this.

The dependency of my dependency is my enemy...

...or so the saying goes.

**Comment by thedavidprice** [comment]
We've released https://github.com/redwoodjs/redwood/releases/tag/v0.37.3

**Comment by Isaac-Tait** [comment]
> So you cloned https://github.com/redwoodjs/example-blog?

Yes that is correct.

Thank you for the workaround - I will implement it 👍🏼 😄 Fingers crossed the webpack folks get a patch release ASAP 🤞🏼

**Comment by stephenhandley** [comment]
Running into this after upgrading to redwood 0.38.0

**Comment by jtoar** [comment]
Hey @stephenhandley, did you happen to have the resolution at `1.5.2` when you upgraded like Kyle [here](https://community.redwoodjs.com/t/v0-38-upgrade-guide/2501/3)? If so, you can remove that block entirely as it was just a patch when things broke unexpecedly in v37 and shouldn't be needed at all for v38.

**Comment by stephenhandley** [comment]
Ah, got it thanks @jtoar
