### ISSUE TITLE
GitPod build `rw dev` fails via Wepack css error related to PostCSS and Autoprefixer

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#4144]
## Update
The workaround in place is sufficient for now. I did check to see if this was resolved in CI via #4210. Locally things work fine, however, GitPod build and `yarn rw dev` is still broken. See [this comment](https://github.com/redwoodjs/redwood/pull/4210#issuecomment-1016779821).

I do not have reason to believe there's something fundamentally broken with the current canary version and projects using Tailwind. Confirmed by running separate test with new projects @canary and then running setup ui tailwindcss = success.

Leaving this Issue open to monitor. Goal is to undo workaround.

**ToDo:**
- [ ] Revert https://github.com/redwoodjs/redwood/pull/4143 (must confirm GitPod build is working)

## Background
Projects at v0.41 or greater break with tailwindcss. The issue seems to be specific to PostCSS and autoprefixer. @virtuoushub diagnosed the issue and workaround [over here](https://github.com/redwoodjs/redwood/pull/3515#issuecomment-1000974638) in what was thought to be a Storybook issue, but more likely seems Webpack related.

For CI, I've added a workaround PR here for the short-term:
- https://github.com/redwoodjs/redwood/pull/4143

## Reproduction
- ~create a project at the latest v0.41~

Update: this is more complicated than just creating a fresh project. If I setup tailwind into an existing v0.41 project, tailwind fails. If I do the same on a fresh project, it seems to work. If I run `npx yarn-deduplicate` on the existing project, it works. Definitely a sub-dependency problem.

### Broken example on v0.41
https://github.com/thedavidprice/redwood-tutorial-test/tree/v0.41.0-tailwind-broken
- clone
- yarn
- yarn rw dev

### Working example on v0.41
Using the branch above, I ran `npx yarn-deduplicate`:
https://github.com/thedavidprice/redwood-tutorial-test/tree/v0.41.0-tailwind-working
- clone (or run `npx yarn-deduplicate` on branch above; don't forget to git clean)
- yarn 
- yarn rw dev

Following error results:
```zsh
web | [webpack-cli] Failed to load '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.development.js' config
web | [webpack-cli] Error: Cannot find module 'postcss-loader'
web | Require stack:
web | - /Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.common.js
web | - /Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.development.js
web | - /Users/price/Repos/tdp-redwood-tutorial-test/node_modules/webpack-cli/lib/webpack-cli.js
web | - /Users/price/Repos/tdp-redwood-tutorial-test/node_modules/webpack-cli/lib/bootstrap.js
web | - /Users/price/Repos/tdp-redwood-tutorial-test/node_modules/webpack-cli/bin/cli.js
web | - /Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@storybook/builder-webpack4/node_modules/webpack/bin/webpack.js
web |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
web |     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
web |     at getStyleLoaders (/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.common.js:76:25)
web |     at module.exports (/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.common.js:305:16)
web |     at Object.<anonymous> (/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.development.js:48:26)
web |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
web |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
web |     at Module.load (node:internal/modules/cjs/loader:981:32)
web |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
web |     at Module.require (node:internal/modules/cjs/loader:1005:19) {
web |   code: 'MODULE_NOT_FOUND',
web |   requireStack: [
web |     '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.common.js',
web |     '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@redwoodjs/core/config/webpack.development.js',
web |     '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/webpack-cli/lib/webpack-cli.js',
web |     '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/webpack-cli/lib/bootstrap.js',
web |     '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/webpack-cli/bin/cli.js',
web |     '/Users/price/Repos/tdp-redwood-tutorial-test/node_modules/@storybook/builder-webpack4/node_modules/webpack/bin/webpack.js'
web |   ]
web | }
error Command failed with exit code 2.
```

**Comment by thedavidprice** [comment]
Based on what I'm seeing, it's most likely an underlying sub-dependency, which could have been released around the same time we upgraded to Storybook 6.4. So, yes, something about how packages are being resolved but just as likely to be caused by semver allowing things to get out of sync or using a package with a regression.

To demonstrate, I have a replication that's using the most recent canary + tailwind and it's working successfully. Here's what I did
- started with the broken 0.41 branch https://github.com/thedavidprice/redwood-tutorial-test/tree/v0.41.0-tailwind-broken
- upgraded via `yarn rw upgrade -t canary` (note: this runs the yarn deduplicate step)
- yarn rw dev

Success. Which is rather maddening.

## Working Reproduction using latest canary
New branch here:
- https://github.com/thedavidprice/redwood-tutorial-test/tree/0.41.1-canary.122-tailwind-working

## Possible Workaround
If projects are experiencing this issue, please try:
- `npx yarn-deduplicate` 

And then reply with the outcome.

**Comment by thedavidprice** [comment]
@jtoar I'm triaging this and putting it on my plate. It's currently something I'd like to resolve for v1 but it's not critical — so watching.

**Comment by thedavidprice** [comment]
This issue has resolved itself. And I'm now reverting the change to the build:test-project via PR:
- #4576

**Comment by thedavidprice** [comment]
## Update and (new) Workaround
This issue showed up again on March 1st. However, this time it was due to packages not being hoisted from web. See #4623 

The workaround is to remove Tailwindcss related devDeps from web/package.json into ./package.json
