### ISSUE TITLE
Upgrade to 0.42 breaks layout (with tailwindcss)

### ISSUE THREAD

**Issue by tilmann** [redwoodjs/redwood#4237]
I just upgrade a project from redwoodjs **0.41.0 to 0.42.0**. The upgrade breaks the layout:
The layout is supposed to look like this:
<img width="400" alt="2022 01 21 - 14-01-08 - LoggingIn | marla" src="https://user-images.githubusercontent.com/7314399/150543512-46e85c23-4774-4f81-87b7-bf262318203c.png">
Deployment: [https://marla-nunipyntw-tilmann.vercel.app/logging-in](https://marla-nunipyntw-tilmann.vercel.app/logging-in)

but after the upgrade it looks like this:
<img width="400" alt="2022 01 21 - 14-01-20 - LoggingIn | marla" src="https://user-images.githubusercontent.com/7314399/150543553-b173230b-d97d-44a3-855a-db11286fe528.png">
Deployment: [https://marla-oh8935c3y-tilmann.vercel.app/logging-in](https://marla-oh8935c3y-tilmann.vercel.app/logging-in)

Only difference was the upgrade. Going back to 0.41.0 solves the problem. 
Any ideas what could be the reason?

_My `package.json` in /web_
```
{
  "name": "web",
  "version": "0.0.0",
  "private": true,
  "browserslist": {
    "development": [
      "last 1 version"
    ],
    "production": [
      "defaults",
      "not IE 11",
      "not IE_Mob 11"
    ]
  },
  "dependencies": {
    "@headlessui/react": "^1.4.1",
    "@heroicons/react": "^1.0.4",
    "@redwoodjs/auth": "^0.42.0",
    "@redwoodjs/forms": "^0.42.0",
    "@redwoodjs/router": "^0.42.0",
    "@redwoodjs/web": "^0.42.0",
    "@supabase/supabase-js": "^1.22.6",
    "@tailwindcss/aspect-ratio": "^0.3.0",
    "@tailwindcss/forms": "^0.4.0-alpha.2",
    "@tailwindcss/typography": "^0.5.0-alpha.3",
    "buffer": "^6.0.3",
    "lodash": "^4.17.21",
    "luxon": "^2.0.2",
    "markdown-to-jsx": "^7.1.3",
    "pino": "^7.5.1",
    "pino-logflare": "^0.3.12",
    "pixi.js": "^6.2.0",
    "process": "^0.11.10",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-colorful": "^5.5.0",
    "react-dom": "17.0.2",
    "react-select": "^5.1.0",
    "stream-browserify": "^3.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.3.4",
    "faker": "^5.5.3",
    "postcss": "^8.3.6",
    "postcss-loader": "^6.1.1",
    "tailwindcss": "^3.0.0-alpha.2"
  }
}
```

**Comment by thedavidprice** [comment]
@jtoar @simoncrypta I have a quick idea about this — Webpack is in charge of how css is loaded (compressed/ordered), and there were updates to css-minify (I believe). So perhaps something happened that actually resolved this old issue #549 and/or had some kind of similar effect.

@tilmann could you inspect things like import order for you app and see if it's related?

**Comment by tilmann** [comment]
Happy to help but I need some guidance. How can I inspect the import order? What other information might be helpful?

**Comment by thedavidprice** [comment]
Any chance the repo is public for us to inspect?

By import order, I'm referring to the order of css imports in your web/src/App.(tsx|js) file, e.g scaffold.css and index.css here:
<img width="299" alt="Screen Shot 2022-01-21 at 11 04 31 AM" src="https://user-images.githubusercontent.com/2951/150585582-714d17d5-2de8-4dfd-9fbf-d71c25202cf6.png">

**Comment by tilmann** [comment]
The repo is not public, but I found something that might help:

I inspected the source code for the links provided above in the chrome dev tools and I see a **new `<div class="bg-white">` inside the redwood root element**. I (to the best of my knowledge) did not add it and cannot find in my codebase. 
Any ideas where this comes from?
![2022 01 23 - 09-01-15 - LoggingIn | marla](https://user-images.githubusercontent.com/7314399/150672356-847b6310-9149-41e7-bbbe-06e8f75e97b7.png)

**Re: Imports**
I use the standard redwood-tailwind integration. And my only css imports are in `App.tsx`: 
```
import './scaffold.css'
import './index.css'
```

**Comment by simoncrypta** [comment]
@tilmann I can confirm that the HTML between your two deployment is not the same, the `<div class="bg-white">` is not the only difference. 
I copy past the HTML of your two URL to see it, you can look at this link : 
https://www.diffchecker.com/8lMMvU4t

Can you confirm is not a change in one of your template when you had made the upgrade ?

**Comment by thedavidprice** [comment]
I'm fairly confident "bg-white" would be coming from Tailwind. Looking at your OP @tilmann you're still running on the Tailwind v3-alpha. You might need to try upgrading Tailwind and the related dependencies. Here's what the versions would be for a fresh install:
```
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.5",
    "postcss-loader": "^6.2.1",
    "tailwindcss": "^3.0.16"
  }
```

Could you update the versions in your app, run `yarn install`, and try again on both v0.41 and v0.42?

**Comment by tilmann** [comment]
Thanks for the answers. 

@simoncrypta I am pretty confident that the change is not coming from a template but from upgrading to 0.42.x.

Here are three deployments I did one after the other to make sure there are no side effects apart from the upgrade. 

**1. Redwood 0.41.0 | This is the build after the commit @thedavidprice recommended:**
<img width="600" alt="2022 01 25 - 10-01-02 - 📌 upgrade tailwind related dependencies · tilmannmarla@a9661d4" src="https://user-images.githubusercontent.com/7314399/150957686-b6e8003b-ee04-4051-9767-316478df4576.png">

✅ [https://marla-r9u3pz3wa-tilmann.vercel.app/logging-in](https://marla-r9u3pz3wa-tilmann.vercel.app/logging-in)

**2. Redwood 0.41.0 | Rebuild on Vercel without using the build cache that already existed making sure everything is rebuild.**
✅ [https://marla-czgalrkl1-tilmann.vercel.app/logging-in](https://marla-czgalrkl1-tilmann.vercel.app/logging-in)

**3. Redwood 0.42.1 | Build after the following commit (Vercel does not use build cache if you upgrade redwood)** 
<img width="600" alt="2022 01 25 - 10-01-36 - ⬆️ upgrade redwood to 0 42 1 · tilmannmarla@faeb353" src="https://user-images.githubusercontent.com/7314399/150958524-9c24bf27-4c4d-4b77-bffc-0691c3bc42b9.png">

❌ [https://marla-kp5wm1fcz-tilmann.vercel.app/logging-in](https://marla-kp5wm1fcz-tilmann.vercel.app/logging-in)

@thedavidprice @simoncrypta I will add you to the repo so you can have a look at the code.

**Comment by tilmann** [comment]
I am happy to dig in as well to find the reason. 
Any ideas what to check to get to the source of the bug?

**Comment by thedavidprice** [comment]
@tilmann @simoncrypta I did some quick digging and found a few things to help us diagnose.

## Problem
The breaking layout is coming from the CSS class change on this div:

#### Comparison of v0.41 layout and v0.42 layout (broken)
Look at the Elements page source html explorer
<img width="1656" alt="Screen Shot 2022-01-25 at 3 17 54 PM" src="https://user-images.githubusercontent.com/2951/151076771-5bb69956-737f-4eda-a704-4e86f125b73e.png">

#### Applying the div class from 0.41 to 0.42
And it's fixed if I copy over the classes
<img width="1650" alt="Screen Shot 2022-01-25 at 3 19 19 PM" src="https://user-images.githubusercontent.com/2951/151076944-3acb6477-bfc7-4264-af19-0e2a4af6b60f.png">

### Affected Component
I belive this is the line of code for the `<div>` I inspected above:
https://github.com/tilmann/marla/blob/3074f18f1f96aced441a1bab938ed6c2f91f7bd0/web/src/layouts/AppLayout/AppLayout.tsx#L15

And there's absolutely nothing that would overwrite that div class in the css:
https://github.com/tilmann/marla/blob/main/web/src/index.css

### Hypothesis
This is a compile error either with Tailwind or Webpack (or combination of both).

I'd look into these plugins by removing them, looking on GitHub for reported Issues, and/or trying newer versions:
- https://github.com/tilmann/marla/blob/main/web/config/tailwind.config.js

^^ I don't know Tailwind plugins well. Are those related to the `utilities` import here?
- https://github.com/tilmann/marla/blob/main/web/src/index.css

And I'd look into the Webpack plugins `css-minimizer-webpack-plugin` and `mini-css-extract-plugin`, which I believe was upgraded:
- downgrade version by installing in project
- can we override and turn off?
- NOTE: there's a patch release for `mini-css-extract-plugin`... maybe it's that simple?
- etc.

Note: other Webpack plugin is `css-loader` but I don't think that would be the cause.

---

Wish I had more of an answer, but hopefully this helps get us to the next step.

**Comment by thedavidprice** [comment]
PS: I didn't take a look at `@media`, which might also be factoring in here

**Comment by tilmann** [comment]
Thanks for the ideas.

1. I removed all tailwind plugins: [commit](https://github.com/tilmann/marla/commit/19db9d98e797aacbe201f7d2174b5f5f2a12b932). It was not the problem: [Build](https://marla-4986t4jl3-tilmann.vercel.app/logging-in)

2. The `utilities` import in tailwind is standard: 
![2022 01 26 - 12-01-41 - Installation Tailwind CLI - Tailwind CSS](https://user-images.githubusercontent.com/7314399/151161650-29e722f8-2bda-44e6-acd4-32891c805d87.png)

3. The patch release for `mini-css-extract-plugin` addresses a problem with types. I assume that will not be our solution.

4. I tried to look into the webpack plugins and tried to activate them in my dev environment but failed to figure out how. Is there a easy way to do that?

**Comment by tilmann** [comment]
I am still struggling to reproduce the bug in my local environment. If I use `yarn rw build web` and use `prerender` the sites look just fine. 
Can anyone point me to a way how to pin the versions of the webpack plugins, run the production build in my local environment, serve it and see if the problem still exists?

**Comment by thedavidprice** [comment]
FYI new Tailwindcss patch that's work trying out:
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.18

**Comment by thedavidprice** [comment]
@tilmann I tried to take the project for a spin locally, but saw you were using Supabase — just didn't have time to get everything going as it fails without DBs set up. Anyway, I still have a few ideas for you.

**Package.json Dependencies**
The Redwood packages are installed at `^0.41.0`, which means semver _will_ allow more recent versions of Redwood to be installed in node_modules. This could mess up testing/reproduction especially if you're gone back and forth a bit.
- recommend you pin version by changing `^0.41.0` to `0.41.0` for all Redwood packages across all three package.json

You have Prisma client installed in api/package.json:
- recommend you remove `"@prisma/client": "^3.8.0",`

**Reproducing Deployment**
If you run `yarn rw dev`, regardless of building, this will use the Webpack dev server and the development settings for Webpack to serve Web.

Running `yarn rw build` or just `yarn rw build web`, will use the production Webpack config here:
- https://github.com/redwoodjs/redwood/blob/2f53b043055495a4041ce0315e1f7575fc338869/packages/core/config/webpack.common.js

The assets are built to web/dist, which is what is served at production. So this is the first step, but then you need to use a "production-style" server.

To reproduce this locally, use the RW Server, which is run via `yarn rw serve`. Then open localhost:8910

**Comment by tilmann** [comment]
Thanks @thedavidprice. 

I pinned the redwood version to `0.43.0`, removed `@prisma/client` and upgrade. The [build](https://marla-inr1kb2zq-tilmann.vercel.app/logging-in) for branch [rw-upgrade-bug](https://github.com/tilmann/marla/tree/rw-upgrade-bug) is still broken ❌.

Next week I will try to use `yarn rw build web` and `yarn rw serve` (thanks for the hint) to find the config in webpack that causes the bug.

**Comment by thedavidprice** [comment]
Gah, this stuff is so incredibly painful to debug. Sorry for the hassle you're experiencing here @tilmann 

Off the top of my head, I really can't think of a reason why you can 1) use the same build process but 2) get different results in different contexts... 🤬

Couple sanity check ideas:
- Locally, delete the `web/dist` folder before you build and serve. Still ok?
- Do the same thing on Vercel with "redeploy" — (just confirm when you do to _not_ use  [the build cache](https://vercel.com/changelog/the-build-cache-can-now-be-enabled-when-redeploying)). Still broken?
- Are you using the same versions of Yarn and Node both locally and in Vercel Build?
    - looks like Vercel is yarn v1.22.17 and Node.js v16.x (?)

Things I'd do next:
- instead of figuring out the bug, I'd try restructuring the html and classes; i.e. wrap problematic block in a `div`, or apply classes differently, or try adding the styles directly to div to see what happens
- try Netlify reproduction
- swear. a lot.

**Comment by tilmann** [comment]
Wohoo. We can stop swearing because we are getting one step closer. 

I got a local error message for the prerendering after deleting `web/dist` that does not make a lot of sense (see below).
BUT removing `prerender` from `routes.tsx` leads to a [build](https://marla-mnhj6nqa6-tilmann.vercel.app/logging-in) where the layout is NOT broken. Adding `prerender` for `/` breaks the broken layout.

Please be aware that the page where the layout was broken was NOT prerendered and it is using a different redwood layout than the `/` home page that was prerendered.

It seems like that from 0.42.x something mixes the "prerendered" home page at `/` and other pages when serving in production.

```
---------- Error rendering path "/tos" ----------
TypeError: Cannot read property 'createCell' of undefined
    at Object.createCell (/Users/tilmannb/code/marla/node_modules/@redwoodjs/web/dist/index.js:99:24)
    at Object.<anonymous> (/Users/tilmannb/code/marla/node_modules/@redwoodjs/web/dist/components/createCell.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/tilmannb/code/marla/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/Users/tilmannb/code/marla/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
```

**Comment by thedavidprice** [comment]
Ah, that is a great diagnostic find! Prerender _should_ be using the same asset build process, but clearly something is out of sync here. 

@dac09 is our resident pre-render expert. Can you take a look at this and suggest some next steps for determining why/how prerender would be generating different CSS?

**Comment by dac09** [comment]
Super annoying bug indeed! One more for me to investigate :) 

I don't have access to the repo @tilmann, could I just get a snippet of your routes please? There was one change related to prerender that went in few weeks ago I think.. will double check

**Comment by tilmann** [comment]
@dac09 Thanks for helping. I invited you to the repo but will share the snippet here for explanations and others to follow:

The prerender is set for routes in the `LandingLayout` like `/`.

The layout breaks for the `AppLayout`.

 ```
return
    <Router>
      <Set wrap={AppLayout}>
        <Route path="/logging-in" page={LoggingInPage} name="loggingIn" />
        <Private unauthenticated="home">
          <Route path="/get-started" page={GetStartedPage} name="getStarted" />
        </Private>
      </Set>
      <Set wrap={LandingLayout}>
        <Route path="/" page={HomePage} name="home" prerender />
        <Route path="/pricing" page={PricingPage} name="pricing" />
      </Set>
    </Router>
  )
```

**Comment by Tobbe** [comment]
> There was one change related to prerender that went in few weeks ago I think.. will double check

Are you thinking about my PR? I'm on my phone, but I'll see if I can find it

**Comment by Tobbe** [comment]
https://github.com/redwoodjs/redwood/pull/4047

**Comment by dac09** [comment]
@tilmann so I've been having trouble running your project locally, but commented a bunch of code to just see if I could figure out the prerender issue - I think I know what this is! 

This is totally annoying, and something we really should figure out how to solve, but I'll try and explain what happens.

Because you're prerendering only the landing layout, and not the app layout, when you go directly to the logging-in route, the render flow looks like this:
1. Browser requests page
2. Vercel serves prerendered index.html
3. JS loads, hydrates the page then realises the layout is different, and react can't quite make those diffs work, and breaks the layout.

The solution to this would be either:
a) Prerender your logging-in page, so that the base html isn't completely different
b) Add a redirect in your project's `./vercel.json` that looks like this:
```
{
  "rewrites": [
    { "source": "/(.*)", "destination": "/200.html" }
  ],
  "cleanUrls": true,
  "trailingSlash": false
}
```

What this does, is that it'll serve the page if the route matches an html file that exists. e.g. if you go to /logging-in and logging-in.html exists, it'll serve that. If it doesn't exist, it'll return 200.html (the default un-prerendered page). This makes sure that there isn't a weird layout shift.  

The redirects might not work 100% for you out of the box, but could give you a good starting point. Let me know how you get on!

**Comment by dac09** [comment]
Hey @tilmann - just looping back on this. Please do let me know if the above solution works for you :)

**Comment by dac09** [comment]
Glad to know its working for you! 

The gist of the issue is that when you prerender the homepage, it genreates index.html, which vercel sends for /, `/logged-in` or any other path that doesn't have an html file. But because your other pages don't share the same layout, React struggles :/ 

Would very much appreciate your thoughts on this if you do investigate any further!

**Comment by dac09** [comment]
Just a quick update on this... having spoken to the vercel team we will be handling this during deployment automatically soon so that Redwood users won't need to add the redirects using vercel.json.

Another note, the original vercel.json I posted had an error in it

```diff
{
  "rewrites": [
-    { "source": "/(.*)", "destination": "/200.html" }
+   { "source": "/(.*)", "destination": "/200" }
  ],
  "cleanUrls": true,
  "trailingSlash": false
}
```

This is because the cleanUrls would strip the html _at build time_, as explained in this vercel discussion here [vercel/vercel#6694 (comment)](https://github.com/vercel/vercel/discussions/6694?sort=top#discussioncomment-1335309)

**Comment by tilmann** [comment]
Thanks for the update. 

Another hacky solution I found while trying to understand what happens was adding a `<span>` element for the prerendered pages at the root of a component. 
I assume that the `<div>` gets reused and the classes mix up.  If you have a `<span>` element around that it works.


```
{browser ? (
        <div className="h-screen">content</div>
      ) : (
        <span className="h-screen">
          <Loader />
        </span>
      )}
```
