### ISSUE TITLE
Error on Windows with fresh install (0.46.1)

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/redwood#4578]
I was attempting to reproduce an issue and thoguht I'd try to repeat it on a new redwood install following the tutorial.

On windows I ran the following command

```sh
yarn create redwood-app ./redwoodblog
```

and got the following output.

```sh
jaceb@DESKTOP-E0U6U2Q MINGW64 ~/git
$ yarn create redwood-app ./redwoodblog
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.2.8" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-graphql-tag@3.3.0" has unmet peer dependency "graphql-tag@^2.10.1".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > relay-compiler@12.0.0" has incorrect peer dependency "graphql@^15.0.0".
[4/4] Building fresh packages...

success Installed "create-redwood-app@0.47.0" with binaries:
      - create-redwood-app
  √ Creating Redwood app
    √ Checking node and yarn compatibility
    √ Creating directory 'C:\Users\jaceb\git\redwoodblog'
  √ Installing packages
    √ Running 'yarn install'... (This could take a while)
  × Convert TypeScript files to JavaScript
    → info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Generating types

Error: Command failed with exit code 1: yarn rw ts-to-js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '.prisma/client/index'
Require stack:
- C:\Users\jaceb\git\redwoodblog\node_modules\@prisma\client\index.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\api\dist\validations\validations.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\api\dist\index.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\graphql-server\dist\functions\graphql.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\graphql-server\dist\index.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\internal\dist\generate\graphqlSchema.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\internal\dist\generate\generate.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\internal\dist\index.js
- C:\Users\jaceb\git\redwoodblog\node_modules\@redwoodjs\cli\dist\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jaceb\git\redwoodblog\node_modules\@prisma\client\index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@prisma\\client\\index.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\api\\dist\\validations\\validations.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\api\\dist\\index.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\graphql-server\\dist\\functions\\graphql.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\graphql-server\\dist\\index.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\internal\\dist\\generate\\graphqlSchema.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\internal\\dist\\generate\\generate.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\internal\\dist\\index.js',
    'C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\cli\\dist\\index.js'
  ]
}
error Command failed with exit code 1.
yarn run v1.22.17
$ C:\Users\jaceb\git\redwoodblog\node_modules\.bin\rw ts-to-js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at makeError (C:\Users\jaceb\AppData\Local\Yarn\Data\global\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\jaceb\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: yarn rw ts-to-js',
  command: 'yarn rw ts-to-js',
  escapedCommand: '"yarn rw ts-to-js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn run v1.22.17\n' +
    '$ C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\.bin\\rw ts-to-js\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.',
  stderr: 'node:internal/modules/cjs/loader:936\r\n' +
    '  throw err;\r\n' +
    '  ^\r\n' +
    '\r\n' +
    "Error: Cannot find module '.prisma/client/index'\r\n" +
    'Require stack:\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@prisma\\client\\index.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\api\\dist\\validations\\validations.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\api\\dist\\index.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\graphql-server\\dist\\functions\\graphql.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\graphql-server\\dist\\index.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\internal\\dist\\generate\\graphqlSchema.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\internal\\dist\\generate\\generate.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\internal\\dist\\index.js\r\n' +
    '- C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@redwoodjs\\cli\\dist\\index.js\r\n' +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\r\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\r\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1005:19)\r\n' +
    '    at require (node:internal/modules/cjs/helpers:102:18)\r\n' +
    '    at Object.<anonymous> (C:\\Users\\jaceb\\git\\redwoodblog\\node_modules\\@prisma\\client\\index.js:1:16)\r\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\r\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\r\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)\r\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\r\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1005:19) {\r\n' +
    "  code: 'MODULE_NOT_FOUND',\r\n" +
    '  requireStack: [\r\n' +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@prisma\\\\client\\\\index.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\api\\\\dist\\\\validations\\\\validations.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\api\\\\dist\\\\index.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\graphql-server\\\\dist\\\\functions\\\\graphql.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\graphql-server\\\\dist\\\\index.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\internal\\\\dist\\\\generate\\\\graphqlSchema.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\internal\\\\dist\\\\generate\\\\generate.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\internal\\\\dist\\\\index.js',\r\n" +
    "    'C:\\\\Users\\\\jaceb\\\\git\\\\redwoodblog\\\\node_modules\\\\@redwoodjs\\\\cli\\\\dist\\\\index.js'\r\n" +
    '  ]\r\n' +
    '}\r\n' +
    'error Command failed with exit code 1.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}

Warning: Directory 'C:\Users\jaceb\git\redwoodblog' was created. However, the installation could not complete due to an error.

error Command failed.
Exit code: 1
Command: C:\Users\jaceb\AppData\Local\Yarn\bin\create-redwood-app
Arguments: ./redwoodblog
Directory: C:\Users\jaceb\git
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

jaceb@DESKTOP-E0U6U2Q MINGW64 ~/git
```

I was able to cd into `redwoodblog`, but trying to run yarn rw dev gave me errors too.

I was able cd rm -rf node_modules, then I was able to reinstall them via yarn.

I also wanted to add a new model and run scaffold on it.
The scaffold is generating in typescript, not javascript.

**Comment by simoncrypta** [comment]
I just run the command on Windows and I got no error, but I feel that something had crash when doing the TS to JS. Can you retry  to see if is a possibly intermittent error ?

**Comment by jacebenson** [comment]
yea, okay, seems resolved now.  Thansk @simoncrypta
