### ISSUE TITLE
Schema Loading error on Generate SDL or Scaffold with Relation with Type Generation

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4762]
1. Create new models with relation (at the same time in a single migration).

Here is a Book that is on a Shelf. And a Shelf has many Books.

```
model Book {
  id      Int    @id @default(autoincrement())
  title   String @unique
  Shelf   Shelf? @relation(fields: [shelfId], references: [id])
  shelfId Int?
}

model Shelf {
  id    Int    @id @default(autoincrement())
  name  String @unique
  books Book[]
}
```

2. `yarn rw prisma migrate dev`

3. Now, I want sdls and services.

`yarn rw g sdl Book --crud`

4. The sdl and services **do generate**

```bash
 ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/books.sdl.js`
    ✔ Successfully wrote file `./api/src/services/books/books.scenarios.js`
    ✔ Successfully wrote file `./api/src/services/books/books.test.js`
    ✔ Successfully wrote file `./api/src/services/books/books.js`
```

5. BUT when generating types, the schema fails to load as Book needs Shelf.

Note:  Ignore BigInt warning as that is a separate issue.

```
  ⠙ Generating types ...
Failed to load schema
Failed to load schema
AggregateError: Something went wrong Failed to load schema for "/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/.redwood/schema.graphql"
        Failed to load schema from scalar BigInt

scalar Date

scalar Time

scalar DateTime

scalar JSON

scalar JSONObject

type Redwood {
  version: String
  currentUser: JSON
  prismaVersion: String
}

type Query {
  redwood: Redwood
},graphql/**/*.sdl.{js,ts},directives/**/*.{js,ts}:

        Unknown type: "Shelf".
        Error: Unknown type: "Shelf".
    at getNamedType (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/utilities/extendSchema.js:427:13)
    at getWrappedType (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/utilities/extendSchema.js:442:12)
    at buildFieldMap (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/utilities/extendSchema.js:483:17)
    at fields (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/utilities/extendSchema.js:672:25)
    at resolveObjMapThunk (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/type/definition.js:504:40)
    at defineFieldMap (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/type/definition.js:760:20)
    at GraphQLObjectType._fields (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/type/definition.js:685:26)
    at GraphQLObjectType.getFields (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/type/definition.js:704:27)
    at collectReferencedTypes (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/type/schema.js:387:51)
    at new GraphQLSchema (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/graphql/type/schema.js:174:9)
    
        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file
    
        Try to use one of above options and run codegen again.
    
      
    at executeCodegen (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/@graphql-codegen/cli/index.js:1078:28)
    at async generate (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/@graphql-codegen/cli/index.js:1388:25)
    at async generateGraphQLSchema (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/@redwoodjs/internal/dist/generate/graphqlSchema.js:27:15)
    at async Task.generate [as task] (/Users/dthyresson/Dropbox/Code/redwoodjs/service-validation-test-project/node_modules/@redwoodjs/internal/dist/generate/generate.js:25:22)
```

You can get out of this by

`yarn rw g sdl Shelf --crud`
`yarn rw g types`

6. But we could instead catch the error, and make a friendlier message that says there is a relationship dependency and go view this docs link for more info.

This also impact scaffolding.

See also: https://github.com/redwoodjs/redwood/issues/4394

**Comment by Tobbe** [comment]
> Eventually, we could use the `core` parts of codeine instead

I'm going to have a got at that over here: https://github.com/redwoodjs/redwood/pull/4728 I plan to start working on that tomorrow

**Comment by Tobbe** [comment]
> I'm going to have a go at that over here: #4728 I plan to start working on that tomorrow

I was mistaken. I switched to using graphql-codegen/core for gql documents. This PR needs it for the schema, which is another function.

**Comment by twodotsmax** [comment]
Thanks for working on this. One of the core selling points of Redwood is that code gen is easier than DIY. Ideally you don't have to add things one by one carefully checkpointing with git to avoid the scenario where the black box stopped working and customers expect the software to work, etc
