### ISSUE TITLE
[Prerender] [Router] Prerender breaks if pages in the Router are in subdirectories

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4896]
May be related to #4895 

When a `<Set prerender>` exists, and another page (outside of that Set) comes from a subdirectory, prerender errors out when encountering its route:

```
import { Private, Route, Router, Set } from '@redwoodjs/router'

import JobsPage from 'src/pages/Jobs/JobsPage'
import NewJobPage from 'src/pages/Jobs/NewJobPage'

const Routes = () => {
  return (
    <Router>
      <Set wrap={MainLayout}>
        <Route path="/jobs/new" page={NewJobPage} name="newJob" />
        <Route path="/jobs" page={JobsPage} name="jobs" />

        <Set prerender>
          <Route path="/showcase" page={ShowcasePage} name="showcase" />
          <Set wrap={[ShowcaseLayout]}>
            <Route path="/showcase/snaplet" page={ShowcaseSnapletPage} name="showcaseSnaplet" />
          </Set>
        </Set>
      </Set>
    </Router>
  )
}
```

```
% yarn rw prerender 

You can use `yarn rw prerender --dry-run` to debug

---------- Error rendering path "/showcase" ----------
ReferenceError: NewJobPage is not defined
    at Routes (/Users/rob/Sites/sprout/web/src/Routes.js:35:39)
    at processChild (/Users/rob/Sites/sprout/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/rob/Sites/sprout/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/rob/Sites/sprout/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/rob/Sites/sprout/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/rob/Sites/sprout/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at runPrerender (/Users/rob/Sites/sprout/node_modules/@redwoodjs/prerender/dist/runPrerender.js:54:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Task.task (/Users/rob/Sites/sprout/node_modules/@redwoodjs/cli/dist/commands/prerender.js:108:35)

  ✖ Prerendering /showcase -> web/dist/showcase.html
    → Failed to render "/Users/rob/Sites/sprout/web/src/pages/ShowcasePage/ShowcasePage.js"
    Prerendering /showcase/snaplet -> web/dist/showcase/snaplet.html
```

Presumably it would error out for all of the pages in subdirectories, but it never gets past the first one.

## Steps to Reproduce

We may have a workaround in the `main` branch already, but if you checkout commit `531ce408` you can see it: https://github.com/redwoodjs/sprout

Locally run `yarn rw build && yarn rw serve`.

**Comment by realStandal** [comment]
When working with pages in a subdirectory, I usually have to prefix the page with the subdirectory. So `NewJobPage`, which is located at `src/pages/Jobs/NewJobPage/NewJobPage.js`, would be referenced in `Routes` as `JobsNewJobPage`.

Doing so will resolve the error of not being able to prerender a page while using a page from a subdirectory. However, the issue of not being able to (manually) import a page and prerender another page still persists, which [contradicts the documentation](https://redwoodjs.com/docs/router#not-code-splitting). _It's only when the imported page is within a subdirectory that the error occurs._

```diff
import { Private, Route, Router, Set } from '@redwoodjs/router'

- import JobsPage from 'src/pages/Jobs/JobsPage'
- import NewJobPage from 'src/pages/Jobs/NewJobPage'

const Routes = () => {
  return (
    <Router>
      <Set wrap={MainLayout}>
-       <Route path="/jobs/new" page={NewJobPage} name="newJob" />
-       <Route path="/jobs" page={JobsPage} name="jobs" />
+       <Route path="/jobs/new" page={JobsNewJobPage} name="newJob" />
+       <Route path="/jobs" page={JobsJobsPage} name="jobs" />

        <Set prerender>
          <Route path="/showcase" page={ShowcasePage} name="showcase" />
          <Set wrap={[ShowcaseLayout]}>
            <Route path="/showcase/snaplet" page={ShowcaseSnapletPage} name="showcaseSnaplet" />
          </Set>
        </Set>
      </Set>
    </Router>
  )
}
```

**Comment by thedavidprice** [comment]
related https://github.com/redwoodjs/redwood/pull/4782?
