### ISSUE TITLE
yarn build:test-project --rebuild-fixture fails on tailwind setup step

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#4937]
When trying to rebuild the fixtures for the test project you'll see an error like this

```
  ✔ [link] Copying framework packages to project
  ✔ [link] Add rwfw project:copy postinstall
  ❯ Apply web codemods
    ✔ Creating pages
    ✔ Creating layout
    ✔ Creating components
    ✔ Creating cells
    ✔ Updating cell mocks
    ✔ Changing routes
    ✔ Add Prerender to Routes
    ✖ Install tailwind dependencies
      → Command failed with exit code 1: yarn workspace web add -D postcss postcss-loader tailwindcss autoprefixer
      [link] Copy local framework files again
      Adding Tailwind
    Apply api codemods
    Running prisma migrate reset
    Convert to JS
    Lint --fix all the things
    [Rebuild Fixture] Replace and Cleanup Fixture
    All done!
Error: Command failed with exit code 1: yarn workspace web add -D postcss postcss-loader tailwindcss autoprefixer
    at makeError (/Users/tobbe/dev/redwood/redwood/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/tobbe/dev/redwood/redwood/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: yarn workspace web add -D postcss postcss-loader tailwindcss autoprefixer',
  command: 'yarn workspace web add -D postcss postcss-loader tailwindcss autoprefixer',
  escapedCommand: '"yarn workspace web add -D postcss postcss-loader tailwindcss autoprefixer"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}
```

https://github.com/redwoodjs/redwood/pull/4825#issuecomment-1079539486
According to the comment linked above this started when RW switched from yarn1 to yarn3.

**Comment by Tobbe** [comment]
Going to the temp directory created by the build:test script and manually trying to set up tw a (potentially) more helpful error message is printed:

```
➤ YN0002: │ web@workspace:web doesn't provide graphql (p52200), requested by @redwoodjs/forms
➤ YN0002: │ web@workspace:web doesn't provide webpack (pa4904), requested by postcss-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 311ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 344ms
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: ENOENT: no such file or directory, lstat '/private/var/folders/w7/hkfhzp4x68qcbr1ggchr7hx40000gn/T/redwood-test-project/2022-03-26T07-50-03.253Z/node_modules/@redwoodjs/core/node_modules/@babel/cli/node_modules/semver'
➤ YN0000: └ Completed in 0s 652ms
➤ YN0000: Failed with errors in 2s 361ms
```

I'll try manually installing the semver package and see where that gets us

**Comment by thedavidprice** [comment]
It's project:copy failing on duplicate runs. 

Dom and I diagnosed @tobbe Please don't feel like you need to resolve this now.

**Comment by Tobbe** [comment]
> It's project:copy failing on duplicate runs.

Yeah, that's about as far as I got too :)  Bummer it's broken :/ 

> Dom and I diagnosed @Tobbe Please don't feel like you need to resolve this now.

Great. I'll leave this one open for now then

**Comment by jtoar** [comment]
This no longer fails on the tailwind step. It fails on a later step but it's unrelated to Yarn. I'll make a new issue for updating the fixture.
