### ISSUE TITLE
Error switching database from postgres back to SQLite

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#5043]
I'm hitting a strange behaviour which feels as if the `schema.prisma` is still lingering around in some kind of cache, executing content that is not there anymore.

I worked through the deployment chapter of the tutorial and successfully deployed to netlify with a postgres DB. Because i knew i would want to continue the tutorial locally i only did that specific sub-chapter in a separate branch on: https://github.com/Philzen/redwoodblog-tutorial/tree/netlified-railway

Back on the main branch, when i start prisma studio all my data in the sqlite db created in the previous chapters is still showing up fine. However, my `ArticlesCell` on the home page was showing up EMPTY in the webapp and the logins from the db didn't work. So i also removed the postgres-`DATABASE_URL` from `.env` and tried re-running `yarn rw dev`, and behold:

```bash
/home/phil/prog/testing/rwb-tutorial/node_modules/@prisma/client/runtime/index.js:35591
            throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                  ^

PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgres"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at Object.loadEngine (/home/phil/prog/testing/rwb-tutorial/node_modules/@prisma/client/runtime/index.js:35591:19)
    at async Object.instantiateLibrary (/home/phil/prog/testing/rwb-tutorial/node_modules/@prisma/client/runtime/index.js:35520:5) {
  clientVersion: '3.11.1',
  errorCode: 'P1012'
}
```

Now the funny part is: `schema.prisma` looks like this: 

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
```

:thinking: ?

**Comment by Philzen** [comment]
„Did you try turning it off and on again“ – that doesn't help.

## `yarn rw prisma migrate dev` actually does :tada: 

I guess still getting the hang of it. Sorry for the noise, closing this.
