### ISSUE TITLE
Schema-relations. GraphQLDocumentError  - Cannot query field

### ISSUE THREAD

**Issue by artemhp** [redwoodjs/redwood#5224]
Hi. I was trying to take a look how RedwoodJS scaffold UI for items with relations.

I was referencing to Documentation
[https://redwoodjs.com/docs/schema-relations](https://redwoodjs.com/docs/schema-relations)

Following that guide I couldn't achieve expected result.

1. I have imitated project with `yarn create redwood-app ./redwoodblog`
2. Copied and Pasted from section 
'You can get this working by creating an explicit relationship—defining the table structure yourself:' code.
```
model Product { ... }
model Tag { ... }
model ProductsOnTag { ... }
```
[https://github.com/artemhp/redwood-relations/blob/master/api/db/schema.prisma#L13](https://github.com/artemhp/redwood-relations/blob/master/api/db/schema.prisma#L13)
3. Migrate DB: `yarn rw prisma migrate dev`
4. Scaffold product
`yarn rw g scaffold product`
All files has been successfully created but in output there some errors:
```
Error: Could not generate GraphQL type definitions (web)
AggregateError: GraphQL Document Validation failed with 9 errors;
  Error 0: GraphQLDocumentError: Unknown type "Int".
    at /Users/adeikun/Projects/temp/temp2/redwoodblog/web/src/components/Product/EditProductCell/EditProductCell.js:1:28

Error 1: GraphQLDocumentError: Cannot query field "product" on type "Query".
    at /Users/adeikun/Projects/temp/temp2/redwoodblog/web/src/components/Product/EditProductCell/EditProductCell.js:2:3

Error 2: GraphQLDocumentError: Unknown type "Int".
    at /Users/adeikun/Projects/temp/temp2/redwoodblog/web/src/components/Product/EditProductCell/EditProductCell.js:1:37

Error 3: GraphQLDocumentError: Unknown type "UpdateProductInput".
    at /Users/adeikun/Projects/temp/temp2/redwoodblog/web/src/components/Product/EditProductCell/EditProductCell.js:1:51

Error 4: GraphQLDocumentError: Unknown type "CreateProductInput".
    at /Users/adeikun/Projects/temp/temp2/redwoodblog/web/src/components/Product/NewProduct/NewProduct.js:1:40
``` 
5. Run project `yarn redwood dev`
6. Navigate to http://localhost:8910/products
In console output have errors:
```
api | Starting API Server...
api | Loading server config from /Users/adeikun/Projects/temp/temp2/redwoodblog/api/server.config.js 
api | 
api | Importing Server Functions... 
api | 12:32:16 💀 
api |  ⚠️ GraphQL server crashed 
api |  
api | Error: Unknown type "ProductsOnTag". Did you mean "Product"?
api |     at assertValidSDL (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/validation/validate.js:135:11)
api |     at Object.buildASTSchema (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/buildASTSchema.js:44:34)
api |     at makeExecutableSchema (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/@redwoodjs/graphql-server/node_modules/@graphql-tools/schema/index.js:495:26)
api |     at makeMergedSchema (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/@redwoodjs/graphql-server/dist/makeMergedSchema/makeMergedSchema.js:176:51)
api |     at createGraphQLHandler (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:128:53)
api |     at Object.<anonymous> (/Users/adeikun/Projects/temp/temp2/redwoodblog/api/src/functions/graphql.js:10:24)
api |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
api |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
api |     at Module.load (node:internal/modules/cjs/loader:981:32)
api |     at Function.Module._load (node:internal/modules/cjs/loader:822:12) 
api | {
api |   "err": {
api |     "type": "Error",
api |     "message": "Unknown type \"ProductsOnTag\". Did you mean \"Product\"?",
api |     "stack": "Error: Unknown type \"ProductsOnTag\". Did you mean \"Product\"?\n    at assertValidSDL (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/validation/validate.js:135:11)\n    at Object.buildASTSchema (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/buildASTSchema.js:44:34)\n    at makeExecutableSchema (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/@redwoodjs/graphql-server/node_modules/@graphql-tools/schema/index.js:495:26)\n    at makeMergedSchema (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/@redwoodjs/graphql-server/dist/makeMergedSchema/makeMergedSchema.js:176:51)\n    at createGraphQLHandler (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:128:53)\n    at Object.<anonymous> (/Users/adeikun/Projects/temp/temp2/redwoodblog/api/src/functions/graphql.js:10:24)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)"
api |   }
api | }
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://[::1]:8911/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://[::1]:8911/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
7. On UI page I see an error
"The RedwoodJS API server is not available or is currently reloading. Please refresh."

Repository with use case:
[https://github.com/artemhp/redwood-relations](https://github.com/artemhp/redwood-relations)

**Comment by jtoar** [comment]
@artemhp There's a PR that aims to fix this doc that I've been super behind on reviewing: https://github.com/redwoodjs/redwood/pull/4849.

The TL;DR is you have to generate SDLs for the other models in the relation. Here's a PR on your repo that shows what I mean:

**Comment by artemhp** [comment]
@jtoar thank you so much.
So, I'm trying to resolve that with myself with instructions you provided:

### Command:
```
yarn rw g sdl tag
```

### Output:

```
(node:65282) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/tags.sdl.js`
    ✔ Successfully wrote file `./api/src/services/tags/tags.scenarios.js`
    ✔ Successfully wrote file `./api/src/services/tags/tags.test.js`
    ✔ Successfully wrote file `./api/src/services/tags/tags.js`
  ⠙ Generating types ...
Failed to load schema
Failed to load schema
Error parsing SDLs or Schema

        Failed to load schema from scalar BigInt

scalar Date

scalar Time

scalar DateTime

scalar JSON

scalar JSONObject

type Redwood {
  version: String
  currentUser: JSON
  prismaVersion: String
}

type Query {
  redwood: Redwood
},graphql/**/*.sdl.{js,ts},directives/**/*.{js,ts}:

        Unknown type: "ProductsOnTag".
        Error: Unknown type: "ProductsOnTag".
    at getNamedType (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/extendSchema.js:427:13)
    at getWrappedType (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/extendSchema.js:442:12)
    at getWrappedType (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/extendSchema.js:435:42)
    at getWrappedType (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/extendSchema.js:439:45)
    at buildFieldMap (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/extendSchema.js:483:17)
    at fields (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/utilities/extendSchema.js:672:25)
    at resolveObjMapThunk (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/type/definition.js:504:40)
    at defineFieldMap (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/type/definition.js:760:20)
    at GraphQLObjectType._fields (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/type/definition.js:685:26)
    at GraphQLObjectType.getFields (/Users/adeikun/Projects/temp/temp2/redwoodblog/node_modules/graphql/type/definition.js:704:27)
    
        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/tags.sdl.js`
    ✔ Successfully wrote file `./api/src/services/tags/tags.scenarios.js`
    ✔ Successfully wrote file `./api/src/services/tags/tags.test.js`
    ✔ Successfully wrote file `./api/src/services/tags/tags.js`
  ✔ Generating types ...
```

then

### Command
```
yarn rw g sdl productsOnTag
```

### Output:

```
(node:65348) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Generating SDL files...
    ✔ Successfully wrote file `./api/src/graphql/productsOnTags.sdl.js`
    ✔ Successfully wrote file `./api/src/services/productsOnTags/productsOnTags.scenarios.js`
    ✔ Successfully wrote file `./api/src/services/productsOnTags/productsOnTags.test.js`
    ✔ Successfully wrote file `./api/src/services/productsOnTags/productsOnTags.js`
  ✔ Generating types ...
```

then trying to run app

### Command:
```
 yarn redwood dev    
```

### Navigate:
http://localhost:8910/products
On UI see message: Cannot read properties of undefined (reading 'findMany')

### Output:

```
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 10:49:27 🌲 Server listening at http://[::]:8911
api | 10:49:54 🌲 incoming request POST xxx /graphql
api | 10:49:54 🐛 Checking if GraphiQL Request
api | 10:49:54 🐛 Extracting GraphQL Parameters
api | 10:49:54 🐛 Processing Request
api | 10:49:54 🐛 execute-start
api | 10:49:54 🐛 query FindProducts {
api |   products {
api |     id
api |     title
api |     desc
api |     __typename
api |   }
api | }
api | 10:49:54 🐛 FindProducts
api | 10:49:54 🐛 variables
api | 10:49:54 🐛 graphql-server GraphQL execution started: FindProducts
api | 10:49:54 🐛 execute-end
api | 10:49:54 🐛 -->
api | 10:49:54 🚨 graphql-server Cannot read properties of undefined (reading 'findMany')
api | (node:65475) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
api | 10:49:54 🌲 request completed 39ms
```

What am I doing wrong?

**Comment by jtoar** [comment]
@artemhp No worries? And I think I usually see that one when I haven't migrated the database yet. Have you run this one yet?

```
yarn rw prisma migrate dev
```

**Comment by artemhp** [comment]
@jtoar thanks. 
Now it has no error and I'm able to land on page: `/products but on /products/new`
### But there are no field tags.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2180061/163975054-a63f9e45-58e3-4eb6-8f1a-c214ce192383.png">

### So, I have decided to scaffold tags. 
And it was not easy. 
After command `yarn rw g scaffold tag` was error that I already have tags.sdl.js.
So, I had to remove that file and also some components that has been created after not successful scaffolding.

### My commands set that helps me to achieve some result:
```
yarn rw g sdl tag
yarn rw g sdl productsOnTag
yarn rw prisma migrate dev   
yarn rw g scaffold tag
rm api/src/graphql/tags.sdl.js
rm -rf web/src/components/Tag
rm -rf api/src/services/tags
yarn rw g scaffold tag
yarn redwood dev
```

Finally I have tags and products. 
<img width="513" alt="image" src="https://user-images.githubusercontent.com/2180061/163976456-64c53e97-6e42-4c5e-acb9-5e49039c286d.png">

**I'm able to add new tags but still don't have field on Product for tags.**

**Comment by jtoar** [comment]
> I'm able to add new tags but still don't have field tags on Product page
> But I was expecting to get that because it has relations.

Understood! We could do a better job of communicating what is and isn't supported. The scaffolds are better than they were, but they still don't generate fields for all the possible kinds of relations yet. If you generated the scaffold for `ProductsOnTag`, I think you'd see the fields for `tagId` and `productId`. So models that have one relation tend to work, but not many. 

Note that you can still edit relational data in prisma studio:

```
yarn rw prisma studio 
```

But right now you won't get the UI you're expecting from the scaffolds. Sorry about that!

**Comment by artemhp** [comment]
@jtoar OK. 
Can you point me on some guide that will help me to scaffold Product page with some relations?
That works. Not with many-to-many.

**Comment by jtoar** [comment]
@artemhp Apologies for the delay; I feel like the confusion here is that scaffolds simply don't do what you want yet. It's certainly possible to do it manually, but I don't have a guide that's readily available. But it would make for a great one if it was! Any chance that you got this to work and could share something with the community?

**Comment by jtoar** [comment]
@Isaac-Tait I had a quick look and correct me if I'm wrong but this seems unrelated no? This thread is about scaffolding with many to many relations.

**Comment by jtoar** [comment]
I'm going to close this one for now; if you'd like to open a feature request we're happy to talk about it.
