### ISSUE TITLE
Using mongodb datasource for prisma causes jest test api to fail

### ISSUE THREAD

**Issue by masterbater** [redwoodjs/redwood#5404]
Running this command
` yarn rw test api`

Causes this errror you can reproduce it with a newly created redwood project and change datasource to mongodb
`error: Error validating datasource `db`: the URL must start with the protocol `mongo`.`

```
Full error
Running Prisma CLI...
$ yarn prisma db push --force-reset --accept-data-loss --schema "/home/jasonzach/modernsmarthealth/api/db/schema.prisma"

Environment variables loaded from .env
Prisma schema loaded from api/db/schema.prisma
Error: Get config: Schema Parsing P1012

error: Error validating datasource `db`: the URL must start with the protocol `mongo`.
  -->  schema.prisma:7
   | 
 6 |   provider = "mongodb"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

● Validation Error:

  An unknown error occurred in @redwoodjs/testing/config/jest/api:

  Command failed with exit code 1: yarn rw prisma db push --force-reset --accept-data-loss
  Error: Command failed with exit code 1: yarn rw prisma db push --force-reset --accept-data-loss
    at makeError (/home/jasonzach/modernsmarthealth/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/home/jasonzach/modernsmarthealth/node_modules/execa/index.js:194:17)
    at Object.<anonymous> (/home/jasonzach/modernsmarthealth/node_modules/@redwoodjs/testing/config/jest/api/jest-preset.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImportModule (/home/jasonzach/modernsmarthealth/node_modules/jest-util/build/requireOrImportModule.js:53:28)
```

**Comment by masterbater** [comment]
Everything works perfectly from scaffold but only jest test api causes this error. 

Running this directly doesnt causes error `error: Error validating datasource `db`: the URL must start with the protocol `mongo`.`
yarn prisma db push --force-reset --accept-data-loss --schema "/home/jasonzach/modernsmarthealth/api/db/schema.prisma"

**Comment by YannBirba** [comment]
I got the same problem with postgresql.

`yarn rw test
(node:28116) [FST_MODULE_DEP_FASTIFY-REPLY-FROM] FastifyWarning.fastify-reply-from: fastify-reply-from has been deprecated. Use @fastify/reply-from@7.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28320) [FST_MODULE_DEP_FASTIFY-REPLY-FROM] FastifyWarning.fastify-reply-from: fastify-reply-from has been deprecated. Use @fastify/reply-from@7.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)

Running Prisma CLI...
$ yarn prisma db push --force-reset --accept-data-loss --schema "C:\Users\Yann\Documents\dev\Redwood\redwoodblog\api\db\schema.prisma"

Environment variables loaded from .env
Prisma schema loaded from api\db\schema.prisma
Error: Get config: Schema Parsing P1012

error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

● Validation Error:

  An unknown error occurred in @redwoodjs/testing/config/jest/api:

  Command failed with exit code 1: yarn rw prisma db push --force-reset --accept-data-loss
  Error: Command failed with exit code 1: yarn rw prisma db push --force-reset --accept-data-loss
    at makeError (C:\Users\Yann\Documents\dev\Redwood\redwoodblog\node_modules\execa\lib\error.js:60:11)
    at Function.module.exports.sync (C:\Users\Yann\Documents\dev\Redwood\redwoodblog\node_modules\execa\index.js:194:17)
    at Object.<anonymous> (C:\Users\Yann\Documents\dev\Redwood\redwoodblog\node_modules\@redwoodjs\testing\config\jest\api\jest-preset.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) 
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImportModule (C:\Users\Yann\Documents\dev\Redwood\redwoodblog\node_modules\jest-util\build\requireOrImportModule.js:53:28)

  Configuration Documentation:
  https://jestjs.io/docs/configuration`

**Comment by YannBirba** [comment]
Oh, sorry i forgot this part of the configuration. I thought that testing system uses the DATABASE_URL variable.
Yeah i think it can be a good idea to improve the error message and add this configuration in the tutorial.
In addition, we unfortunatly need to compile even in developement to use environement variable.
Thank you for your answer.
