### ISSUE TITLE
Storybook loading indefinitely on newly-created projects

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#5612]
A user in Discord reported Storybook loading indefinitely. I can reproduce it on a newly-created project, and it's probably why CI (the `smoke-test` specifically) is failing across the board.

It looks like the break in CI coincided with the latest release of `@mswjs
/interceptors`. Moreover, Storybook starts up again if you set a resolution in your project downgrading `@mswjs
/interceptors` to `0.15.1` (and then `yarn install` afterwards):

```json
"resolutions": {
  "@mswjs/interceptors": "0.15.1"
}
```

The error in the Console panel in the devtools is:

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at __webpack_modules__.../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js.__extends (NodeClientRequest.js:11:1)
    at NodeClientRequest.js:112:1
    at ../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js (NodeClientRequest.js:460:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/http.get.js (http.get.js:25:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

**Comment by jtoar** [comment]
Maybe to be expected since it also uses `msw`, but `yarn rw test web` now fails too, for Cells at least with `TypeError: interceptors.createInterceptor is not a function`. See https://github.com/mswjs/interceptors/issues/245.
