### ISSUE TITLE
Project absolute path issues

### ISSUE THREAD

**Issue by JesseKoldewijn** [redwoodjs/redwood#5705]
When running ```yarn rw dev``` users might get the following error:

```
web | [webpack-cli] Failed to load <DIR_TO_PROJECT_ROOT>/node_modules/@redwoodjs/core/config/webpack.development.js' config
web | [webpack-cli] Error: Cannot find module <DIR_TO_PROJECT_ROOT>/node_modules/@redwoodjs/core/config/webpack.development.js'
web | Require stack:
web | - <DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.jsweb | - <DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/bootstrap.js
web | - <DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/bin/cli.js
web | - <DIR_TO_PROJECT_ROOT>/node_modules/webpack/bin/webpack.js
web | - <DIR_TO_PROJECT_ROOT>/node_modules/webpack/package.json
web |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
web |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
web |     at require (node:internal/modules/cjs/helpers:102:18)
web |     at WebpackCLI.tryRequireThenImport (<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.js:244:16)
web |     at loadConfigByPath (<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.js:1712:30)
web |     at <DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.js:1767:11
web |     at Array.map (<anonymous>)
web |     at WebpackCLI.loadConfig (<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.js:1766:24)
web |     at WebpackCLI.createCompiler (<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.js:2187:29) {
web |   code: 'MODULE_NOT_FOUND',
web |   requireStack: [
web |     "<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/webpack-cli.js",
web |     "<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/lib/bootstrap.js",
web |     "<DIR_TO_PROJECT_ROOT>/node_modules/webpack-cli/bin/cli.js",
web |     "<DIR_TO_PROJECT_ROOT>/node_modules/webpack/bin/webpack.js",
web |     "<DIR_TO_PROJECT_ROOT>/node_modules/webpack/package.json"
web |   ]
web | }
web | cd "<DIR_TO_PROJECT_ROOT>/web" && yarn cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --config "<DIR_TO_PROJECT_ROOT>/node_modules/@redwoodjs/core/config/webpack.development.js"  exited with code 2
```

I personally ran into this problem both on Windows and Linux/OSX.

What might be a good solution if possible is to check the project's absolute directory path on both the project creation and dev script because this error seems to pop up due to special characters in the absolute path of the project.

Another solution could be to move to relative path usage instead of absolute ones. Both should be fine and fix some headaches.

If there's a need for further details I'd be happy to explain the issue I ran into further in detail.

**Comment by simoncrypta** [comment]
Hi @JesseKoldewijn thanks for this issue !

>  This error seems to pop up due to special characters in the absolute path of the project.

Can I know what is the special characters ?

**Comment by JesseKoldewijn** [comment]
@simoncrypta hello, the special character that caused issues was the single quote

**Comment by JesseKoldewijn** [comment]
@simoncrypta is there any update on this issue? Just curious, no real hurry ofcourse!😁

**Comment by simoncrypta** [comment]
@JesseKoldewijn This is a case which our internal path regex fail and if the OS accepted to have single quote in directory name, we should also handle it. 
I don't have any delays of when it can be fixed, but feel free to open a PR if you want :)
