### ISSUE TITLE
[Bug?]: graphql query OpenWeather fails

### ISSUE THREAD

**Issue by aleeusgr** [redwoodjs/redwood#5864]
### What's not working?

Following [this doc](https://redwoodjs.com/docs/how-to/using-a-third-party-api#server-side-api-integration),  section Server-side integration, The Service.
Running a query in http://localhost:8911/graphql:
```
query GetWeatherQuery($zip: String!) {
    weather: getWeather(zip: $zip) {
      zip
      city
    	conditions
      temp
    	icon
    }
  }
  ```
 `{"zip": "94040"}`

If I have `export const getWeather...` in `api/src/services/weather/weather.js` the Playground produces the right output, Hot Lava.

However when I move to next step (run `yarn workspace api add cross-undici-fetch`  and the following) code into the file, I get an error:
```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading '0')",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ],
  "data": null
}
```

I tried different API keys (the one at the beginning, and my own), and the result is the same.

console output:
```
graphql-server Cannot read properties of undefined (reading '0')                                     
api |                                                                                                                  
api | 🚨 GraphQLError Info                                                                                             
api |                                                                                                                  
api | {                                                                                                                
api |   "path": [                                                                                                      
api |     "weather"                                                                                                    
api |   ],                                                                                                             
api |   "locations": [                                                                                                 
api |     {                                                                                                            
api |       "line": 2,                                                                                                 
api |       "column": 3                                                                                                
api |     }                                                                                                            
api |   ],                                                                                                             
api |   "extensions": {}                                                                                               
api | }
api |  
api | 🥞 Error Stack
api | 
api | /home/alex/workshop/dandelion-gql/api/src/services/weather/weather.js:12
api |     conditions: json.weather[0].main,
api |                      ^
api | 
api | TypeError: Cannot read properties of undefined (reading '0')
at Object.getWeather (/home/alex/workshop/dandelion-gql/api/src/services/weather/weather.js:12:22)
api |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
api |     at async Promise.all (index 0)
api |     at async /home/alex/workshop/dandelion-gql/node_modules/@envelop/core/cjs/orchestrator.js:379:27
api |     at async processRequest (/home/alex/workshop/dandelion-gql/node_modules/@graphql-yoga/common/index.js:194:20)
api |     at async YogaServer.getResponse (/home/alex/workshop/dandelion-gql/node_modules/@graphql-yoga/common/index.js
:909:28)
api |     at async YogaServer.handleRequest (/home/alex/workshop/dandelion-gql/node_modules/@graphql-yoga/common/index.
js:671:30)
api |     at async handlerFn (/home/alex/workshop/dandelion-gql/node_modules/@redwoodjs/graphql-server/dist/functions/g
raphql.js:271:24)
api |     at async execFn (/home/alex/workshop/dandelion-gql/node_modules/@redwoodjs/graphql-server/dist/functions/grap
hql.js:310:16)
api |     at async requestHandler (/home/alex/workshop/dandelion-gql/node_modules/@redwoodjs/api-server/dist/requestHan
dlers/awsLambdaFastify.js:121:30)
api | 
api | 13:45:40 🌲 request completed 331ms

```

### How do we reproduce the bug?

Follow [the tutorial](https://redwoodjs.com/docs/how-to/using-a-third-party-api) to the section Server-side Integration, The Service.

Create file `api/src/services/weather/weather.js`

go to http://localhost:8911/

input the query into the Playground and run. 
Observe the output with first option for the file content.
Change the file to query the API and observe output. 

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.15 NixOS 22.05 (Quokka) 22.05 (Quokka)
    Shell: 5.1.16 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 16.15.0 - /tmp/nix-shell.QnGMJz/xfs-c781e249/node
    Yarn: 3.2.1 - /tmp/nix-shell.QnGMJz/xfs-c781e249/yarn
  Browsers:
    Firefox: 101.0.1
__I use Brave Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (64-bit) __
  npmPackages:
    @redwoodjs/core: 2.0.0 => 2.0.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by aleeusgr** [comment]
I am an idiot.
The api key you provide in the guide is most likely null, and I didn't confirm my email.
All works good, sorry

**Comment by jtoar** [comment]
@aleeusgr no worries! And don't be too hard on yourself haha 😅
