### ISSUE TITLE
[Bug?]: Deploy to Netlify and Vercel not working when prerendering with Redwood canary

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#6088]
### What's not working?

I have a RW app where I prerender the home page. This works fine when I run everything locally. But it fails when I try to deploy to Netlify or Vercel.

This is what I see on Netlify

![image](https://user-images.githubusercontent.com/30793/181996699-ad9b740c-7078-425d-8c01-268d679b601c.png)

And for better googleability, here's the plain-text version
```
9:38:14 PM: Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
9:38:14 PM: In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
9:38:14 PM:     at new PrismaClient (/opt/build/repo/node_modules/.prisma/client/index.js:3:11)
9:38:14 PM:     at Object.<anonymous> (/opt/build/repo/api/src/lib/db.ts:13:19)
9:38:14 PM:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
9:38:14 PM:     at Module._compile (/opt/build/repo/node_modules/pirates/lib/index.js:136:24)
9:38:14 PM:     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
9:38:14 PM:     at Object.newLoader [as .ts] (/opt/build/repo/node_modules/pirates/lib/index.js:141:7)
9:38:14 PM:     at Module.load (node:internal/modules/cjs/loader:981:32)
9:38:14 PM:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
9:38:14 PM:     at Module.require (node:internal/modules/cjs/loader:1005:19)
9:38:14 PM:     at require (node:internal/modules/cjs/helpers:102:18)
9:38:14 PM: [19:38:14] Prerendering / -> web/dist/index.html [failed]
9:38:14 PM: [19:38:14] → Failed to render "/opt/build/repo/web/src/pages/HomePage/HomePage.tsx"
9:38:14 PM: [19:38:14] Prerendering Web... [failed]
9:38:14 PM: [19:38:14] → Failed to render "/opt/build/repo/web/src/pages/HomePage/HomePage.tsx"
9:38:14 PM: Failed to render "/opt/build/repo/web/src/pages/HomePage/HomePage.tsx"
```

Further up the logs I also see this:
```
9:37:44 PM: ────────────────────────────────────────────────────────────────
9:37:44 PM:   1. build.command from netlify.toml                            
9:37:44 PM: ────────────────────────────────────────────────────────────────
9:37:44 PM: 
9:37:44 PM: $ yarn rw deploy netlify
9:37:46 PM: 
9:37:46 PM: Running:
9:37:46 PM: yarn rw build --verbose && yarn rw prisma migrate deploy && yarn rw data-migrate up
9:37:52 PM: [19:37:52] Generating Prisma Client... [started]
9:37:55 PM: Prisma schema loaded from db/schema.prisma
9:37:57 PM: ✔ Generated Prisma Client (3.15.2 | library) to ./../node_modules/@prisma/client in 75ms
9:37:57 PM: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
9:37:57 PM: ``
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
``9:37:57 PM: [19:37:57] Generating Prisma Client... [completed]
9:37:57 PM: [19:37:57] Verifying graphql schema... [started]
9:37:57 PM: [19:37:57] Verifying graphql schema... [completed]
```

Which seems to suggest the Prisma Client is indeed generated. But it's still not working...

Trying to deploy to Vercel I get the exact same error

### How do we reproduce the bug?

Pseudo-steps for reproduction:
`yarn create redwood-app prerender-bug`
`yarn rw g page home /`
`yarn rw g cell HomeCell`
Update Routes.js to prerender /
Wire something up on the api side to just return a static string or something using gql to the web side. No need to talk to a DB or anything like that
`yarn rw setup deploy netlify`

And then push to github and link your netlify account to the gh repo.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Tobbe** [comment]
I managed to reproduce the behavior locally

```
rm -fr node_modules/
yarn
yarn rw build web
```

And making it work is as simple as

```
rm -fr node_modules/
yarn
yarn rw prisma generate
yarn rw build web
```

And if I change my build command in `netlify.toml` to this, it starts working on Netlify too!
```
[build]
command = "yarn rw prisma generate && yarn rw build --verbose"
```
(I removed prisma migrate and data migrate because I don't need that for this simple project)

**Comment by Tobbe** [comment]
Another option that seems to work is to split the build command to build the api side first, and then the web side

```
[build]
command = "yarn rw build api --verbose && yarn rw build web --verbose"
```

**Comment by Tobbe** [comment]
As seen here, prisma generate is only run when building the api side. So I thought it would be as easy as removing that check to let it run for web side builds too. But even doing so I get the same error as before
 https://github.com/redwoodjs/redwood/blob/112a2e551c277a8064564eb65f0e9f3cec5f5680/packages/cli/src/commands/buildHandler.js#L55-L67

Also tried running it with a bunch of different options to `execa`, but no luck 🙁 But if I have it running on web side builds too, and build for web twice it always works just fine the second time. 

Even tried adding a 20 second timeout after building the client before continuing, but still get the same error.

I'm out of ideas for now

**Comment by Tobbe** [comment]
Got a solution in #6093 The key was to kick off a new process for prerendering. That new process could find the generated client 🙂
