### ISSUE TITLE
[Bug?]: Deploying on Netlify Sending Images/Emails across the serverless 502

### ISSUE THREAD

**Issue by Gresliebear** [redwoodjs/redwood#6149]
### What's not working?

I managed to deploy my first serverless application with redwood on netlify for a customer however a core function that I built allows the user to send a submission of photos and text to customer email as a invoice of sorts. 

However this doesn't work with Netlify functions. I get 503 

![image](https://user-images.githubusercontent.com/13157730/183268810-30470d06-9953-4088-a637-528cde8b0114.png)

I have been working on this for few weeks now and am soooo close to getting it work, its works locally and netlify dev easily but on  deployment it breaks so I went to graphql netlify function URL `https://diamondhaulingpa.com/.netlify/functions/graphql`

its some sort of Auth issue with AWS Lamba is anyone familiar? 

![image](https://user-images.githubusercontent.com/13157730/183268822-ee92ea0a-1ad5-4504-b432-ec46e6e359ec.png)

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Gresliebear** [comment]
here's database logs
```

2022-08-06 22:54:31.877 UTC [10484] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 22:54:31.884 UTC [10485] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 22:57:34.532 UTC [10502] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 22:57:34.538 UTC [10503] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 22:58:25.958 UTC [10564] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 22:59:51.499 UTC [10592] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 23:00:47.509 UTC [10611] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 23:00:53.658 UTC [10612] LOG:  TimescaleDB background worker scheduler for database 17831 will be stopped
2022-08-06 23:00:53.658 UTC [10612] STATEMENT:  DROP DATABASE IF EXISTS "prisma_migrate_shadow_db_3cb06ceb-b140-4d49-8f49-c991fff3beea"
2022-08-06 23:01:01.137 UTC [10612] LOG:  TimescaleDB background worker scheduler for database 17897 will be stopped
2022-08-06 23:01:01.137 UTC [10612] STATEMENT:  DROP DATABASE IF EXISTS "prisma_migrate_shadow_db_777a0e05-6562-4ed5-85d5-d842ad18716a"
2022-08-06 23:04:15.600 UTC [10364] LOG:  could not receive data from client: Operation timed out
2022-08-06 23:04:15.600 UTC [10566] LOG:  could not send data to client: Connection reset by peer
2022-08-06 23:04:15.601 UTC [10566] FATAL:  connection to client lost
2022-08-06 23:04:15.601 UTC [10593] LOG:  could not send data to client: Connection reset by peer
2022-08-06 23:04:15.601 UTC [10593] FATAL:  connection to client lost
2022-08-06 23:04:15.601 UTC [10612] LOG:  could not send data to client: Connection reset by peer
2022-08-06 23:04:15.601 UTC [10612] FATAL:  connection to client lost
2022-08-06 23:04:57.672 UTC [10692] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 23:05:01.908 UTC [10693] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 23:13:10.121 UTC [10838] LOG:  could not receive data from client: Connection reset by peer
2022-08-06 23:13:10.128 UTC [10839] LOG:  could not receive data from client: Connection reset by peer

```

**Comment by Gresliebear** [comment]
Here waiting for the functions server on netlify to response for 2s to 4s

![image](https://user-images.githubusercontent.com/13157730/183269180-69960ae7-8c82-4005-b155-c97627ad909b.png)

**Comment by Gresliebear** [comment]
`Runtime.ImportModuleError - Error: Cannot find module '..\..\lib\auth' Require stack: - /var/task/api/dist/directives/requireAuth/requireAuth.js - /var/task/api/dist/functions/graphql.js - /var/task/graphql.js - /var/runtime/index.mjs`

so if I ren the Netlify function crash it says that it "Cannot find module" so that means some where in dist requireAuth.js is not found so I try to add library in netlify.toml 

![image](https://user-images.githubusercontent.com/13157730/183304412-92d2b301-69b5-4577-a558-a760b037f889.png)

this syntax is incorrect
![image](https://user-images.githubusercontent.com/13157730/183304421-d27ff225-f562-4b07-9f69-ee8f663f5287.png)

![image](https://user-images.githubusercontent.com/13157730/183304672-96056cbb-b3da-4c7b-ad5d-3b3944d783db.png)

![image](https://user-images.githubusercontent.com/13157730/183304676-af752244-f155-4867-8202-aa922eba4081.png)

even if we do something like remove /functions/ so we can capture the require requireAuth.js this causes the functions server to crash 

![image](https://user-images.githubusercontent.com/13157730/183304947-b907e31d-aeb2-412e-a716-edd5dfbe98b5.png)

**Comment by Gresliebear** [comment]
I don't know if this will a issue for Redwood 
![image](https://user-images.githubusercontent.com/13157730/183305294-963e7f00-648c-4c98-9325-7db30948b5b6.png)

**Comment by Gresliebear** [comment]
Runtime.ImportModuleError - Error: Cannot find module '..\..\lib\auth' Require stack: - /var/task/api/dist/directives/requireAuth/requireAuth.js - /var/task/api/dist/functions/graphql.js - /var/task/graphql.js - /var/runtime/index.mjs

so netlify considers this a external node model 

![image](https://user-images.githubusercontent.com/13157730/183307121-4d2f943a-3fd6-443a-b721-6552d5eac2ea.png)

thats why it cannot find it so Netlify esbuild bundler is in beta so it breaks everything when I try to import external module 

```

  2. Functions bundling
────────────────────────────────────────────────────────────────

Packaging Functions from api\dist\functions directory:
 - graphql.js

X [ERROR] Could not resolve "..\\lib\\db"

    api/dist/functions/graphql.js:32:24:
      32 │ var import_db = require("..\\lib\\db");
         ╵                         ~~~~~~~~~~~~~

  Use the relative path "./..\\lib\\db" to reference the file "api/dist/lib/db.js". Without the
  leading "./", the path "..\\lib\\db" is being interpreted as a package path instead.

X [ERROR] Could not resolve "..\\lib\\logger"

    api/dist/functions/graphql.js:33:28:
      33 │ var import_logger = require("..\\lib\\logger");
         ╵                             ~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\lib\\logger" to reference the file "api/dist/lib/logger.js". Without
  the leading "./", the path "..\\lib\\logger" is being interpreted as a package path instead.

X [ERROR] Could not resolve "..\\..\\lib\\auth"

    api/dist/directives/requireAuth/requireAuth.js:25:26:
      25 │ var import_auth = require("..\\..\\lib\\auth");
         ╵                           ~~~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\..\\lib\\auth" to reference the file "api/dist/lib/auth.js". Without
  the leading "./", the path "..\\..\\lib\\auth" is being interpreted as a package path instead.

X [ERROR] Could not resolve "..\\..\\lib\\db"

    api/dist/services/posts/posts.js:27:24:
      27 │ var import_db = require("..\\..\\lib\\db");
         ╵                         ~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\..\\lib\\db" to reference the file "api/dist/lib/db.js". Without the
  leading "./", the path "..\\..\\lib\\db" is being interpreted as a package path instead.

X [ERROR] Could not resolve "..\\..\\lib\\db"

    api/dist/services/photos/photos.js:28:24:
      28 │ var import_db = require("..\\..\\lib\\db");
         ╵                         ~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\..\\lib\\db" to reference the file "api/dist/lib/db.js". Without the
  leading "./", the path "..\\..\\lib\\db" is being interpreted as a package path instead.

X [ERROR] Could not resolve "..\\..\\lib\\db"

    api/dist/services/pickUpSchemata/pickUpSchemata.js:33:24:
      33 │ var import_db = require("..\\..\\lib\\db");
         ╵                         ~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\..\\lib\\db" to reference the file "api/dist/lib/db.js". Without the
  leading "./", the path "..\\..\\lib\\db" is being interpreted as a package path instead.

X [ERROR] Could not resolve "..\\..\\lib\\email"

    api/dist/services/pickUpSchemata/pickUpSchemata.js:34:27:
      34 │ var import_email = require("..\\..\\lib\\email");
         ╵                            ~~~~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\..\\lib\\email" to reference the file "api/dist/lib/email.js".
  Without the leading "./", the path "..\\..\\lib\\email" is being interpreted as a package path
  instead.

X [ERROR] Could not resolve "..\\..\\lib\\extractimage"

    api/dist/services/pickUpSchemata/pickUpSchemata.js:35:34:
      35 │ var import_extractimage = require("..\\..\\lib\\extractimage");
         ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Use the relative path "./..\\..\\lib\\extractimage" to reference the file
  "api/dist/lib/extractimage.js". Without the leading "./", the path "..\\..\\lib\\extractimage" is
  being interpreted as a package path instead.

X [ERROR] Could not resolve "@clerk/clerk-sdk-node/instance"

    node_modules/@redwoodjs/api/dist/auth/decoders/clerk.js:17:24:
      17 │   const Clerk = require('@clerk/clerk-sdk-node/instance').default;
         ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@clerk/clerk-sdk-node/instance" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch block to
  handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "@magic-sdk/admin"

    node_modules/@redwoodjs/api/dist/auth/decoders/magicLink.js:22:14:
      22 │   } = require('@magic-sdk/admin');
         ╵               ~~~~~~~~~~~~~~~~~~

  You can mark the path "@magic-sdk/admin" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

10 of 11 errors shown (disable the message limit with --log-limit=0)

❯ Failed to bundle functions with selected bundler (fallback used):
   - graphql.zip

```

**Comment by dthyresson** [comment]
@Gresliebear How does for function return the response body? 

Netlify needs it to be a certain way.

See https://github.com/redwoodjs/redwood/pull/877

**Comment by Gresliebear** [comment]
> 



> @Gresliebear How does your function return the response body?
> 
> Netlify needs it to be a certain way.
> 
> See #877 and #864

Well I fixed that 502 error by changing functions in netlify.toml 

```
[functions]
directory = "api/dist/functions"
```

to 

```
[functions]
directory = "api/dist"
```

this provides access to the modules in '..\..\lib\auth' now I am left with different error 404 which returns a html page, in turn this triggers another bug called 'Error: Unexpected token < in JSON at position 0 '
![image](https://user-images.githubusercontent.com/13157730/183310062-ced93efe-431c-4190-a63c-06da37d7b60c.png)

The 502 error response comes from the fact that when I set directory ="api/dist/functions" it doesn't has access to the modules so return response body is same from accessing the URL at `https://diamondhaulingpa.com/.netlify/functions/graphql`

`{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '..\\..\\lib\\auth'\nRequire stack:\n- /var/task/api/dist/directives/requireAuth/requireAuth.js\n- /var/task/api/dist/functions/graphql.js\n- /var/task/graphql.js\n- /var/runtime/index.mjs","trace":["Runtime.ImportModuleError: Error: Cannot find module '..\\..\\lib\\auth'","Require stack:","- /var/task/api/dist/directives/requireAuth/requireAuth.js","- /var/task/api/dist/functions/graphql.js","- /var/task/graphql.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:726:17)","    at async Object.module.exports.load (file:///var/runtime/index.mjs:741:21)","    at async file:///var/runtime/index.mjs:781:15","    at async file:///var/runtime/index.mjs:4:1"]}`

Currently I am pursuing 404 bug to fix my issue I need to get this done by this week, I want to work on other orders and github issues.

**Comment by Gresliebear** [comment]
Closing thoughts netilfy.toml default builder is called zip-it-and-ship-it so made issue asking about accessing scripts outside of the build. 

https://github.com/netlify/zip-it-and-ship-it/issues?q=is%3Aissue+Error%3A+Cannot+find+module+is%3Aclosed

**Comment by dthyresson** [comment]
@Gresliebear Can we close this issue?

I believe the problem was that you were trying to deploy using the Netlify CLI and this will not package up and deploy the app properly.

Instead, as per the new docs, Netlify deploys should be done using the GitHub integration and build on their platform.

**Comment by Gresliebear** [comment]
> @Gresliebear Can we close this issue?
> 
> I believe the problem was that you were trying to deploy using the Netlify CLI and this will not package up and deploy the app properly.
> 
> Instead, as per the new docs, Netlify deploys should be done using the GitHub integration and build on their platform.

Go ahead! I talked with Netlify they said was redwood issues. Honestly its too much of hot potato issue that i am moving on.
