### ISSUE TITLE
[Bug?]:  PrismaClientUnknownRequestError: Response from the Engine was empty

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#6326]
### What's not working?

After updating to the latest canary our backend seems to crash, at least in dev mode.

The problem disappears, when I switch back to 2.2.3

```
yarn rw dev
gen | Generating TypeScript definitions and GraphQL schemas...
gen | 110 files generated
api | Building... Took 1385 ms
api | Debugger listening on ws://127.0.0.1:18911/70cbe147-93a8-468e-baac-ab0c65249e9f
api | For help, see: https://nodejs.org/en/docs/inspector
api | Starting API Server...
api | Loading server config from /home/klampe/dev/slashskills/api/server.config.js 
api | 
api | Importing Server Functions... 
api | /graphql 1686 ms
api | ...Done importing in 1686 ms
api | 11:29:22 🐛 Fastify server configuration 
api | 🗒 Custom
api | {
api |   "connectionTimeout": 0,
api |   "keepAliveTimeout": 72000,
api |   "maxRequestsPerSocket": 0,
api |   "requestTimeout": 0,
api |   "requestIdHeader": "request-id",
api |   "requestIdLogLabel": "reqId",
api |   "disableRequestLogging": false,
api |   "bodyLimit": 1048576,
api |   "caseSensitive": true,
api |   "allowUnsafeRegex": false,
api |   "ignoreTrailingSlash": false,
api |   "ignoreDuplicateSlashes": false,
api |   "jsonShorthand": true,
api |   "maxParamLength": 100,
api |   "onProtoPoisoning": "error",
api |   "onConstructorPoisoning": "error",
api |   "pluginTimeout": 10000,
api |   "http2SessionTimeout": 72000,
api |   "exposeHeadRoutes": true
api | }
api | Took 1800 ms
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 11:29:22 🐛 Registered plugins 
api | bound root 1762 ms
api | ├── bound _after 9 ms
api | ├── @fastify/url-data 0 ms
api | ├── fastify-raw-body 1 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | └── bound _after 0 ms
api | 
api | 11:29:22 🌲 Server listening at http://[::]:8911
web | assets by path static/js/*.js 8.66 MiB
web |   asset static/js/app.bundle.js 3.95 MiB [emitted] (name: app) 1 related asset
web |   asset static/js/src_pages_MatchPage_MatchPage_tsx.chunk.js 1.71 MiB [emitted] 1 related asset
web |   asset static/js/src_pages_Project_ProjectPage_ProjectPage_tsx.chunk.js 623 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_StatsPage_StatsPage_tsx.chunk.js 546 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_Skill_SkillPage_SkillPage_tsx.chunk.js 541 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_Project_NewProjectPage_NewProjectPage_tsx.chunk.js 288 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_AdminPage_AdminPage_tsx.chunk.js 283 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_Project_ProjectsPage_ProjectsPage_tsx.chunk.js 252 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_MyProfilePage_MyProfilePage_tsx.chunk.js 147 KiB [emitted] 1 related asset
web |   asset static/js/src_pages_Profile_ProfilePage_ProfilePage_tsx.chunk.js 147 KiB [emitted] 1 related asset
web |   + 5 assets
web | asset favicon.png 485 bytes [emitted] [from: public/favicon.png] [copied]
web | asset index.html 483 bytes [emitted]
web | asset robots.txt 24 bytes [emitted] [from: public/robots.txt] [copied]
web | Entrypoint app 4 MiB (3.66 MiB) = static/js/runtime-app.bundle.js 51.1 KiB static/js/app.bundle.js 3.95 MiB 2 auxiliary assets
web | orphan modules 1.16 MiB [orphan] 832 modules
web | runtime modules 34.3 KiB 19 modules
web | modules by path ../node_modules/ 4.41 MiB 1417 modules
web | modules by path ./src/ 617 KiB 90 modules
web | asset modules 1.02 KiB
web |   data:image/svg+xml,%3csvg xmlns=%27.. 284 bytes [built] [code generated]
web |   data:image/svg+xml,%3csvg viewBox=%.. 312 bytes [built] [code generated]
web |   data:image/svg+xml,%3csvg viewBox=%.. 181 bytes [built] [code generated]
web |   data:image/svg+xml,%3csvg xmlns=%27.. 271 bytes [built] [code generated]
web | modules by path ../api/src/lib/*.ts 46.9 KiB
web |   ../api/src/lib/gitlab.ts 18.7 KiB [built] [code generated]
web |   ../api/src/lib/gitlabAuth.ts 28.1 KiB [built] [code generated]
web | webpack 5.74.0 compiled successfully in 18074 ms
api | 11:29:35 🌲 incoming request POST xxx /graphql
api | 11:29:35 🐛 Parsing request to extract GraphQL parameters
api | (node:74475) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
api | (Use `node --trace-warnings ...` to show where the warning was created)
api | 11:29:35 🐛 Processing GraphQL Parameters
api | PrismaClientUnknownRequestError: Response from the Engine was empty
api |     at LibraryEngine.parseEngineResponse (/home/klampe/dev/slashskills/node_modules/@prisma/client/runtime/index.js:25389:13)
api |     at LibraryEngine.logger (/home/klampe/dev/slashskills/node_modules/@prisma/client/runtime/index.js:25440:24)
api |     at /home/klampe/dev/slashskills/node_modules/@prisma/client/runtime/index.js:25424:59 {
api |   clientVersion: '3.15.2'
api | }
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://[::1]:8911/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

Are there any needed manual steps to run the latest canary?

### How do we reproduce the bug?

I assume, just installing the canary via `yarn rw upgrade -t canary` and then running `yarn rw dev` should show this, maybe try to open the website.

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - /tmp/xfs-601c426a/node
    Yarn: 3.2.1 - /tmp/xfs-601c426a/yarn
  Databases:
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 104.0
  npmPackages:
    @redwoodjs/core: ^2.2.4-canary.284 => 2.2.4-canary.284+259fd7753
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dac09** [comment]
Could you please try `yarn rw prisma generate` and see if the error is still around?

**Comment by razzeee** [comment]
Thanks, that seems to have fixed it.

**Comment by dac09** [comment]
I'll add a note to the release notes, thanks.
