### ISSUE TITLE
[Chore]: @redwoodjs/cli tests are slow and sometimes cause timeouts

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#6451]
### What's not working?

The tests in the (internal) redwood cli package are slow - particularly for generate and destroy commands.

This is likely because the tests don't fully or correctly mock underlying functions (which do not affect the output of the test).

The best examples of this are the SDL and Scaffold generators, which internally call other generators. You will see Listr logs printed to the console (which indicates that something is off). 

Possible approaches to explore

A. Don't generate files in the `beforeAll` block, only run them in the describe/test block that is needed. This will make running things in parallel faster

B. For each of the slow test suites, make sure that if other generators are called, they are mocked (we are testing the current generator, not the other ones)

### How do we reproduce the bug?

1. `cd packages/cli`
2. `yarn test`

### What's your environment? (If it applies)
On a Mac you might not appreciate this as much, best way to see this for yourself is to run tests in Gitpod - which has limited power and memory. https://gitpod.io/#https://github.com/redwoodjs/redwood

### Are you interested in working on this?

- [x] I'm interested in working on this

**Comment by dac09** [comment]
I also think it's may be writing files to disk, see output while running test:

```
console.log
      [12:54:30] Writing `./api/src/graphql/users.sdl.js` [title changed]

      at Object.<anonymous>.exports.log (../../node_modules/listr/node_modules/listr-verbose-renderer/lib/utils.js:13:10)

    console.log
      [12:54:30] Successfully wrote file `./api/src/graphql/users.sdl.js` [title changed]

      at Object.<anonymous>.exports.log (../../node_modules/listr/node_modules/listr-verbose-renderer/lib/utils.js:13:10)

    console.log
      [12:54:30] Successfully wrote file `./api/src/graphql/users.sdl.js` [completed]

      at Object.<anonymous>.exports.log (../../node_modules/listr/node_modules/listr-verbose-renderer/lib/utils.js:13:10)

    console.log
      [12:54:30] ...waiting to write file `./api/src/services/users/users.scenarios.js`... [started]

      at Object.<anonymous>.exports.log (../../node_modules/listr/node_modules/listr-verbose-renderer/lib/utils.js:13:10)
```

**Comment by dac09** [comment]
Here's an incomplete list of tests from one of the CI runs that are slow:

```
  PASS  src/commands/generate/scaffold/__tests__/scaffoldPathMultiwordNoNest.test.js (22.395 s)
 PASS  src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js (22.145 s)
 PASS  src/commands/deploy/__tests__/baremetal.test.js
 PASS  src/commands/generate/scaffold/__tests__/scaffoldPathMulti.test.js (12.933 s)
 PASS  src/commands/generate/scaffold/__tests__/scaffoldPath.test.js (14.276 s)
 PASS  src/commands/generate/scaffold/__tests__/scaffoldPathMultiNoNest.test.js (14.829 s)
 PASS  src/commands/generate/scaffold/__tests__/scaffoldPathNoNest.test.js (13.066 s)
 PASS  src/commands/generate/cell/__tests__/cell.test.js (12.453 s)
 PASS  src/commands/generate/__tests__/helpers.test.js
 PASS  src/commands/generate/scaffold/__tests__/scaffold.test.js (15.508 s)
 PASS  src/commands/generate/service/__tests__/service.test.js (6.663 s)
 PASS  src/lib/__tests__/mergeConfig.test.js
 PASS  src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js (12.358 s)
 PASS  src/commands/destroy/scaffold/__tests__/scaffold.test.js
 PASS  src/commands/generate/page/__tests__/page.test.js (7.254 s)
 PASS  src/commands/generate/sdl/__tests__/sdl.test.js (
  PASS  src/commands/destroy/cell/__tests__/cell.test.js (8.73 s)
 PASS  src/commands/generate/scaffold/__tests__/editableColumns.test.js (5.799 s)
```
