### ISSUE TITLE
CLI tests not passing

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#648]
First thing first:

```
  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 13.8.0 - ~\AppData\Local\Temp\yarn--1591188855462-0.7127393367377759\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1591188855462-0.7127393367377759\yarn.CMD

  redwood: 01f42e804e0ee2eec2e17e9bea2939b0613b027c
```

These are the commands I run, with truncated test output

```
$ git clone https://github.com/redwoodjs/redwood.git .
$ yarn install
$ yarn build
$ yarn test
yarn run v1.22.4
$ lerna run test --stream -- --colors
lerna notice cli v3.22.0
lerna info Executing command in 5 packages: "yarn run test --colors"
$ yarn jest src --colors
$ jest --colors
$ C:\Users\tobbe\dev\redwood\rw-test\node_modules\.bin\jest src --colors
@redwoodjs/internal:  PASS  src/__tests__/config.test.ts
@redwoodjs/internal:  PASS  src/__tests__/paths.test.ts
@redwoodjs/internal: Test Suites: 2 passed, 2 total
@redwoodjs/internal: Tests:       3 passed, 3 total
@redwoodjs/internal: Snapshots:   1 passed, 1 total
@redwoodjs/internal: Time:        8.654s
@redwoodjs/internal: Ran all test suites.
$ yarn jest --colors
$ jest --colors
@redwoodjs/router:  PASS  src/__tests__/util.test.js
$ C:\Users\tobbe\dev\redwood\rw-test\node_modules\.bin\jest --colors
@redwoodjs/router:  PASS  src/__tests__/links.test.js (6.045s)
@redwoodjs/router: Test Suites: 2 passed, 2 total
@redwoodjs/router: Tests:       42 passed, 42 total
@redwoodjs/router: Snapshots:   0 total
@redwoodjs/router: Time:        10.427s
@redwoodjs/router: Ran all test suites matching /src/i.
@redwoodjs/api:  PASS  src/__tests__/importAll.macro.test.js (9.273s)
@redwoodjs/api:  PASS  src/__tests__/graphQLServer.test.ts (13.187s)
@redwoodjs/api:  PASS  src/makeMergedSchema/makeMergedSchema.test.ts (12.997s)
@redwoodjs/api: Test Suites: 3 passed, 3 total
@redwoodjs/api: Tests:       12 passed, 12 total
@redwoodjs/api: Snapshots:   2 passed, 2 total
@redwoodjs/api: Time:        20.28s
@redwoodjs/api: Ran all test suites.
@redwoodjs/cli:  FAIL  src/commands/generate/page/__tests__/page.test.js (18.683s)
@redwoodjs/cli:   ● creates a page component
@redwoodjs/cli:     expect(received).toEqual(expected) // deep equality
@redwoodjs/cli:     Expected: "const HomePage = () => {
@redwoodjs/cli:       return (
@redwoodjs/cli:         <div>
@redwoodjs/cli:           <h1>HomePage</h1>
@redwoodjs/cli:           <p>Find me in ./web/src/pages/HomePage/HomePage.js</p>
@redwoodjs/cli:         </div>
@redwoodjs/cli:       )
@redwoodjs/cli:     }·
@redwoodjs/cli:     export default HomePage
@redwoodjs/cli:     "
@redwoodjs/cli:     Received: undefined
@redwoodjs/cli:
@redwoodjs/cli:       18 |   expect(
@redwoodjs/cli:       19 |     singleWordFiles['/path/to/project/web/src/pages/HomePage/HomePage.js']
@redwoodjs/cli:     > 20 |   ).toEqual(loadGeneratorFixture('page', 'singleWordPage.js'))
@redwoodjs/cli:          |     ^
@redwoodjs/cli:       21 | })
@redwoodjs/cli:       22 |
@redwoodjs/cli:       23 | test('creates a page test', () => {
@redwoodjs/cli:
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/page/__tests__/page.test.js:20:5)
@redwoodjs/cli:   ● creates a page test
@redwoodjs/cli:     expect(received).toEqual(expected) // deep equality
@redwoodjs/cli:     Expected: "import { render, cleanup } from '@redwoodjs/testing'·
@redwoodjs/cli:     import HomePage from './HomePage'·
@redwoodjs/cli:     describe('HomePage', () => {
@redwoodjs/cli:       afterEach(() => {
@redwoodjs/cli:         cleanup()
@redwoodjs/cli:       })
@redwoodjs/cli:       it('renders successfully', () => {
@redwoodjs/cli:         expect(() => {
@redwoodjs/cli:           render(<HomePage />)
@redwoodjs/cli:         }).not.toThrow()
@redwoodjs/cli:       })
@redwoodjs/cli:     })
@redwoodjs/cli:     "
@redwoodjs/cli:     Received: undefined
@redwoodjs/cli:
@redwoodjs/cli:       24 |   expect(
@redwoodjs/cli:       25 |     singleWordFiles['/path/to/project/web/src/pages/HomePage/HomePage.test.js']
@redwoodjs/cli:     > 26 |   ).toEqual(loadGeneratorFixture('page', 'singleWordPage.test.js'))
@redwoodjs/cli:          |     ^
@redwoodjs/cli:       27 | })
@redwoodjs/cli:       28 |
@redwoodjs/cli:       29 | test('creates a page component', () => {
@redwoodjs/cli:
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/page/__tests__/page.test.js:26:5)
@redwoodjs/cli:   ● creates a page component
@redwoodjs/cli:     expect(received).toEqual(expected) // deep equality
@redwoodjs/cli:     Expected: "const ContactUsPage = () => {
@redwoodjs/cli:       return (
@redwoodjs/cli:         <div>
@redwoodjs/cli:           <h1>ContactUsPage</h1>
@redwoodjs/cli:           <p>Find me in ./web/src/pages/ContactUsPage/ContactUsPage.js</p>
@redwoodjs/cli:         </div>
@redwoodjs/cli:       )
@redwoodjs/cli:     }·
@redwoodjs/cli:     export default ContactUsPage
@redwoodjs/cli:     "
@redwoodjs/cli:     Received: undefined
@redwoodjs/cli:
@redwoodjs/cli:       32 |       '/path/to/project/web/src/pages/ContactUsPage/ContactUsPage.js'
@redwoodjs/cli:       33 |     ]
@redwoodjs/cli:     > 34 |   ).toEqual(loadGeneratorFixture('page', 'multiWordPage.js'))
@redwoodjs/cli:          |     ^
@redwoodjs/cli:       35 | })
@redwoodjs/cli:       36 |
@redwoodjs/cli:       37 | test('creates a page test', () => {
@redwoodjs/cli:
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/page/__tests__/page.test.js:34:5)

[...]

@redwoodjs/cli:     .rw-table-actions .rw-button-red:hover {
@redwoodjs/cli:       background-color: #e53e3e;
@redwoodjs/cli:       color: #fff;
@redwoodjs/cli:     }
@redwoodjs/cli:     .rw-text-center {
@redwoodjs/cli:       text-align: center;
@redwoodjs/cli:     }
@redwoodjs/cli:     "}
@redwoodjs/cli:
@redwoodjs/cli:       1055 |       })
@redwoodjs/cli:       1056 |
@redwoodjs/cli:     > 1057 |       expect(foreignKeyFiles).toHaveProperty([
@redwoodjs/cli:            |                               ^
@redwoodjs/cli:       1058 |         '/path/to/project/web/src/components/AdminPages/EditUserProfileCell/EditUserProfileCell.js',
@redwoodjs/cli:       1059 |       ])
@redwoodjs/cli:       1060 |     })
@redwoodjs/cli:
@redwoodjs/cli:       at Object.<anonymous> (src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js:1057:31)
@redwoodjs/cli: Test Suites: 12 failed, 11 passed, 23 total
@redwoodjs/cli: Tests:       266 failed, 109 passed, 375 total
@redwoodjs/cli: Snapshots:   0 total
@redwoodjs/cli: Time:        98.533s
@redwoodjs/cli: Ran all test suites.
error Command failed with exit code 1.
lerna ERR! yarn run test --colors exited 1 in '@redwoodjs/cli'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is this a Windows issue?

**Comment by Tobbe** [comment]
Duplicate of https://github.com/redwoodjs/redwood/issues/533

**Comment by thedavidprice** [comment]
Ah, so you've found our mess... `/hangs head in shame`

😉
