### ISSUE TITLE
[Bug?]: `yarn rw upgrade` fails without canary due to new auth packages 

### ISSUE THREAD

**Issue by Josh-Walker-GM** [redwoodjs/redwood#6762]
### What's not working?

Running `yarn rw upgrade` fails on a new test project:
```
✔ Checking latest version
✔ Updating your project package.json(s)
  ✔ Updating /home/josh/Development/redwood-test-project/package.json
  ✔ Updating /home/josh/Development/redwood-test-project/api/package.json
  ✔ Updating /home/josh/Development/redwood-test-project/web/package.json
✖ Could not finish installation. Please run `yarn install --force`, before continuing
◼ Refreshing the Prisma client
◼ De-duplicating dependencies
◼ One more thing..
Could not finish installation. Please run `yarn install --force`, before continuing
```
If you run `yarn install` you see the issue is:
```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @redwoodjs/auth-providers-api@npm:^3.2.1: No candidates found
    at ce (/home/josh/Development/redwood-test-project/.yarn/releases/yarn-3.2.3.cjs:439:7864)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 1)
    at async ho (/home/josh/Development/redwood-test-project/.yarn/releases/yarn-3.2.3.cjs:390:10446)
➤ YN0000: └ Completed in 2s 985ms
➤ YN0000: Failed with errors in 2s 988ms
```
This is simply because the new packages like `auth-providers-api` don't have any non-canary versions (see https://www.npmjs.com/package/@redwoodjs/auth-providers-api?activeTab=versions).

I raise the issue mainly just to document this as I'm sure this is only temporary while the new packages get implemented and then published. 

You can avoid this by switching to the canary via `yarn rw upgrade --tag=canary`

### How do we reproduce the bug?

Produce a new test project via `yarn build:test-project ../whatever-dir` and then run `yarn rw upgrade`

### What's your environment? (If it applies)

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 18.12.0 - /tmp/xfs-80474b97/node
  Yarn: 3.2.3 - /tmp/xfs-80474b97/yarn
npmPackages:
  @redwoodjs/core: ^3.2.1 => 3.2.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
> Could not finish installation. Please run `yarn install --force`, before continuing

I also think this error message suggestion might need an update? Following the advice results in:
```
Unknown Syntax Error: Unsupported option name ("--force").
```
This is related to the version of yarn the users uses? I haven't made any conscious choices to use a particular yarn version so I would imagine the default user might also receive the same message and resulting error that I do.

**Comment by Josh-Walker-GM** [comment]
Okay maybe I'm snowballing this issue beyond the intended temporary advisory...

I notice now that if the `yarn rw upgrade` command fails at the "Running yarn install" stage then it does not rollback the changes to the `package.json`'s.

I notice this here because if I run `yarn rw info` (as the bug issue template suggests) before I run the upgrade then I get the correct current version of my redwood project. If however I run the info command after the failed upgrade then I get the latest redwood version - because the changes to `package.json`'s are never reverted. This could maybe muddle up version reporting in issues where this occurs.

This isn't apocalyptic or anything but noteworthy for inclusion in future upgrade command improvements.

**Comment by Josh-Walker-GM** [comment]
I'll ping you @Tobbe just since it seems you're very active in the new auth stuff. Apologies if an unwelcome notification!

**Comment by Tobbe** [comment]
I just tried this and can confirm that it's working now that all auth packages have been properly published.
