### ISSUE TITLE
bug: `TypeError: Cannot redefine property: __RESOLVED_TMP_DIR__`

### ISSUE THREAD

**Issue by virtuoushub** [redwoodjs/redwood#6814]
Seeing some hard to reproduce locally test failures in GitHub actions.

`TypeError: Cannot redefine property: __RESOLVED_TMP_DIR__`

---

see also:
- https://community.redwoodjs.com/t/api-tests-fail-in-github-actions-but-pass-locally/4251
- https://discord.com/channels/679514959968993311/716252919875240007/1029853780033933452

---

```log
...
FAIL api api/src/services/comments/comments.test.js
  comments
    ✕ returns all comments for a single post from the database (5 ms)
    ✕ creates a new comment (6 ms)
    ✕ allows admins and moderators to delete a comment (4 ms)
    ✕ does not allow a non-moderator to delete a comment (4 ms)
    ✕ does not allow a logged out user to delete a comment (5 ms)

  ● comments › returns all comments for a single post from the database

    TypeError: Cannot redefine property: __RESOLVED_TMP_DIR__
        at Function.defineProperty (<anonymous>)

      at Object.get (node_modules/jest-environment-node/build/index.js:100:20)
      at Object.<anonymous> (node_modules/temp-write/node_modules/temp-dir/index.js:7:12)
      at Object.<anonymous> (node_modules/temp-write/index.js:8:17)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/engine-commands/queryEngineCommons.js:44:33)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/engine-commands/getConfig.js:43:33)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/engine-commands/index.js:29:24)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/index.js:120:25)
      at configureTeardown (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:35:23)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:225:11)

  ● comments › returns all comments for a single post from the database

    TypeError: Cannot redefine property: __RESOLVED_TMP_DIR__
        at Function.defineProperty (<anonymous>)

      at Object.get (node_modules/jest-environment-node/build/index.js:100:20)
      at Object.<anonymous> (node_modules/temp-write/node_modules/temp-dir/index.js:7:12)
      at Object.<anonymous> (node_modules/temp-write/index.js:8:17)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/engine-commands/queryEngineCommons.js:44:33)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/engine-commands/getConfig.js:43:33)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/engine-commands/index.js:29:24)
      at Object.<anonymous> (node_modules/@prisma/internals/dist/index.js:120:25)
      at getQuoteStyle (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:60:42)
      at teardown (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:139:28)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:237:11)
...
```

- https://github.com/redwoodjs/example-storybook/pull/194

_Originally posted by @virtuoushub in https://github.com/redwoodjs/redwood/issues/6438#issuecomment-1304857167_

---

_note:_ there is a workaround

Instead of: `- run: yarn rw test --no-watch`

```
 - run: yarn rw test api --no-watch
 - run: yarn rw test web --no-watch
```

**Comment by virtuoushub** [comment]
since there is a workaround, and I haven't seen this in a while; going to close this out. If we have better steps to reproduce in the future, will open a new issue and reference this if necissary.
