### ISSUE TITLE
[Bug?]:  API server fails due to ReferenceError in dist file

### ISSUE THREAD

**Issue by AlvaroPata** [redwoodjs/redwood#6908]
### What's not working?

When trying to run the developing server with `yarn rw dev api`, the server crashes due to the following error
```console
api | 12:09:10 🌲 Server listening at http://[::]:8911
api | /Users/alvaro_ffy/Code/RW_NEW/api/dist/services/assets/assets.js:29
api |   createAsset: () => createAsset,
api |                      ^
api | 
api | ReferenceError: Cannot access 'createAsset' before initialization
```

Looking at the file `api/src/services/assets/assets.js/` it looks like a hoisting error, since the `createAsset` function is an arrow function and it is indeed declared below the exports:
```js
var assets_exports = {};
__export(assets_exports, {
  Asset: () => Asset,
  asset: () => asset,
  assets: () => assets,
  createAsset: () => createAsset,
  deleteAsset: () => deleteAsset,
  updateAsset: () => updateAsset
});
```

This is the complete console log:
```console
❯ yarn rw dev api
gen | Generating TypeScript definitions and GraphQL schemas...
gen | 47 files generated
api | Building... Took 676 ms
api | Debugger listening on ws://127.0.0.1:18911/0c94ab6e-d155-4612-851a-db6545852b1d
api | For help, see: https://nodejs.org/en/docs/inspector
api | Starting API Server...
api | Loading server config from /Users/alvaro_ffy/Code/RW_NEW/api/server.config.js 
api | 
api | 12:09:10 🌲 Configuring api side 
api | 🗒 Custom
api | {
api |   "options": {
api |     "side": "api",
api |     "_": [
api |       "api"
api |     ],
api |     "port": 8911,
api |     "p": 8911,
api |     "apiRootPath": "/",
api |     "rootPath": "/",
api |     "root-path": "/",
api |     "api-root-path": "/",
api |     "$0": "node_modules/@redwoodjs/api-server/dist/index.js"
api |   }
api | }
api | Importing Server Functions... 
api | /auth 1 ms
api | Took 232 ms
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 12:09:10 🐛 Fastify server configuration 
api | 🗒 Custom
api | {
api |   "requestTimeout": 15000,
api |   "connectionTimeout": 0,
api |   "keepAliveTimeout": 72000,
api |   "maxRequestsPerSocket": 0,
api |   "requestIdHeader": "request-id",
api |   "requestIdLogLabel": "reqId",
api |   "disableRequestLogging": false,
api |   "bodyLimit": 1048576,
api |   "caseSensitive": true,
api |   "allowUnsafeRegex": false,
api |   "ignoreTrailingSlash": false,
api |   "ignoreDuplicateSlashes": false,
api |   "jsonShorthand": true,
api |   "maxParamLength": 100,
api |   "onProtoPoisoning": "error",
api |   "onConstructorPoisoning": "error",
api |   "pluginTimeout": 10000,
api |   "http2SessionTimeout": 72000,
api |   "exposeHeadRoutes": true
api | }
api | 12:09:10 🐛 Registered plugins 
api | bound root 226 ms
api | ├── bound _after 2 ms
api | ├── @fastify/url-data 0 ms
api | ├── fastify-raw-body 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | └── bound _after 0 ms
api | 
api | 12:09:10 🌲 Server listening at http://[::]:8911
api | /Users/alvaro_ffy/Code/RW_NEW/api/dist/services/assets/assets.js:29
api |   createAsset: () => createAsset,
api |                      ^
api | 
api | ReferenceError: Cannot access 'createAsset' before initialization
api |     at Object.createAsset (/Users/alvaro_ffy/Code/RW_NEW/api/dist/services/assets/assets.js:29:22)
api |     at Object.get [as createAsset] (/Users/alvaro_ffy/Code/RW_NEW/api/dist/services/assets/assets.js:15:45)
api |     at Object.<anonymous> (/Users/alvaro_ffy/Code/RW_NEW/api/src/utils/modelOperations.ts:134:13)
api |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api |     at Module._load (node:internal/modules/cjs/loader:878:12)
api |     at Module.require (node:internal/modules/cjs/loader:1061:19)
api |     at require (node:internal/modules/cjs/helpers:103:18)
api |     at Object.<anonymous> (/Users/alvaro_ffy/Code/RW_NEW/api/src/utils/index.ts:10:50)
api | 
api | Node.js v18.11.0
```

### How do we reproduce the bug?

I have a model `Asset`:

```prisma

model Asset {
  id          String       @id @default(cuid())
  name        String       @unique
  type        AssetType
  isPublic    Boolean      @default(false)
  longitude   Float
  latitude    Float
  geojson     Json
  values      AssetValue[]
  portfolio   Portfolio    @relation(fields: [portfolioId], references: [id], onDelete: Cascade)
  portfolioId String
  groups      Group[]
  project     Project?
}
```

The Services are nothing out of the ordinary, barely modified the generated ones.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.6
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /private/var/folders/8h/lnt630zn1t71xvyjq0n8353h0000gn/T/xfs-daf23eb5/node
    Yarn: 3.2.3 - /private/var/folders/8h/lnt630zn1t71xvyjq0n8353h0000gn/T/xfs-daf23eb5/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 106.0.5
    Safari: 16.0
  npmPackages:
    @redwoodjs/core: ^3.4.0 => 3.4.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by AlvaroPata** [comment]
It turns out the issue was caused by a circular import as mentioned here: https://github.com/webpack/webpack/issues/12724#issuecomment-817701622
