### ISSUE TITLE
yarn build:watch and yarn rwt copy:watch don't work together on Windows

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#701]
If I have both `yarn build:watch` and `yarn rwt copy:watch ../redwood` running at the same time, and then make a change in the Redwood Framework that causes `yarn build:watch` to try to rebuild I get the following error

```
@redwoodjs/cli: [nodemon] restarting due to changes...
@redwoodjs/cli: [nodemon] starting `yarn build`
@redwoodjs/cli: $ yarn build:js && yarn build:clean-dist
@redwoodjs/cli: $ yarn cross-env NODE_ENV=production yarn babel src -d dist --delete-dir-on-start --copy-files --no-copy-ignored
@redwoodjs/cli: $ C:\Users\tobbe\dev\redwood\redwood\node_modules\.bin\cross-env NODE_ENV=production yarn babel src -d dist --delete-dir-on-start --copy-files --no-copy-ignored
@redwoodjs/cli: $ C:\Users\tobbe\dev\redwood\redwood\node_modules\.bin\babel src -d dist --delete-dir-on-start --copy-files --no-copy-ignored
@redwoodjs/cli: Error: ENOTEMPTY: directory not empty, rmdir 'dist/commands/destroy/scaffold/__tests__'
@redwoodjs/cli:     at Object.rmdirSync (fs.js:865:3)
@redwoodjs/cli:     at deleteDir (C:\Users\tobbe\dev\redwood\redwood\node_modules\@babel\cli\lib\babel\util.js:143:19)
@redwoodjs/cli:     at C:\Users\tobbe\dev\redwood\redwood\node_modules\@babel\cli\lib\babel\util.js:137:9
@redwoodjs/cli:     at Array.forEach (<anonymous>)
@redwoodjs/cli:     at deleteDir (C:\Users\tobbe\dev\redwood\redwood\node_modules\@babel\cli\lib\babel\util.js:133:37)
@redwoodjs/cli:     at C:\Users\tobbe\dev\redwood\redwood\node_modules\@babel\cli\lib\babel\util.js:137:9
@redwoodjs/cli:     at Array.forEach (<anonymous>)
@redwoodjs/cli:     at deleteDir (C:\Users\tobbe\dev\redwood\redwood\node_modules\@babel\cli\lib\babel\util.js:133:37)
@redwoodjs/cli:     at C:\Users\tobbe\dev\redwood\redwood\node_modules\@babel\cli\lib\babel\util.js:137:9
@redwoodjs/cli:     at Array.forEach (<anonymous>) {
@redwoodjs/cli:   errno: -4051,
@redwoodjs/cli:   syscall: 'rmdir',
@redwoodjs/cli:   code: 'ENOTEMPTY',
@redwoodjs/cli:   path: 'dist/commands/destroy/scaffold/__tests__'
@redwoodjs/cli: }
@redwoodjs/cli: error Command failed with exit code 1.
@redwoodjs/cli: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@redwoodjs/cli: error Command failed with exit code 1.
@redwoodjs/cli: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@redwoodjs/cli: error Command failed with exit code 1.
@redwoodjs/cli: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@redwoodjs/cli: error Command failed with exit code 1.
@redwoodjs/cli: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@redwoodjs/cli: [nodemon] app crashed - waiting for file changes before starting...
```

If I stop `yarn rwt copy:watch` (Ctrl+C) and make a change to Redwood the rebuild works just fine

```
@redwoodjs/cli: [nodemon] restarting due to changes...
@redwoodjs/cli: [nodemon] starting `yarn build`
@redwoodjs/cli: $ yarn build:js && yarn build:clean-dist
@redwoodjs/cli: $ yarn cross-env NODE_ENV=production yarn babel src -d dist --delete-dir-on-start --copy-files --no-copy-ignored
@redwoodjs/cli: $ C:\Users\tobbe\dev\redwood\redwood\node_modules\.bin\cross-env NODE_ENV=production yarn babel src -d dist --delete-dir-on-start --copy-files --no-copy-ignored
@redwoodjs/cli: $ C:\Users\tobbe\dev\redwood\redwood\node_modules\.bin\babel src -d dist --delete-dir-on-start --copy-files --no-copy-ignored
@redwoodjs/cli: Successfully compiled 44 files with Babel (3228ms).
@redwoodjs/cli: $ yarn rimraf 'dist/**/__tests__'
@redwoodjs/cli: $ C:\Users\tobbe\dev\redwood\redwood\node_modules\.bin\rimraf 'dist/**/__tests__'
@redwoodjs/cli: [nodemon] clean exit - waiting for changes before restart
```

I suspect Windows is holding file locks differently compared to how it works in Linux/MacOS

Workaround for now is to just manually run `yarn rwt cp ../redwood` when needed.

**Comment by Tobbe** [comment]
@peterp I'm confused about the title change. I don't think there is a `yarn rwt build:watch` command, it's just `yarn build:watch`

**Comment by peterp** [comment]
@Tobbe No, no, it is I who is confused.

**Comment by jtoar** [comment]
@Tobbe assuming you use `yarn rwt link` somewhat successfully now? (And therefore okay to close this one out?)

**Comment by Tobbe** [comment]
I'm actually still using `yarn rwt cp` 🙈  (Also haven't been contributing much in a while. Will try `link` when I get back in to it)

But as long as RW still supports `cpw` and `build:watch` I think this is a valid issue.

If we feel like we're never going to fix this we should update our docs and say "Sorry, this doesn't work on Windows, please use link instead". (After making sure link works properly ofcourse (which it did when Danny and I tried several months ago, but a lot has changed since then))

**Comment by Tobbe** [comment]
Sure
