### ISSUE TITLE
[Bug?]: Overwrite auth provider setup with `yarn rw setup auth auth0 --force` fails (for any provider)

### ISSUE THREAD

**Issue by mc-spieczynski** [redwoodjs/redwood#7015]
### What's not working?

Reinstalling different auth provider (auth0 in this case) when an already configured provider is already installed.

```
$ yarn rw setup auth auth0 --force
(node:16464) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Generating auth lib...
  ✔ Successfully wrote file `./api\src\lib\auth.ts`
✔ Adding auth config to web...
✔ Adding auth config to GraphQL API...
⠋ Adding required web packages...
◼ Installing packages...
◼ One more thing...
...\node_modules\@redwoodjs\cli\dist\commands\setup\auth\auth.js:148
    throw new Error('Could not replace existing auth provider init');
          ^

Error: Could not replace existing auth provider init
    at removeOldAuthProvider (...\node_modules\@redwoodjs\cli\dist\commands\setup\auth\auth.js:148:11) 
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addConfigToApp (...\node_modules\@redwoodjs\cli\dist\commands\setup\auth\auth.js:208:15)  
```

### How do we reproduce the bug?

1. Create a RW setup with dbAuth provider.
2. Try to setup auth0 as a provider to replace existing one.

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.13.1 - ...\AppData\Local\Temp\xfs-fe9928b1\node.CMD
    Yarn: 3.2.1 - ...\AppData\Local\Temp\xfs-fe9928b1\yarn.CMD
  Browsers:
    Chrome: 107.0.5304.123
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.62)
  npmPackages:
    @redwoodjs/core: ^3.4.0 => 3.4.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
This is fixed in RW v4 which is in RC right now
