### ISSUE TITLE
yarn create redwood-app ./redwoodblog  error

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#739]
```

D:\workspace\www
λ node --version
v14.4.0

D:\workspace\www
λ yarn --version
1.22.4


D:\workspace\www
λ yarn create redwood-app ./redwoodblog
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-redwood-app@0.11.0" with binaries:
      - create-redwood-app
  > Creating Redwood app
    √ Creating directory 'D:\workspace\www\redwoodblog'
    × Downloading latest release
      → read ECONNRESET
      Extracting latest release
      Clean up
    Installing packages

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  config: {
    url: 'https://api.github.com/repos/redwoodjs/create-redwood-app/releases/latest',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: false,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/repos/redwoodjs/create-redwood-app/releases/latest',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.github.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/repos/redwoodjs/create-redwood-app/releases/latest'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /repos/redwoodjs/create-redwood-app/releases/latest HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: api.github.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/repos/redwoodjs/create-redwood-app/releases/latest',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://api.github.com/repos/redwoodjs/create-redwood-app/releases/latest',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function (anonymous)],
  context: [Object: null prototype] {}
}
error Command failed.
Exit code: 1
Command: C:\Users\admin\AppData\Local\Yarn\bin\create-redwood-app
Arguments: ./redwoodblog
Directory: D:\workspace\www
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.



```

**Comment by Tobbe** [comment]
@zwl1619 Did you try running it again? (So it wasn't just a temporary network connection glitch)
Can you access https://api.github.com/repos/redwoodjs/create-redwood-app/releases/latest in your browser?
Where are you running your commands? Is that Cmdr with a Cmd shell? If so, have you tried in Git Bash?

**Comment by zwl1619** [comment]
@Tobbe 
1、 I can access  https://api.github.com/repos/redwoodjs/create-redwood-app/releases/latest .
2、 I tried 4 times with `cmder` .

I try it with  Git Bash, the result is as follows. And I find the reason, I can't access `https://raw.githubusercontent.com`, but I don't know how to solve it.
```
admin@DESKTOP-0I3C62Q MINGW64 /d/workspace/www
$ yarn create redwood-app ./redwoodblog
  √ Creating Redwood app
    √ Creating directory 'D:\workspace\www\redwoodblog'
    √ Downloading latest release
    √ Extracting latest release
    √ Clean up
  > Installing packages
    √ Checking node and yarn compatibility
    × Running `yarn install`... (This could take a while)
      → info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error: Command failed with ENOENT: yarn install
spawn yarn install ENOENT
error An unexpected error occurred: "https://raw.githubusercontent.com/mcollina/undici/e5ec7ea989eef57a3456a005e7f5d945128b68e7/package.json: read ECONNRESET".
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "D:\\workspace\\www\\redwoodblog\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at notFoundError (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn yarn install',
  path: 'yarn install',
  spawnargs: [],
  originalMessage: 'spawn yarn install ENOENT',
  shortMessage: 'Command failed with ENOENT: yarn install\nspawn yarn install ENOENT',
  command: 'yarn install',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.4\n' +
    '[1/5] Validating package.json...\n' +
    '[2/5] Resolving packages...\n' +
    'info There appears to be trouble with your network connection. Retrying...\n' +
    'info There appears to be trouble with your network connection. Retrying...\n' +
    'info There appears to be trouble with your network connection. Retrying...\n' +
    'info There appears to be trouble with your network connection. Retrying...\n' +
    'info If you think this is a bug, please open a bug report with the information provided in "D:\\\\workspace\\\\www\\\\redwoodblog\\\\yarn-error.log".\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: 'error An unexpected error occurred: "https://raw.githubusercontent.com/mcollina/undici/e5ec7ea989eef57a3456a005e7f5d945128b68e7/package.json: read ECONNRESET".',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}
error Command failed.
Exit code: 1
Command: C:\Users\admin\AppData\Local\Yarn\bin\create-redwood-app
Arguments: ./redwoodblog
Directory: D:\workspace\www
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

**Comment by Tobbe** [comment]
You mean you can't access ttps://raw.githubusercontent.com/mcollina/undici/e5ec7ea989eef57a3456a005e7f5d945128b68e7/package.json ? Not even in your browser?

If that's the case, I'm afraid there is nothing Redwood can do about it

**Comment by thedavidprice** [comment]
@zwl1619 this seems frustrating -- sorry you're having trouble right out of the gate. And @Tobbe thanks for your help here!

As a workaround, you _can_ run a manual installation using the template repo for create-redwood-app. Instructions here:
https://community.redwoodjs.com/t/how-to-manually-bootstrap-install-create-redwood-app/115

I wrote that article awhile ago but it looks accurate. Let me know otherwise if you do give it a try.

**Comment by zwl1619** [comment]
I use a proxy, it works now. Thank you.
