### ISSUE TITLE
Scaffold generator not generating arrays for relations

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#741]
Similar to #740 it appears the SDL generator is not properly generating the array syntax for `@relation` fields.

```
model Farm {
  createdAt    DateTime    @default(now())
  id           Int         @id @default(autoincrement())
  Inventories  Inventory[] @relation(references: [id])
}
```

Is generating:

```
export const schema = gql`
  type Farm {
    createdAt: DateTime!
    id: Int!
    Inventories: Inventory  // <---
  }
```

When it should be:

```
export const schema = gql`
  type Farm {
    createdAt: DateTime!
    id: Int!
    Inventories: Inventory[]  // <---
  }
```

**Comment by Rosenberg96** [comment]
I believe this can be fixed by adding a check for `field.isList` (not entirely sure here, but the DMMF will specify the correct key) and adding `field[]`  to the `query` returned to be used in the template. See: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/sdl/sdl.js#L30.

```
return `${field.name}: ${field.type} ${field.isList ? '[]' : ''}
${field.isRequired && required ? '!' : ''}`
```

**Comment by cannikin** [comment]
@Rosenberg96 Thanks for tracking that down! That looks like it'll fix #740 as well!

**Comment by FiveBoroughs** [comment]
I just encountered the following issue :
```javascript
error GraphQLError: Syntax Error: Expected Name, found [
api |     at syntaxError ([...]/node_modules/graphql/error/syntaxError.js:15:10)
api |     at Parser.expectToken ([...]/node_modules/graphql/language/parser.js:1404:40)
api |     at Parser.parseName ([...]/node_modules/graphql/language/parser.js:94:22)
api |     at Parser.parseFieldDefinition ([...]/node_modules/graphql/language/parser.js:857:21)
api |     at Parser.optionalMany ([...]/node_modules/graphql/language/parser.js:1497:28)
api |     at Parser.parseFieldsDefinition ([...]/node_modules/graphql/language/parser.js:846:17)
api |     at Parser.parseObjectTypeDefinition ([...]/node_modules/graphql/language/parser.js:798:23)
api |     at Parser.parseTypeSystemDefinition ([...]/node_modules/graphql/language/parser.js:696:23)
api |     at Parser.parseDefinition ([...]/node_modules/graphql/language/parser.js:146:23)
api |     at Parser.many ([...]/node_modules/graphql/language/parser.js:1518:26) {
api |   message: 'Syntax Error: Expected Name, found [',
api |   locations: [ { line: 8, column: 14 } ]
api | }
```
Using the generator on a relation similar to your example, many to many:
```graphql
model Post {
  id         Int        @default(autoincrement()) @id
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @default(now())
  author     User       @relation(fields: [authorId], references: [id])
  authorId   Int
  tags       Tag[]      @relation(references: [id])
}
model Tag {
  id          Int       @default(autoincrement()) @id
  name        String
  posts       Post[]    @relation(references: [id])
}
```
Generated the following SDL
```javascript
  type Post {
    id: Int!
    createdAt: DateTime!
    updatedAt: DateTime!
    author: User!
    authorId: Int!
    tags: Tag[]
}
```

Commenting the line `tags: Tag[]` removes the error, but it was hard to trace.

Shouldn't the syntax be `tags: [Tag]` instead ?
Or is it because I need to import the Tag type ?

**Comment by Rosenberg96** [comment]
@FiveBoroughs, you are correct. I am sorry. I will correct this asap. 

@cannikin see #772

**Comment by cannikin** [comment]
Whoops! That one was my fault!
