### ISSUE TITLE
[Bug?]: GraphQL Requests Fail with RedwoodJS v.4.2.0

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#7691]
### What's not working?

With v4.2.0 or current canary, GraphQL requests fail:

```
api | 12:11:03 🚨 Cannot read properties of undefined (reading 'toUpperCase') 
api | 
api | 🚨 TypeError Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | TypeError: Cannot read properties of undefined (reading 'toUpperCase')
api |     at onRequest (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/plugins/useCORS.js:111:32)
api |     at YogaServer.getResponse (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/server.js:296:23)
api |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api |     at async YogaServer.handle (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/server.js:42:34)
api |     at async handlerFn (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)
api |     at async execFn (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)
api |     at async requestHandler (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)
api | 
api | 12:11:03 🌲 request completed 12ms
api | 12:11:03 🚨 Cannot read properties of undefined (reading 'toUpperCase') 
api | 
api | 🚨 TypeError Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | TypeError: Cannot read properties of undefined (reading 'toUpperCase')
api |     at onRequest (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/plugins/useCORS.js:111:32)
api |     at YogaServer.getResponse (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/server.js:296:23)
api |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api |     at async YogaServer.handle (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/server.js:42:34)
api |     at async handlerFn (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)
api |     at async execFn (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)
api |     at async requestHandler (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)
api | 
api | 12:11:03 🚨 Cannot read properties of undefined (reading 'get') 
api | 
api | 🚨 TypeError Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | TypeError: Cannot read properties of undefined (reading 'get')
api |     at getMediaTypesForRequestInOrder (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/plugins/resultProcessor/accept.js:5:38)
api |     at onResultProcess (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/plugins/useResultProcessor.js:39:86)
api |     at processResult (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/process-request.js:10:15)
api |     at YogaServer.getResponse (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/server.js:356:71)
api |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api |     at async YogaServer.handle (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/graphql-yoga/cjs/server.js:42:34)
api |     at async handlerFn (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)
api |     at async execFn (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)
api |     at async requestHandler (/Users/dthyresson/Dropbox/Code/throwaways/test42canary/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)
api | 
```

"Something" about the request headers and/or method is undefined.

```
// graphql function
    cors: request => {
      const requestOrigin = request.headers.get('origin');
      return (0, _cors.mapRwCorsOptionsToYoga)(cors, requestOrigin);
    }
```

```
//useCors
   return {
        onRequest({ request, fetchAPI, endResponse }) {
            if (request.method.toUpperCase() === 'OPTIONS') {
                const response = new fetchAPI.Response(null, {
                    status: 204,
                    // Safari (and potentially other browsers) need content-length 0,
                    // for 204 or they just hang waiting for a body
                    // see: https://github.com/expressjs/cors/blob/master/lib/index.js#L176
                    headers: {
                        'Content-Length': '0',
                    },
                });
                endResponse(response);
            }
        },
   ```

### How do we reproduce the bug?

1. Create a new app with 4.2 (or build test project): yarn create redwood-app app --ts 
2. yarn rw dev

### What's your environment? (If it applies)

```shell
OSX
Node v18.14.1
RW 4.2.0

Same behavior on Chrome and Safari
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
It appears that upgrading GraphQL Yoga to 3.7 resolves the issue.

**Comment by shivghai** [comment]
seeing this for 4.0.0 too (ran `yarn rw upgrade -t 4.0.0` + `rm -rf node_modules && rm yarn.lock` after upgrade to 4.2.0 was failing)

**Comment by twodotsjeremy** [comment]
It looks like it's locked to 3.5.1 in the graph-server package

https://github.com/redwoodjs/redwood/blob/main/packages/graphql-server/package.json#L39

**Comment by dthyresson** [comment]
> It looks like it's locked to 3.5.1 in the graphql-server package
> 
> https://github.com/redwoodjs/redwood/blob/main/packages/graphql-server/package.json#L39
> 
> I'm still seeing the error after upgrading graphql-yoga to 3.7.0, but in the stacktrace it seems to be referencing 3.5.1

Correct. @jtoar has it queued up for a version change.

I believe you can force resolution to 3.7 but Dom can explain.

Apologies for the mismatch

**Comment by wizztjh** [comment]
same error here.
graphql-yoga: 3.5.1 too in yarn.lock

https://gist.github.com/wizztjh/2864265a335a14aa8a00d47d17198faa

**Comment by twodotsjeremy** [comment]
For a workaround:

Make sure you're on yarn 3. Resolutions are a newer feature.

`yarn set version 3.2.0`

```
yarn -v
yarn add graphql-yoga@3.7.0 -E
yarn set resolution graphql-yoga@npm:3.5.1 3.7.0
```

**Comment by wizztjh** [comment]
it works! Thanks!

**Comment by jtoar** [comment]
This has been fixed in https://github.com/redwoodjs/redwood/releases/tag/v4.2.1; please just upgrade to that version (v4.2.1) and undo the changes to yarn resolutions if you made them

**Comment by esteban-url** [comment]
lol, just scrapped my hard drive thinking it was something in my setup, i just assumed I'd really messed it up because I'd been pretty reckless lately 😆💀🫣

at least i have a ✨sparking clean✨ env now!
