### ISSUE TITLE
Scaffold generated wrong sdl 

### ISSUE THREAD

**Issue by redstab** [redwoodjs/redwood#808]
Scaffold generator produces faulty sdl. Arrays are inproper.

### Versions
`yarn rw --version => 0.12.0`
`yarn -v => 1.22.4`
`node -v => 12.16.1`

### Recreation steps 

`yarn create redwood-app app`

**Edit api/prisma/schema.prisma**

Change datasource provider from 'sqlite' to 'postgresql'

Replace UserExample with

```
model Person {
  id Int @id @default(autoincrement())
  names String[]
}
```
Run `yarn rw g scaffold Person`

Check the file api/src/graphql/people.sdl.js 

**Expectation** 

```
import gql from 'graphql-tag'

export const schema = gql`
  type Person {
    id: Int!
    names: [String]
  }
...
```

**Observed**

```
import gql from 'graphql-tag'

export const schema = gql`
  type Person {
    id: Int!
    names: String[]
  }
...
```

**Consequence** 
`yarn rw dev api` fails to run and produces this error => 
```yarn run v1.22.4
$ X:\git\app1\node_modules\.bin\rw dev api
$ X:\git\app1\node_modules\.bin\dev-server
api | Running at 'http://localhost:8911'
api | Watching files in 'X:\git\app1\api\src\functions'
api | error GraphQLError: Syntax Error: Expected Name, found [
api |     at syntaxError (X:\git\app1\node_modules\graphql\error\syntaxError.js:15:10)
api |     at Parser.expectToken (X:\git\app1\node_modules\graphql\language\parser.js:1404:40)
api |     at Parser.parseName (X:\git\app1\node_modules\graphql\language\parser.js:94:22)
api |     at Parser.parseFieldDefinition (X:\git\app1\node_modules\graphql\language\parser.js:857:21)
api |     at Parser.optionalMany (X:\git\app1\node_modules\graphql\language\parser.js:1497:28)
api |     at Parser.parseFieldsDefinition (X:\git\app1\node_modules\graphql\language\parser.js:846:17)
api |     at Parser.parseObjectTypeDefinition (X:\git\app1\node_modules\graphql\language\parser.js:798:23)
api |     at Parser.parseTypeSystemDefinition (X:\git\app1\node_modules\graphql\language\parser.js:696:23)
api |     at Parser.parseDefinition (X:\git\app1\node_modules\graphql\language\parser.js:146:23)
api |     at Parser.many (X:\git\app1\node_modules\graphql\language\parser.js:1518:26) {
api |   message: 'Syntax Error: Expected Name, found [',
api |   locations: [ { line: 4, column: 18 } ]
api | }
api | 
api | GraphQLError: Syntax Error: Expected Name, found [
api |
api |
api | 1 syntaxError
api |   X:\git\app1\node_modules\graphql\error\syntaxError.js:15
api |
api | 2 Parser.expectToken
api |   X:\git\app1\node_modules\graphql\language\parser.js:1404
api |
api | 3 Parser.parseName
api |   X:\git\app1\node_modules\graphql\language\parser.js:94
api |
api | 4 Parser.parseFieldDefinition
api |   X:\git\app1\node_modules\graphql\language\parser.js:857
api |
api | 5 Parser.optionalMany
api |   X:\git\app1\node_modules\graphql\language\parser.js:1497
api |
api | 6 Parser.parseFieldsDefinition
api |   X:\git\app1\node_modules\graphql\language\parser.js:846
api |
api | 7 Parser.parseObjectTypeDefinition
api |   X:\git\app1\node_modules\graphql\language\parser.js:798
api |
api | 8 Parser.parseTypeSystemDefinition
api |   X:\git\app1\node_modules\graphql\language\parser.js:696
api |
api | 9 Parser.parseDefinition
api |   X:\git\app1\node_modules\graphql\language\parser.js:146
api |
api | 10 Parser.many
api |   X:\git\app1\node_modules\graphql\language\parser.js:1518
api |

```

**User Solution** 
Replace all the faulty field types. Ex String[] to [String]

**My Solution**
Change modelFieldToSDL("node_modules\@redwoodjs\cli\dist\commands\generate\sdl\sdl.js") from this
```
const modelFieldToSDL = (field, required = true, types = {}) => {
  if ((0, _entries.default)(types).length) {
    field.type = field.kind === 'object' ? idType(types[field.type]) : field.type;
  }

  return `${field.name}: ${field.type}${field.isList ? '[]' : ''}${field.isRequired && required ? '!' : ''}`;
};

```
To this 
```
const modelFieldToSDL = (field, required = true, types = {}) => {
  if ((0, _entries.default)(types).length) {
    field.type = field.kind === 'object' ? idType(types[field.type]) : field.type;
  }

  return `${field.name}: ${field.isList ? '[' : ''}${field.type}${field.isList ? ']' : ''}${field.isRequired && required ? '!' : ''}`;
};
```
Then everything works as expected. 

I hope I have given you everything to fix this issue

**Comment by jtoar** [comment]
@redstab Thanks for such a thorough issue :rocket: having all the details down here like this really helps. We actually got this one fixed in #772, but just haven't had time to cut a new release including it yet. Expect it soon!
