### ISSUE TITLE
Tests timeout

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#838]
Running the tests for redwood core (`yarn test`) I often get a bunch of timeout errors, like these:

```
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › returns exactly 16 files
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
@redwoodjs/cli:       at mapper (../../node_modules/jest-cli/node_modules/jest-jasmine2/build/queueRunner.js:29:45)
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › creates a layout
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
@redwoodjs/cli:       at mapper (../../node_modules/jest-cli/node_modules/jest-jasmine2/build/queueRunner.js:29:45)
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › creates a edit page
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
@redwoodjs/cli:       at mapper (../../node_modules/jest-cli/node_modules/jest-jasmine2/build/queueRunner.js:29:45)
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › the edit page correctly imports the edit cell
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
@redwoodjs/cli:       at mapper (../../node_modules/jest-cli/node_modules/jest-jasmine2/build/queueRunner.js:29:45)
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › creates a index page
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
@redwoodjs/cli:       at mapper (../../node_modules/jest-cli/node_modules/jest-jasmine2/build/queueRunner.js:29:45)
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › the index page correctly imports the index cell
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
@redwoodjs/cli:       at mapper (../../node_modules/jest-cli/node_modules/jest-jasmine2/build/queueRunner.js:29:45)
@redwoodjs/cli:   ● admin/post › creates the correct files with the correct imports › creates a new page
@redwoodjs/cli:     Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.
@redwoodjs/cli:
```

Is this a Windows issue? Or just my computer?
If I re-run the tests they usually don't timeout.

Am I the only one seeing this? Is it worth increasing the timeout from 5 seconds to something like 30 seconds?

**Comment by thedavidprice** [comment]
@Tobbe I've seen this as well on my (older) Mac when I have several processes running at once. 

I'm not sure about jumping to 30 but maybe try bumping to 10?

**Comment by Tobbe** [comment]
Tried 10, but that didn't do it. Had to increase to 15
