### ISSUE TITLE
[Bug]: Prerendering the root path breaks hard refreshes on non-prerendered pages on Netlify

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#8386]
### What's not working?

```jsx
const Routes = () => {
  return (
    <Router useAuth={useAuth}>
      <Route path="/pricing" page={PricingPage} name="pricing" />
      <Route path="/login" page={LoginPage} name="login" prerender />
      <Route path="/" page={HomePage} name="home" prerender />
  // ...
```

Cmd+Shift+R works on the root path, `/` (i.e. the home page). It also works on `/login`.
Cmd+Shift+R breaks on `/pricing`

```
caught TypeError: Cannot read properties of undefined (reading 'call')
    at c (runtime-app.0f51d3c3.js:1:157)
    at Object.prerenderLoader (app.c9f44c15.js:2:120997)
    at t.ActiveRouteLoader (app.c9f44c15.js:2:173873)
    at _a (app.c9f44c15.js:2:635427)
    at _u (app.c9f44c15.js:2:692259)
    at wc (app.c9f44c15.js:2:681411)
    at gc (app.c9f44c15.js:2:681339)
    at yc (app.c9f44c15.js:2:681202)
    at ic (app.c9f44c15.js:2:676338)
    at k (app.c9f44c15.js:172:15448)

p.c9f44c15.js:2 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _u (app.c9f44c15.js:2:693623)
    at wc (app.c9f44c15.js:2:681411)
    at gc (app.c9f44c15.js:2:681339)
    at yc (app.c9f44c15.js:2:681202)
    at ac (app.c9f44c15.js:2:678009)
    at ic (app.c9f44c15.js:2:676564)
    at k (app.c9f44c15.js:172:15448)
    at MessagePort.A (app.c9f44c15.js:172:15980)
```

It all works fine using both `yarn rw dev` and `yarn rw serve` locally. But it breaks when deployed to Netlify

### How do we reproduce the bug?

Create an app with routes like in the description above

Deploy to Netlify

Refresh the pages and look in the dev console

### What's your environment? (If it applies)

```shell
  System:
    OS: macOS 12.6
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /private/var/folders/w7/hkfhzp4x68qcbr1ggchr7hx40000gn/T/xfs-2f7ba553/node
    Yarn: 3.5.0 - /private/var/folders/w7/hkfhzp4x68qcbr1ggchr7hx40000gn/T/xfs-2f7ba553/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.35
    Firefox: 106.0.3
    Safari: 16.0
  npmPackages:
    @redwoodjs/auth-supabase-setup: 5.2.1 => 5.2.1 
    @redwoodjs/core: 5.2.1 => 5.2.1
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Tobbe** [comment]
This turned out to be an issue with Netlify redirect rules from old RW projects. Fresh projects have correct config for Netlify.

Old (broken)
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

New (working)
```
[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200
```
