### ISSUE TITLE
[Bug?]: Not being logged out and redirected to login route after Azure JWT expires (only status 500 error)

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#8499]
### What's not working?

This is connected to #6197, as we're also seeing a status code 500 – however that issue is concerned with the API side only.

We have a working RedwoodJS application that used in an Azure auth setup. Apparently, after some time the Azure login expires and all graphql requests start coming back as follows (where `…` is an abbreviation for the absolute project root folder):

```json
{
  "errors":[{
    "message":"Something went wrong.",
    "extensions":{
      "originalError":{
        "message":"Exception in getAuthenticationContext: jwt expired",
        "stack":"Error: Exception in getAuthenticationContext: jwt expired\n    at onContextBuilding (…/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodAuthContext.js:30:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.contextFactory (…/node_modules/@envelop/core/cjs/orchestrator.js:198:45)\n    at async processRequest (…/node_modules/graphql-yoga/cjs/process-request.js:40:26)\n    at async YogaServer.getResultForParams (…/node_modules/graphql-yoga/cjs/server.js:265:26)\n    at async YogaServer.getResponse (…/node_modules/graphql-yoga/cjs/server.js:331:23)\n    at async YogaServer.handle (…/node_modules/graphql-yoga/cjs/server.js:41:34)\n    at async handlerFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)\n    at async execFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)"
        }
      }
    }
  ]
}
```

On the console we can see:
```terminal
api | 14:35:40 🌲 incoming request POST xxx /graphql
api | 14:35:40 🐛 Parsing request to extract GraphQL parameters
api | 14:35:40 🐛 Processing GraphQL Parameters
api | 14:35:40 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: jwt expired
api | 14:35:40 🌲 request completed 372ms
api | 14:35:40 🚨 Exception in getAuthenticationContext: jwt expired 
api | 
api | 🚨 Error Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | Error: Exception in getAuthenticationContext: jwt expired
api |     at onContextBuilding (…/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodAuthContext.js:30:15)
api |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
api |     at async Object.contextFactory (…/node_modules/@envelop/core/cjs/orchestrator.js:198:45)
api |     at async processRequest (…/node_modules/graphql-yoga/cjs/process-request.js:40:26)
api |     at async YogaServer.getResultForParams (…/node_modules/graphql-yoga/cjs/server.js:265:26)
api |     at async YogaServer.getResponse (…/node_modules/graphql-yoga/cjs/server.js:331:23)
api |     at async YogaServer.handle (…/node_modules/graphql-yoga/cjs/server.js:41:34)
api |     at async handlerFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)
api |     at async execFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)
api |     at async requestHandler (…/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)
api | 
```

Our expectation would be that the redwood stack would redirect the user to the login route, but instead it only renders the `Failure`-component of the current cell.

The `Failure`-component receives the following error:

```json
ApolloError: Response not successful: Received status code 500
    at new ApolloError (index.js:29:1)
    at QueryManager.js:654:1
    at both (asyncMap.js:16:1)
    at asyncMap.js:9:1
    at new Promise (<anonymous>)
    at Object.then (asyncMap.js:9:1)
    at Object.error (asyncMap.js:17:1)
    at notifySubscription (module.js:137:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.error (module.js:229:1)
```

Everything else in the application also still behaves as if the user was still logged in – `useAuth().isAuthenticated` is still true and `currentUser.preferred_username` is still populated. From my understanding, at least `isAuthenticated` would need to become `false` at this point (or maybe the refresh token flow can be triggered in the background?).

---

In one occasion where we could reproduce this error, a few minutes after the above errors were shown it changed to this:

```json
{
  "errors":[{
    "message":"Something went wrong.",
    "extensions":{
      "originalError":{
        "message":"Exception in getAuthenticationContext: error in secret or public key callback: getaddrinfo EAI_AGAIN login.microsoftonline.com",
        "stack":"Error: Exception in getAuthenticationContext: error in secret or public key callback: getaddrinfo EAI_AGAIN login.microsoftonline.com\n    at onContextBuilding (…/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodAuthContext.js:30:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.contextFactory (…/node_modules/@envelop/core/cjs/orchestrator.js:198:45)\n    at async processRequest (…/node_modules/graphql-yoga/cjs/process-request.js:40:26)\n    at async YogaServer.getResultForParams (…/node_modules/graphql-yoga/cjs/server.js:265:26)\n    at async YogaServer.getResponse (…/node_modules/graphql-yoga/cjs/server.js:331:23)\n    at async YogaServer.handle (…/node_modules/graphql-yoga/cjs/server.js:41:34)\n    at async handlerFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)\n    at async execFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)\n    at async requestHandler (…/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)"
      }
    }
  }]
}
```

… with the console showing:

```terminal
api | 15:14:21 🌲 incoming request POST xxx /graphql
api | 15:14:21 🐛 Parsing request to extract GraphQL parameters
api | 15:14:21 🐛 Processing GraphQL Parameters
api | 15:14:21 🌲 request completed 69ms
api | 15:14:21 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: error in secret or public key callback: getaddrinfo EAI_AGAIN login.microsoftonline.com
api | 15:14:21 🚨 Exception in getAuthenticationContext: error in secret or public key callback: getaddrinfo EAI_AGAIN login.microsoftonline.com 
api | 
api | 🚨 Error Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | Error: Exception in getAuthenticationContext: error in secret or public key callback: getaddrinfo EAI_AGAIN login.microsoftonline.com
api |     at onContextBuilding (…/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodAuthContext.js:30:15)
api |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
api |     at async Object.contextFactory (…/node_modules/@envelop/core/cjs/orchestrator.js:198:45)
api |     at async processRequest (…/node_modules/graphql-yoga/cjs/process-request.js:40:26)
api |     at async YogaServer.getResultForParams (…/node_modules/graphql-yoga/cjs/server.js:265:26)
api |     at async YogaServer.getResponse (…/node_modules/graphql-yoga/cjs/server.js:331:23)
api |     at async YogaServer.handle (…/node_modules/graphql-yoga/cjs/server.js:41:34)
api |     at async handlerFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:178:24)
api |     at async execFn (…/node_modules/@redwoodjs/graphql-server/dist/functions/graphql.js:233:16)
api |     at async requestHandler (…/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)
```

---

Sidenote: Unfortunately, at this point we're unable to distinct this error on the web side from other status 500 errors that theoretically could happen. I've seen that there is a new prop introduced on the `Failure`-component in Redwood 5.x – but as we have too many moving parts in our current sprint we're currently unable to update in order to test that. If anybody can advice how to intercept the earlier graphQL error above and handle it accordingly before (or within) the `Failure` component render …  – then we could at least implement a workaround for the time being by simply checking for "jwt expired" in the error message and redirecting the user in our web side code. 

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.1 Manjaro Linux
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - /tmp/xfs-5336f285/node
    Yarn: 3.2.1 - /tmp/xfs-5336f285/yarn
  Databases:
    SQLite: 3.41.2 - /usr/bin/sqlite3
  Browsers:
    Firefox: 113.0
  npmPackages:
    @redwoodjs/auth-azure-active-directory-setup: 4.1.0-canary.592 => 4.1.0-canary.592+960724a08 
    @redwoodjs/core: ^4.1.0-canary.592 => 4.1.0-canary.592+960724a08
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Philzen** [comment]
Since the change to Azure login in our app we're observing that there seems to be a completely new auth context for every new browser tab. One has to log in again in every new tab being opened (while already existing tabs keep their auth status). This was quite different from the way it worked when the app was still dbAuth based – once you were logged in, you were also logged in in every other or new tab – once you log out in any tab, you were unable to visit anything requiring authentication in all others. This is also the default behaviour one would expect from any web app out there, but i'm not sure if this is simply an "Azure thing".

At least it's a big annoyance for reproducabilty of this bug, b/c otherwise one could just have one tab open and try to log out in another one … which was at least my hope would trigger this issue.

**Comment by jtoar** [comment]
Hey @Philzen thanks for taking the time to report, sorry this one got lost—I'll get some eyes on it this week.

**Comment by cmberard** [comment]
> Since the change to Azure login in our app we're also observing that there seems something like a completely new auth context for every new browser tab.

The fix for this is the cache config you provide `msal-browser` when creating your new PublicClientApplication. You need to set the cacheLocation to local storage, so that the tokens can be shared across browser windows...

```
auth: {
  clientId: ...,
  authority: ...,
  redirectUri: ...,
  postLogoutRedirectUri: ...,
},
cache: {
    cacheLocation: 'localStorage',
}
```

**Comment by cmberard** [comment]
As to the 500 error, we're seeing the same thing - 500 errors when tokens expire. It seems like the error is being thrown by `useRedwoodAuthContext` here:

```
      try {
        authContext = await getAuthenticationContext({
          authDecoder,
          event: context.event,
          context: requestContext,
        })
      } catch (error: any) {
        throw new Error(
          `Exception in getAuthenticationContext: ${error.message}`
        )
      }
```

If this handler were to throw an AuthenticationError rather than a generic error, perhaps it would be easier to handle?

**Comment by cdubz** [comment]
This also impacts custom auth decoders. We've got a custom decode that we try to throw a `401` from if the token is invalid (decryption fails) but this always get caught by `useRedwoodAuthContext` and re-thrown as a `500`.

**Comment by Tobbe** [comment]
@cdubz Sorry you're having problems with our auth implementation. Sounds like we need to figure out a way to give our uses more control over the error handling here.

We're currently in the process of rewriting our auth logic to make it work with Streaming/SSR and React Server Components. We'll try to improve the behavior here while we work on the rewrite. Thanks for reporting!

**Comment by cdubz** [comment]
Thanks, @Tobbe! Looks like there are a couple different use cases to consider here so happy to hear it's being looked at. Let me know if you would like any more info about what we are doing or how. The basic context is that we wrote a custom auth implementation that sits alongside `dbAuth` providing API key auth for frontends where there is no "user" but API access restrictions are needed.

**Comment by Tobbe** [comment]
> The basic context is that we wrote a custom auth implementation that sits alongside `dbAuth` providing API key auth for frontends where there is no "user" but API access restrictions are needed.

That's awesome! This is exactly one of the use cases for custom auth that we wanted to support, so definitely want to remove any obstacles you're facing. 

I think it would be very valuable to the RW community if you wanted to do a writeup on how you implemented your API key auth on our [forums](https://community.redwoodjs.com)
