### ISSUE TITLE
[Bug?]: dbAuth authentication fails with "Request path contains unescaped characters" error

### ISSUE THREAD

**Issue by arioberek** [redwoodjs/redwood#8861]
### What's not working?

I'm using dbAuth and when I try to authenticate I get this error:

```
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
```

It is also returned as response on the /auth API call

<img width="766" alt="image" src="https://github.com/redwoodjs/redwood/assets/25717193/02b5c9ca-1ad9-4424-a84b-693cbc3ffb2d">

### How do we reproduce the bug?

1. I've set up a User model in Prisma with the following schema:

```
model User {
  id                  String    @id @default(cuid())
  name                String
  email               String    @unique
  webAuthnChallenge   Boolean?  @default(true)
  hashedPassword      String
  salt                String
  resetToken          String?
  resetTokenExpiresAt DateTime?
}
```

2. I attempt to log in using a valid user's email and password.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /private/var/folders/dw/x4gbys1s7hg5vlyndgyyt5_h0000gn/T/xfs-929188dd/node
    Yarn: 3.2.1 - /private/var/folders/dw/x4gbys1s7hg5vlyndgyyt5_h0000gn/T/xfs-929188dd/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Safari: 16.5.1
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 5.4.2 => 5.4.2 
    @redwoodjs/auth-dbauth-web: 5.4.2 => 5.4.2 
    @redwoodjs/core: 5.4.2 => 5.4.2 
    @redwoodjs/studio: 5.4.2 => 5.4.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by arioberek** [comment]
Hey @Josh-Walker-GM, thank you for your swift response!

I attempted to log in using a regular email format, for example: `name@email.com`. Additionally, I used a test password that includes symbols, numbers, and letters, similar to a UUID.

I also tried using the unique email address you provided in your response and encountered the same `TypeError: Request path contains unescaped characters` error.

**Comment by Josh-Walker-GM** [comment]
Thanks for that @arioberek. I updated my test project to use the `cuid` too and noticed I had to update the `getCurrentUser` function - just want to check that's something you did too?

Could you check the browser console and see what network request is failing? That will likely be helpful for me to know. I'm wondering if it's perhaps that the login is working fine but that then the redirect to a different route afterwards might be failing. Just an idea I'm not sure.

**Comment by arioberek** [comment]
I've not modified the `getCurrentUser` function in any way. Here's the current implementation for reference:

```javascript
export const getCurrentUser = async (session: Decoded) => {
  return await db.user.findUnique({
    where: { id: session.id as string },
    select: { id: true, email: true, name: true },
  })
}
```

As for the issue with the failed request, it seems to be associated with the authentication process (auth). The browser console presents the following error messages:

<img width="569" alt="image" src="https://github.com/redwoodjs/redwood/assets/25717193/bb59f6ca-fd6c-4661-8c86-4998d73a3014">

At this point, I'm uncertain if this could be a repercussion of the cuid update or if there's a problem with the login redirect mechanism. Any guidance on this would be deeply appreciated. Also, would making adjustments to the getCurrentUser function potentially resolve this issue? Thank you for your assistance.

**Comment by Josh-Walker-GM** [comment]
So with our test project the generated code inside `lib/auth.ts` looked like so:
![image](https://github.com/redwoodjs/redwood/assets/56300765/364c80b9-0fa1-416f-a83f-a7ad2f28fa3e)
where I have modified the highlighted code to ensure that the session id is a string rather than a number - since we now have a cuid.

I also assume you updated the sdl for the user to have `id: String!` rather than the standard `Int!`.

I don't have any specific hunches as to what this could be. My main recommendation would be to add that check to ensure the session is valid and confirm you don't see that error. Then I would simply add a few console logs to confirm everything looks sensible. Something like:
```ts
export const getCurrentUser = async (session: Decoded) => {
  if (!session || typeof session.id !== 'string') {
    throw new Error('Invalid session')
  }
  console.log({session})

  const user = await db.user.findUnique({
    where: { id: session.id },
    select: { id: true, roles: true, email: true },
  })
  console.log({user})

  return user
}
```

**Comment by arioberek** [comment]
I've updated my `lib/auth.ts` to include the changes in the `getCurrentUser` function you provided:

```typescript
export const getCurrentUser = async (session: Decoded) => {
  if (!session || typeof session.id !== 'string') {
    throw new Error('Invalid session')
  }
  const user = await db.user.findUnique({
    where: { id: session.id },
    select: { id: true, email: true },
  })
  console.log({ user })

  return user
}
```
Second, I double-checked my users.sdl.ts file to ensure that the user id is set as a string, not a number:

```typescript
 type User {
    id: String!
    name: String!
    email: String!
    hashedPassword: String!
    salt: String!
    resetToken: String
    resetTokenExpiresAt: DateTime
  }
```

It seems like the `getCurrentUser` function might not be getting executed at all. I've included the console log and exception throw as you suggested, but neither of those are appearing in the console.

This leads me to suspect that the problem might be occurring before `getCurrentUser` has a chance to run.

**Comment by Josh-Walker-GM** [comment]
Hmm and there is no helpful output in the API logs when the the auth function fails? 

Thanks for working with me on this! If we don't make any progress with the API logs then I'll loop in some more help here.

**Comment by arioberek** [comment]
Sure! Thanks for your patience throughout this process.

I've included the logs starting from the moment I initiated the application through to the point where the bug is reproduced.

```
❯ yarn rw dev
gen | Generating TypeScript definitions and GraphQL schemas...
gen | 
gen | Error: Could not generate GraphQL type definitions (web)
gen | Error: GraphQL Document Validation failed with 1 errors;
gen |   Error 0: This anonymous operation must be the only defined operation.
gen |     at /Users/ari/www/notes/web/src/components/MessageForm/MessageForm.tsx:1:1
gen |     at codegen (/Users/ari/www/notes/node_modules/@graphql-codegen/core/cjs/codegen.js:83:19)
gen |     at async runCodegenGraphQL (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/graphqlCodeGen.js:131:18)
gen |     at async generateTypeDefGraphQLWeb (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/graphqlCodeGen.js:103:12)
gen |     at async generateTypeDefs (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/typeDefinitions.js:47:18)
gen |     at async generate (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/generate.js:17:25)
gen |     at async FSWatcher.<anonymous> (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/watch.js:42:17)
gen | 
gen | 59 files generated
api | Building... Took 1716 ms
api | Debugger listening on ws://127.0.0.1:18911/1ef1afad-bd9d-4acd-920f-c8704a9ff835
api | For help, see: https://nodejs.org/en/docs/inspector
api | Starting API Server...
api | Loading server config from /Users/ari/www/notes/api/server.config.js 
api | 
api | Importing Server Functions... 
web | (node:55958) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/ari/www/notes/node_modules/react-icons/package.json' of 'lib'. Please either fix that or report it to the module author
web | (Use `node --trace-deprecation ...` to show where the warning was created)
api | {
api |   "auth-provider": "dbAuth",
api |   "cookie": "session=73jsijzuh3UyZlaCsTE70BUEH9YDhy5GHWJ8j88FDjsjhusHDg43cMqWYzInRTvJHs4A==",
api |   "authorization": "Bearer 2"
api | }
api | /graphql 1495 ms
api | /auth 1 ms
api | ...Done importing in 1496 ms
api | 18:42:53 🐛 Fastify server configuration 
api | 🗒 Custom
api | {
api |   "connectionTimeout": 0,
api |   "keepAliveTimeout": 72000,
api |   "maxRequestsPerSocket": 0,
api |   "requestTimeout": 0,
api |   "requestIdHeader": "request-id",
api |   "requestIdLogLabel": "reqId",
api |   "disableRequestLogging": false,
api |   "bodyLimit": 1048576,
api |   "caseSensitive": true,
api |   "allowUnsafeRegex": false,
api |   "ignoreTrailingSlash": false,
api |   "ignoreDuplicateSlashes": false,
api |   "jsonShorthand": true,
api |   "maxParamLength": 100,
api |   "onProtoPoisoning": "error",
api |   "onConstructorPoisoning": "error",
api |   "pluginTimeout": 10000,
api |   "http2SessionTimeout": 72000,
api |   "exposeHeadRoutes": true
api | } 
api | 🗒 Custom
api | {
api |   "time": 1689543773633,
api |   "pid": 56016,
api |   "hostname": "Ari",
api |   "msg": "Fastify server configuration"
api | }
api | Took 1572 ms
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 18:42:53 🐛 Registered plugins 
api | bound root 1562 ms
api | ├── bound _after 4 ms
api | ├── @fastify/url-data 1 ms
api | ├── fastify-raw-body 1 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | └── bound _after 0 ms
api |  
api | 🗒 Custom
api | {
api |   "time": 1689543773634,
api |   "pid": 56016,
api |   "hostname": "Ari",
api |   "msg": "Registered plugins \nbound root 1562 ms\n├── bound _after 4 ms\n├── @fastify/url-data 1 ms\n├── fastify-raw-body 1 ms\n├── bound _after 0 ms\n├── bound _after 0 ms\n├── bound _after 0 ms\n└── bound _after 0 ms\n"
api | }
api | 18:42:53 🌲 Server listening at http://[::]:8911 
api | 🗒 Custom
api | {
api |   "time": 1689543773638,
api |   "pid": 56016,
api |   "hostname": "Ari",
api |   "msg": "Server listening at http://[::]:8911"
api | }
web | assets by path static/js/*.js 15.5 MiB
web |   asset static/js/TalkToPage.chunk.js 5.91 MiB [emitted] (name: TalkToPage) 1 related asset
web |   asset static/js/app.bundle.js 4.49 MiB [emitted] (name: app) 1 related asset
web |   asset static/js/ReceivedNotesPage.chunk.js 2.08 MiB [emitted] (name: ReceivedNotesPage) 1 related asset
web |   asset static/js/NoteNotesPage.chunk.js 2.08 MiB [emitted] (name: NoteNotesPage) 1 related asset
web |   asset static/js/UserUsersPage.chunk.js 257 KiB [emitted] (name: UserUsersPage) 1 related asset
web |   asset static/js/UserUserPage.chunk.js 256 KiB [emitted] (name: UserUserPage) 1 related asset
web |   asset static/js/NoteNotePage.chunk.js 255 KiB [emitted] (name: NoteNotePage) 1 related asset
web |   asset static/js/runtime-app.bundle.js 51 KiB [emitted] (name: runtime-app) 1 related asset
web |   + 6 assets
web | assets by path *.png 13.1 KiB
web |   asset logo.png 7.21 KiB [emitted] [from: public/logo.png] [copied]
web |   asset favicon.png 5.84 KiB [emitted] [from: public/favicon.png] [copied]
web | asset index.html 592 bytes [emitted]
web | asset robots.txt 26 bytes [emitted] [from: public/robots.txt] [copied]
web | Entrypoint app 4.54 MiB (4.15 MiB) = static/js/runtime-app.bundle.js 51 KiB static/js/app.bundle.js 4.49 MiB 2 auxiliary assets
web | orphan modules 802 KiB [orphan] 540 modules
web | runtime modules 34.3 KiB 19 modules
web | modules by path ../node_modules/ 7.52 MiB 1419 modules
web | modules by path ./ 847 KiB
web |   modules by path ./node_modules/ 490 KiB
web |     modules by path ./node_modules/framer-motion/dist/es/ 321 KiB 145 modules
web |     modules by path ./node_modules/@chakra-ui/ 170 KiB
web |       ./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js 6.63 KiB [built] [code generated]
web |       + 9 modules
web |   modules by path ./src/ 357 KiB
web |     modules by path ./src/components/ 132 KiB 25 modules
web |     modules by path ./src/pages/ 103 KiB 17 modules
web |     modules by path ./src/*.css 76.9 KiB 4 modules
web |     modules by path ./src/*.tsx 8.95 KiB 2 modules
web |     + 4 modules
web | webpack 5.88.1 compiled successfully in 11083 ms
```
_(The error occurs below)_

```
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
web |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
web |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
```

**Comment by Josh-Walker-GM** [comment]
Interesting so there are no logs for the API side for when the auth function is returning the 500?

For example if I manually throw an error in the auth function then I get lines like so in the dev server logs:
![image](https://github.com/redwoodjs/redwood/assets/56300765/96f2ef82-fcfe-4ccd-896d-3ccecca9890c)

**Comment by arioberek** [comment]
It appears that no logs are being generated from the API side.


I adjusted my getCurrentUser function to this:


```typescript
export const getCurrentUser = async (session: Decoded) => {
  throw new Error('test')
}
```

I believe the logs remain unchanged from before:


```
❯ yarn rw dev
gen | Generating TypeScript definitions and GraphQL schemas...
gen | 
gen | Error: Could not generate GraphQL type definitions (web)
gen | Error: GraphQL Document Validation failed with 1 errors;
gen |   Error 0: This anonymous operation must be the only defined operation.
gen |     at /Users/ari/www/notes/web/src/components/MessageForm/MessageForm.tsx:1:1
gen |     at codegen (/Users/ari/www/notes/node_modules/@graphql-codegen/core/cjs/codegen.js:83:19)
gen |     at async runCodegenGraphQL (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/graphqlCodeGen.js:131:18)
gen |     at async generateTypeDefGraphQLWeb (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/graphqlCodeGen.js:103:12)
gen |     at async generateTypeDefs (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/typeDefinitions.js:47:18)
gen |     at async generate (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/generate.js:17:25)
gen |     at async FSWatcher.<anonymous> (/Users/ari/www/notes/node_modules/@redwoodjs/internal/dist/generate/watch.js:42:17)
gen | 
gen | 59 files generated
api | Building... Took 439 ms
api | Debugger listening on ws://127.0.0.1:18911/efad9772-5ca0-4ee5-9e76-330ba0260ec4
api | For help, see: https://nodejs.org/en/docs/inspector
api | Starting API Server...
api | Loading server config from /Users/ari/www/notes/api/server.config.js 
api | 
api | Importing Server Functions... 
api | {
api |   "auth-provider": "dbAuth",
api |   "cookie": "session=z67565gyDYGEH9YDhy5GHWJ8MeYgl8PslpBa3KQsrlvNQOl3CVg43cMqWYzInRTvJHs4A==",
api |   "authorization": "Bearer 2"
api | }
api | /graphql 551 ms
api | /auth 1 ms
api | ...Done importing in 552 ms
api | 19:38:46 🐛 Fastify server configuration 
api | 🗒 Custom
api | {
api |   "connectionTimeout": 0,
api |   "keepAliveTimeout": 72000,
api |   "maxRequestsPerSocket": 0,
api |   "requestTimeout": 0,
api |   "requestIdHeader": "request-id",
api |   "requestIdLogLabel": "reqId",
api |   "disableRequestLogging": false,
api |   "bodyLimit": 1048576,
api |   "caseSensitive": true,
api |   "allowUnsafeRegex": false,
api |   "ignoreTrailingSlash": false,
api |   "ignoreDuplicateSlashes": false,
api |   "jsonShorthand": true,
api |   "maxParamLength": 100,
api |   "onProtoPoisoning": "error",
api |   "onConstructorPoisoning": "error",
api |   "pluginTimeout": 10000,
api |   "http2SessionTimeout": 72000,
api |   "exposeHeadRoutes": true
api | } 
api | 🗒 Custom
api | {
api |   "time": 1689806326379,
api |   "pid": 63272,
api |   "hostname": "Ari.local",
api |   "msg": "Fastify server configuration"
api | }
api | Took 583 ms
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 19:38:46 🐛 Registered plugins 
api | bound root 576 ms
api | ├── bound _after 4 ms
api | ├── @fastify/url-data 0 ms
api | ├── fastify-raw-body 1 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | └── bound _after 1 ms
api |  
api | 🗒 Custom
api | {
api |   "time": 1689806326380,
api |   "pid": 63272,
api |   "hostname": "Ari.local",
api |   "msg": "Registered plugins \nbound root 576 ms\n├── bound _after 4 ms\n├── @fastify/url-data 0 ms\n├── fastify-raw-body 1 ms\n├── bound _after 0 ms\n├── bound _after 0 ms\n├── bound _after 0 ms\n└── bound _after 1 ms\n"
api | }
api | 19:38:46 🌲 Server listening at http://[::]:8911 
api | 🗒 Custom
api | {
api |   "time": 1689806326382,
api |   "pid": 63272,
api |   "hostname": "Ari.local",
api |   "msg": "Server listening at http://[::]:8911"
api | }
web | (node:63240) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/ari/www/notes/node_modules/react-icons/package.json' of 'lib'. Please either fix that or report it to the module author
web | (Use `node --trace-deprecation ...` to show where the warning was created)
web | assets by path static/js/*.js 15.6 MiB
web |   asset static/js/TalkToPage.chunk.js 5.95 MiB [emitted] (name: TalkToPage) 1 related asset
web |   asset static/js/app.bundle.js 4.53 MiB [emitted] (name: app) 1 related asset
web |   asset static/js/ReceivedNotesPage.chunk.js 2.12 MiB [emitted] (name: ReceivedNotesPage) 1 related asset
web |   asset static/js/NoteNotesPage.chunk.js 2.11 MiB [emitted] (name: NoteNotesPage) 1 related asset
web |   asset static/js/UserUsersPage.chunk.js 257 KiB [emitted] (name: UserUsersPage) 1 related asset
web |   asset static/js/UserUserPage.chunk.js 256 KiB [emitted] (name: UserUserPage) 1 related asset
web |   asset static/js/NoteNotePage.chunk.js 255 KiB [emitted] (name: NoteNotePage) 1 related asset
web |   asset static/js/runtime-app.bundle.js 51 KiB [emitted] (name: runtime-app) 1 related asset
web |   + 6 assets
web | assets by path *.png 13.1 KiB
web |   asset logo.png 7.21 KiB [emitted] [from: public/logo.png] [copied]
web |   asset favicon.png 5.84 KiB [emitted] [from: public/favicon.png] [copied]
web | asset index.html 11.6 KiB [emitted]
web | asset robots.txt 26 bytes [emitted] [from: public/robots.txt] [copied]
web | Entrypoint app 4.58 MiB (4.19 MiB) = static/js/runtime-app.bundle.js 51 KiB static/js/app.bundle.js 4.53 MiB 2 auxiliary assets
web | orphan modules 802 KiB [orphan] 540 modules
web | runtime modules 34.3 KiB 19 modules
web | modules by path ../node_modules/ 7.52 MiB 1419 modules
web | modules by path ./ 959 KiB
web |   modules by path ./node_modules/ 490 KiB
web |     modules by path ./node_modules/framer-motion/dist/es/ 321 KiB 145 modules
web |     modules by path ./node_modules/@chakra-ui/ 170 KiB
web |       ./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js 6.63 KiB [built] [code generated]
web |       + 9 modules
web |   modules by path ./src/ 469 KiB
web |     modules by path ./src/components/ 207 KiB 25 modules
web |     modules by path ./src/pages/ 103 KiB 17 modules
web |     modules by path ./src/*.css 76.9 KiB 4 modules
web |     modules by path ./src/*.tsx 8.95 KiB 2 modules
web |     + 4 modules
web | webpack 5.88.1 compiled successfully in 6107 ms
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
web |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
web |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web | TypeError: Request path contains unescaped characters
web |     at new NodeError (node:internal/errors:399:5)
web |     at new ClientRequest (node:_http_client:184:13)
web |     at Object.request (node:http:98:10)
web |     at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
web |     at ProxyServer.<anonymous> (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
web |     at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)

```

**Comment by Josh-Walker-GM** [comment]
Interesting... Let's call in the dbAuth expert - @cannikin any ideas on what could be the issue here?

I'm surprised at the no API logs. Feels like that means we hit the web side with something malformed and it doesn't even proxy it to the API. Maybe seeing the raw headers and url/body of the request that's failing will help? It's only the auth requests that fail and not the graphql ones yeah?

**Comment by cannikin** [comment]
That sounds like me like the actual URL that the auth function is being called at is messed up for some reason... it would normally be something like `http://localhost:8910/.redwood/functions.auth.js` Can you check the Web Inspector in your browser @arioberek and see what URL is being requested? For example, I see:

<img width="383" alt="image" src="https://github.com/redwoodjs/redwood/assets/300/dfe3ebd9-77b4-42b3-8a25-7371200064b7">

And the payload looks something like:

<img width="492" alt="image" src="https://github.com/redwoodjs/redwood/assets/300/25c7e8a9-ed32-4c70-b856-0d726f2995bd">

**Comment by arioberek** [comment]
Sure! Here is the URL being requested:

<img width="691" alt="image" src="https://github.com/redwoodjs/redwood/assets/25717193/c6db56c2-ff3c-4f0f-96c7-92c3c5dede77">

And this is the payload I used:

<img width="705" alt="image" src="https://github.com/redwoodjs/redwood/assets/25717193/c8712fa8-314f-4357-912e-baa83e0cfc62">

**Comment by cannikin** [comment]
Anything in the response?

**Comment by cannikin** [comment]
One thing I noticed, mine has the following for Remote Address:

<img width="266" alt="image" src="https://github.com/redwoodjs/redwood/assets/300/c6a8848b-9a8b-434d-99eb-a5b0c8be5d23">

Yours has an IPv6 address...I remember something a while ago about IPv6 causing issues. Can you get it to connect via 127.0.0.1 instead of [::1]? What's your `/etc/hosts` file look like? Mine has:

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

Maybe it goes through them in order and because my IPv4 one is first that's what's used?

**Comment by arioberek** [comment]
The following screenshot displays the content of my `/etc/hosts` file:

![hosts file content](https://github.com/redwoodjs/redwood/assets/25717193/1300ce78-42ad-4339-81b6-b1e14e1dd135)

Additionally, this is the response I received from `/auth`:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>
            TypeError: Request path contains unescaped characters<br>
            &nbsp;&nbsp;at new NodeError (node:internal/errors:399:5)<br>
            &nbsp;&nbsp;at new ClientRequest (node:_http_client:184:13)<br>
            &nbsp;&nbsp;at Object.request (node:http:98:10)<br>
            &nbsp;&nbsp;at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)<br>
            &nbsp;&nbsp;at ProxyServer.&lt;anonymous &gt;(/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)<br>&nbsp;&nbsp;at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
        </pre>
    </body>
</html>
```
After checking my IP address on [whatismyipaddress](https://whatismyipaddress.com), it appears that I'm utilizing IPv4:

![IP check](https://github.com/redwoodjs/redwood/assets/25717193/774e35f5-9a72-4b9e-816e-3bc6beab55e5)

**Comment by Josh-Walker-GM** [comment]
Is this error returned even if you make a request via the command line with something like curl? Something like: `curl -G http://localhost:8910/api/auth?method=getToken`

**Comment by arioberek** [comment]
Yes, the same error persists. Below is the output from my terminal:


```
curl -G http://localhost:8910/api/auth?method=getToken
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Request path contains unescaped characters<br> &nbsp; &nbsp;at new NodeError (node:internal/errors:399:5)<br> &nbsp; &nbsp;at new ClientRequest (node:_http_client:184:13)<br> &nbsp; &nbsp;at Object.request (node:http:98:10)<br> &nbsp; &nbsp;at Array.stream (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)<br> &nbsp; &nbsp;at ProxyServer.&lt;anonymous&gt; (/Users/ari/www/notes/node_modules/http-proxy/lib/http-proxy/index.js:81:21)<br> &nbsp; &nbsp;at HttpProxyMiddleware.middleware (/Users/ari/www/notes/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</pre>
</body>
</html>
```

**Comment by cannikin** [comment]
What if you access the site via http://127.0.0.1:8910 instead of localhost?

**Comment by arioberek** [comment]
It seems I am not able to access using `http://127.0.0.1:8910/` instead of `http://localhost:8910`. When I access the application using `http://127.0.0.1:8910`, I don't see any changes in the logs. 


<img width="758" alt="image" src="https://github.com/redwoodjs/redwood/assets/25717193/9ce62398-5d6f-487b-a688-3214cfa59957">

```
curl -G http://127.0.0.1:8910/api/auth?method=getToken
curl: (7) Failed to connect to 127.0.0.1 port 8910 after 4 ms: Couldn't connect to server
```

**Comment by cannikin** [comment]
You may have to do two things to get the site accessible via 127.0.0.1 (or any other IP, like from within your home network):

Add `bind` command to your `redwood.toml` file:

```diff
[web]
  title = "App"
+ host = "0.0.0.0"
  port = 8910
  apiUrl = "/api"
[api]
+ host = "0.0.0.0"
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ['latest']
```

Start the dev server with an additional flag:

```
yarn rw dev --fwd="--allowed-hosts all"
```

**Comment by arioberek** [comment]
Thanks for the guidance! I've successfully launched the application on `127.0.0.1:8910`. Yet, it seems the problem continues to occur in a similar fashion.

https://github.com/redwoodjs/redwood/assets/25717193/e344dba9-fc29-4422-b862-8ef5f3692938

**Comment by cannikin** [comment]
Okay how about this. This command will create an entire sample app from scratch, including login. If this works, but your app doesn't, then it must be something you customized somewhere. If the sample app doesn't work either, then there must be something else going on with your system...

Check out the full redwoodjs codebase:

```
git clone git@github.com:redwoodjs/redwood.git
```

Do a `yarn install` and then build a test project:

```
yarn install
yarn build:test-project ~/redwood-test-project
```

Go to that directory and startup the dev server with `yarn rw dev` and then go to the signup page, create an account, then log out and back in again. Does it work?

**Comment by Josh-Walker-GM** [comment]
Hey @arioberek - I wanted to check back on this and ask if you managed to move past this or if there is more work to be down tracking this down further?
