### ISSUE TITLE
[Bug]: GraphQL syntax error does not tell you where the error is

### ISSUE THREAD

**Issue by orta** [redwoodjs/redwood#9051]
### What's not working?

Somewhere in my app, there is a syntax error in the sdl:

```
api | /home/orta/dev/app/node_modules/graphql/error/syntaxError.js:15
api |   return new _GraphQLError.GraphQLError(`Syntax Error: ${description}`, {
api |          ^
api | 
api | GraphQLError: Syntax Error: Unexpected single quote character ('), did you mean to use a double quote (")?
api |     at syntaxError (/home/orta/dev/app/node_modules/graphql/error/syntaxError.js:15:10)
api |     at readNextToken (/home/orta/dev/app/node_modules/graphql/language/lexer.js:420:40)
api |     at Lexer.lookahead (/home/orta/dev/app/node_modules/graphql/language/lexer.js:84:29)
api |     at Lexer.advance (/home/orta/dev/app/node_modules/graphql/language/lexer.js:67:38)
api |     at Parser.advanceLexer (/home/orta/dev/app/node_modules/graphql/language/parser.js:1536:31)
api |     at Parser.expectOptionalToken (/home/orta/dev/app/node_modules/graphql/language/parser.js:1412:12)
api |     at Parser.parseTypeReference (/home/orta/dev/app/node_modules/graphql/language/parser.js:691:14)
api |     at Parser.parseFieldDefinition (/home/orta/dev/app/node_modules/graphql/language/parser.js:839:23)
api |     at Parser.optionalMany (/home/orta/dev/app/node_modules/graphql/language/parser.js:1492:28)
api |     at Parser.parseFieldsDefinition (/home/orta/dev/app/node_modules/graphql/language/parser.js:822:17) {
api |   path: undefined,
api |   locations: [ { line: 75, column: 23 } ],
api |   extensions: [Object: null prototype] {}
api | }
```

However, this message gives me no clue where that is! It was on the correct line (75) so there's probably somewhere where we need to pass the correct filename information to be able to get back to it in the message

### How do we reproduce the bug?

For the above, take .sdl.ts file and accidentally add a  `'` at the end of a line

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by orta** [comment]
The source attribute on the error is correctly set up, the log which would traditionally tell you the path in the error is behind s `process.env.DEBUG` check

**Comment by orta** [comment]
Yeah, this isn't really solvable from the API level we're at - loadSchema triggers the code files which catch the errors and eventually throw, but by the time we get any errors we get a "hey this thing which relies on the SDL that has syntax errors has broken" which is the only error we can work with

We'd need the loadSchema to have a different error reporting path than just throwing a single error to have much nuance here
