### ISSUE TITLE
[Bug]: Cannot find package 'babel-plugin-graphql-tag'

### ISSUE THREAD

**Issue by eyassud** [redwoodjs/redwood#9156]
### What's not working?

I am new to Redwood and I am just following the tutorial you provide.

I completed chapter 7 as per the instructions of the tutorial and before going further, I want to upgrade from version 6.0.0 to 6.2.0.

I ran `yarn rw upgrade` and then `yarn rw dev `.

I received the following run time exception.

[```
plugin:vite:react-babel] Cannot find package 'babel-plugin-graphql-tag' imported from C:\GitHub\redwood-tutorial\web\babel-virtual-resolve-base.js
C:/GitHub/redwood-tutorial/web/src/entry.client.jsx
    at new NodeError (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:203:5)
    at packageResolve (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:873:9)
    at moduleResolve (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:902:20)
    at defaultResolve (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:985:15)
    at resolve (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:999:12)
    at tryImportMetaResolve (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\files\plugins.js:137:45)
    at resolveStandardizedNameForImport (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\files\plugins.js:159:19)
    at resolveStandardizedName (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\files\plugins.js:168:12)
    at loadPlugin (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\files\plugins.js:47:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at step (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:261:32)
    at evaluateAsync (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:291:5)
    at C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:43:15)
    at Function.all (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-descriptors.js:65:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\gensync-utils\async.js:21:3)
    at Generator.next (<anonymous>)
    at step (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:269:25)
    at evaluateAsync (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:291:5)
    at Function.errback (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:113:7)
    at errback (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\gensync-utils\async.js:66:18)
    at async (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:188:17)
    at onFirstPause (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at mergeChainOpts (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-chain.js:350:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-chain.js:317:14)
    at chainWalker.next (<anonymous>)
    at buildRootChain (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\config-chain.js:57:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\config\full.js:36:46)
    at loadFullConfig.next (<anonymous>)
    at transform (C:\GitHub\redwood-tutorial\node_modules\@babel\core\lib\transform.js:20:44)
    at transform.next (<anonymous>)
    at step (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:269:25)
    at evaluateAsync (C:\GitHub\redwood-tutorial\node_modules\gensync\index.js:291:5
```

### How do we reproduce the bug?

_No response_

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Thanks for reporting this @eyassud and getting involved with redwood! It's great to see new people checking us out!

We have noticed this issue recently and are working on a fix which we will try to get out asap. If you need to keep moving forward in the meantime I have had some success with adding the following dependencies to the root package.json:
```
"dependencies": {
  "@babel/plugin-transform-runtime": "^7.22.15",
  "babel-plugin-graphql-tag": "^3.3.0"
}
```
That's only intended as a quick workaround until we patch the issue though.

**Comment by eyassud** [comment]
@Josh-Walker-GM  Thank you for a great product and responding so quickly.  I will use the workaround you provided.

**Comment by jtoar** [comment]
Hey @eyassud, could you remove the workaround and try the patch I just released when you get the chance? Keeping that package around explicitly will probably cause more errors in the future: https://github.com/redwoodjs/redwood/releases/tag/v6.2.1
